### PR TITLE
[MRTK3] Migrating important example scenes from MRTK2

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
Adding some example scenes for the high-priority features frequently used by customers from v2:
- TapToPlace Example: Known issue - only magnetic behavior works when 'auto start' is checked. Select (pickup/place)behavior is not working. Need engineering investigation on input/interactor.
 
- Clipping Example
- Outline Example
- Solver Example (Follow / RadialView / InBetween)
- Directional Indicator Example

2022-05-02 22_10_02-MRTKDevTemplate - ClippingExamples - PC, Mac   Linux Standalone - Unity 2020 3 3

2022-05-02 22_59_32-MRTKDevTemplate - OutlineExamples - PC, Mac   Linux Standalone - Unity 2020 3 30

2022-05-03 12_50_33-MRTKDevTemplate - SolverExamples - PC, Mac   Linux Standalone - Unity 2020 3 30f

Known issue - only magnetic behavior works when 'auto start' is checked. Select (pickup/place)behavior is not working. 
TapToPlace_RayInteractor_Autostart

2022-05-03 13_22_27-MRTKDevTemplate - DirectionalIndicatorExample - PC, Mac   Linux Standalone - Uni

2022-05-03 23_30_36-MRTKDevTemplate - TapToPlaceExample - Universal Windows Platform - Unity 2020 3

### CODE REVIEW

**Comment by Zee2** [comment]
I'd recommend we do not port the Solvers scenes until @RogPodge's work on unifying and rewriting the solvers + constraints systems is done.

**Review by Zee2 — CHANGES_REQUESTED** [review]
Going to hold this until @RogPodge 's refactor happens; unless the team thinks otherwise

**Comment by cre8ivepark** [comment]
> I'd recommend we do not port the Solvers scenes until @RogPodge's work on unifying and rewriting the solvers + constraints systems is done.

Sounds great!

**Comment by RogPodge** [comment]
I think it may take some time to rewrit the solver system, I'm ok with the solver scene getting ported within this PR, so as to not block the migration of the other scenes.

It might be good to bring back the Experimental folder? This way, we can at least stage components and tools we think will require significant breaking changes in the future.

**Review by RogPodge — APPROVED** [review]

**Review by Zee2 — CHANGES_REQUESTED** [review]
@RogPodge , in my opinion we really shouldn't be merging/porting sample scenes for systems we know will be removed in the (near) future. Was there a discussion on this while I was gone?

**Comment by AMollis** [comment]
Created task to track this work

- https://github.com/orgs/microsoft/projects/575/views/11?filterQuery=+-status%3ACut+sample&pane=issue&itemId=26324193

**Comment by AMollis** [comment]
Closing PR.  These changed merged with @marlenaklein-msft PR:

- https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11522

**Pull request closed without merging**
