### PR TITLE
Turn off input simulation indicators

### PR DESCRIPTION
**Pull request by julenka**
## Overview
UPDATE: This PR originally moved input simulation indicators to the sides and updates the reset button to look like a 'refresh' button. However, after moving indicators to the side, raycasts related to Unity UI began failing. Since the indicators as they are are too visually distracting from interaction, check them in as off by default. Filed #6106 to track turning them back on. The indicators as they are checked in will be on the sides, with correct refresh buttons.

image

## Changes
- Fixes: #6023

### CODE REVIEW

**Comment by julenka** [comment]
@cre8ivepark  could i please get some help with the reset icons?

**Comment by cre8ivepark** [comment]
Updated reset icon.
2019-09-24 14_42_11-Unity 2018 4 6f1 Personal - BoundingBoxExamples unity - MRTK-Public-Microsoft -

**Comment by Troy-Ferrell** [comment]
@julenka, should we set hide flags on the indicators in inspector?

Also how does one show/hide the indicators?

image

**Comment by julenka** [comment]
> @julenka, should we set hide flags on the indicators in inspector?
> 
> Also how does one show/hide the indicators?
> 
> image

I would rather not. Hiding stuff in the inspector tends to make devs feel less in control, I find.

**Comment by julenka** [comment]
> Also how does one show/hide the indicators?

You can set the 'indicators' prefab to none in the profile. On the sides the indicators are not too intrusive actually.

**Comment by julenka** [comment]
UPDATE:, after moving indicators to the side, raycasts related to Unity UI began failing. Since the indicators as they are are too visually distracting from interaction, check them in as off by default. Filed #6106 to track turning them back on. The indicators as they are checked in will be on the sides, with correct refresh buttons.

**Pull request merged**
