### PR TITLE
Fix teleport to match current shell and update stage to not move during teleport

### LINKED ISSUE #843: Teleport and other controls should match the shell
Right now the HTK has a teleport script which uses the Xbox Y button for teleport, and the bumpers for rotation.  However, in the recent versions of the Mixed Reality Portal, the navigation uses the left thumb stick forward to teleport, and the right thumbstick to rotate.  

I think it would be best if the default behavior of the HTK matched that of the shell.

Thoughts?

### PR DESCRIPTION
**Pull request by keveleigh**
Fixes #843.

Use MotionControllerTest.unity to test.

### CODE REVIEW

**Comment by jessemcculloch** [comment]
Hey @keveleigh - When I tested this with my Xbox One S Bluetooth Controller, It seems like my left stick Y axis is backwards.  For example, when I pressed it down/back, it teleported, and when pressing up/forward, it moved me backwards.

I checked my Input settings in Unity and my mappings are not inverted at all.

Can you verify?  This was using the test scene you mentioned.

**Comment by StephenHodgson** [comment]
When testing this out without a HMD connected the editor crashes for me in b10

**Comment by keveleigh** [comment]
@jessemcculloch Ahh interesting, I'm seeing that too! I could have sworn it was right when I tested it...I'm not sure what could be causing that.

@StephenHodgson Hmm, I know there have been some OS-level changes recently that cause weirdness depending on the Unity & Windows combination you're using. I'm not sure if those changes/fixes have reached the public branches yet. Are you on 16288?

**Comment by StephenHodgson** [comment]
> Are you on 16288?

I am, is that no bueno?

**Comment by keveleigh** [comment]
I don't believe the changes are there, though 16288 is the latest public. I'm on a different update path, so I think the changes haven't made their way up yet.

I *believe* the crash has to do with accessing InteractionManager. Does it still crash if you get rid of any lines that do?

**Comment by jessemcculloch** [comment]
The Unity input mappings are correct.  Not sure what is going on there.

I am also seeing the crash when there is no headset connected, but it works fine when connected

**Comment by StephenHodgson** [comment]
It could  be that we're accidentally flipping the input by the way we're doing the math.

**Comment by jessemcculloch** [comment]
So, the crash when hitting play while no headset is connected has something to do with the Fade Script.  Still trying to narrow it down past that.

**Comment by keveleigh** [comment]
I'm unable to repro your experience with the fade script. I've removed it from several scenes and still see a crash. From my experience, I believe it has to do with accessing the InteractionManager.

I'm able to repro it by:
1. Create a new scene.
2. Hit play. Doesn't crash.
3. Create a new script. Only add an event handler for some event on InteractionManager: 
image
4. Put that script somewhere in the scene.
5. Hit play. Crashes.

**Comment by darax** [comment]
Interesting stack for the crash:
>	Unity.exe!SpatialInputImpl::SetEventHandlerAndAttach(void (*)(struct SourceEventType,struct SourceState,struct SourcePressType))	Unknown	Symbols loaded.
 	0000000017640925()	Unknown	No symbols loaded.
 	0000000017640680()	Unknown	No symbols loaded.
 	000000004acb2110()	Unknown	No symbols loaded.
 	0000000002bf0c00()	Unknown	No symbols loaded.
 	000000005c77ace8()	Unknown	No symbols loaded.
 	00000000005fcff0()	Unknown	No symbols loaded.
 	0000000017640680()	Unknown	No symbols loaded.
 	000000002a840000()	Unknown	No symbols loaded.
 	00000000005fd600()	Unknown	No symbols loaded.
 	0000000042f87db0()	Unknown	No symbols loaded.
 	000000000000000e()	Unknown	No symbols loaded.
 	000000001764046c()	Unknown	No symbols loaded.
 	000000004acb2110()	Unknown	No symbols loaded.
 	00000000005fcfb0()	Unknown	No symbols loaded.
 	00000000005fcf10()	Unknown	No symbols loaded.
 	00000000005fd318()	Unknown	No symbols loaded.
 	0000000042df6aa0()	Unknown	No symbols loaded.

**Comment by keveleigh** [comment]
Looks like Unity inverts the vertical axis by default:
image

I've added the inversion to the two ControllerStickY axes we added.

**Comment by DDReaper** [comment]
@darax I think the crashing bug is to do with Unity, possibly also related to whether a boundary is setup or not (or if MR portal isn't running).  logged #988 to track.

**Comment by DDReaper** [comment]
OK, two observations:
1: Project will crash when run from the editor if the Platform is NOT set to UWP :D Could probably do with an editor script to check the editor platform runtime on play
2: Using the Original Xbox One controller through wireless doesn't work.  No input from controller at all.

Sadly, don't have controllers yet so can't test those.

@keveleigh could you add a third column to the Debug view to also show the Xbox Controller debug status in this PR?  Or should it be separate?

**Comment by keveleigh** [comment]
@DDReaper For point 2, are you referring to using one of [these](https://www.xbox.com/en-US/xbox-one/accessories/controllers/windows-wireless-adapter)? I've tested the scene with a Bluetooth controller, and it works. Unfortunately, I don't have one of those adapters.

Yeah, I'll look into adding the Xbox debug status as well, though it might be worth waiting for master, since @StephenHodgson added the new Xbox work there.

**Comment by StephenHodgson** [comment]
@DDReaper, yeah I'm working on a different test scene for the Xbox implementation, although maybe when I get it into the dev branch, we can merge those test scenes.

**Comment by StephenHodgson** [comment]
Finally got this to run after making sure I launch and run in the right order haha.

**Comment by DDReaper** [comment]
Right, after a LOT of testing, this needs merging now as it fixes a whole load of issues @StephenHodgson 
He current Dev branch doesn't work as the MR camera is floating above the scene and the ground is off.  Also Xbox controller functions don't work.

This fixes all those issues and re-enables the Xbox controller to work properly.

**Comment by jessemcculloch** [comment]
@keveleigh - Getting lots of thanks over in the HoloDevelopers Slack for this pull request, so I am passing them along to you 💯 🥇

**Comment by keveleigh** [comment]
@jessemcculloch Thanks for letting me know! Happy to hear that!!

**Comment by DDReaper** [comment]
+10 from me. Makes the project work properly for immersive now. Keep up the great work @keveleigh

**Pull request merged**
