### PR TITLE
Editor update 2018.3.0f2

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Updates the [project's editor to 2018.3.02f](https://unity3d.com/unity/whats-new/unity-2018.3.0)

Key changes:
---
- .net 4.x equivalent is the default editor scripting runtime, and we no longer need to have the embedded dll for updating it.
- Updated prefabs will not be backwards compatible with prev versions of the editor.

Changes
---
- Fixes: #3192 
- Fixes: #3183

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Ready for review.

All tests pass.

UWP and Standalone builds pass and run.

**Comment by StephenHodgson** [comment]
> Does this change remove the need for #3248?

... no?

**Comment by davidkline-ms** [comment]
I'm hitting a CS0019 in SystemType when trying to build the project (UWP target, .net backend) that I do not recall from 2018.2.  Investigating now.

**Comment by davidkline-ms** [comment]
Assets\MixedRealityToolkit\_Core\Definitions\Utilities\SystemType.cs(46,21): error CS0019: Operator '&&' cannot be applied to operands of type 'bool' and 'method group'

```
                if (Type != null && Type.IsAbstract)
```

**Comment by davidkline-ms** [comment]
Feels like we have seen this before.... trying to find the related issue / pr

**Comment by StephenHodgson** [comment]
> UWP target, .net backend

Why are you even trying that? It's marked deprecated and will be removed very soon.

**Comment by davidkline-ms** [comment]
> Why are you even trying that? It's marked deprecated and will be removed very soon.

Because it makes debugging easier, and unity has committed to supporting the .net backend in 2018's LTS for the next 2 years.

**Comment by StephenHodgson** [comment]
Makes no difference. We shouldn't be supporting it anyway.

**Comment by davidkline-ms** [comment]
To best support the maximum number of customers, we should support the maximum functionality provided by Unity.

**Comment by StephenHodgson** [comment]
> maximum functionality provided by Unity

You mean when I opened a bug report on something for .net a few months back and they told me to use IL2CPP cause they weren't committed to fixing it?

**Comment by StephenHodgson** [comment]
To best support our customers we shouldn't be using deprecated features.

**Comment by keveleigh** [comment]
>To best support our customers we shouldn't be using deprecated features.

We aren't forcing customers to use deprecated features, but are providing them the option to if they choose to.

Our publicly stated support level has been that we will enable building the Toolkit with the .NET backend as long as it ships with a version of Unity we support. If Unity has bugs, we can't control that, but we can give our customers the choice.

**Comment by StephenHodgson** [comment]
> Our publicly stated support level has been that we will enable building the Toolkit with the .NET backend

I didn't agree to that. I guess we'll agree to disagree here.

In either case, I don't understand why a deprecated feature should block a PR.

**Comment by davidkline-ms** [comment]
> I don't understand why a deprecated feature should block a PR.

Trying to understand the source of the issue as very recently I was able to build using the .net backend on 2018.2.

**Comment by keveleigh** [comment]
>In either case, I don't understand why a deprecated feature should block a PR.

It was being discussed here because it was discovered while testing this PR, but I'm pretty sure it's not a blocker here if it isn't 2018.3-specific.

**Comment by davidkline-ms** [comment]
We had a fix for a very similar issue in June (2018). I am more than happy to (re)apply the same logic.

https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/cb4feb50de5af307b30ad253aba37f8657ad2a57#diff-9be24a654529dda945cca11020cecab8

**Comment by StephenHodgson** [comment]
Sounds good. likely do it as a separate PR.

**Comment by SimonDarksideJ** [comment]
Interesting, why would we get a missing package for Oculus when we don't support it yet.  Best to ensure oculus isn't in the supported SDK's rather than include the package ref

**Comment by davidkline-ms** [comment]
#3273 is tracking the net backend compile issue. PR forthcoming.

**Comment by davidkline-ms** [comment]
Just to be super clear, if we take this change, we are breaking support for previous Unity releases (many package manager errors on load, MethodAccess exceptions, etc). 

Are we comfortable requiring everyone to move to 2018.3?

My intuition says it is the right thing to do as we are currently planning on requiring Unity 2018.4 upon release. 

Asking this question here to gather community feedback prior to the change.

**Comment by wassx** [comment]
We are testing it on our side. Due to the fix of #3183 it looks promising.

**Comment by StephenHodgson** [comment]
Always forwards, never backwards.

We're still in beta and we all agreed to update until we made our first release.

**Comment by StephenHodgson** [comment]
The player settings quick link is broken in the build window for 2018.3 as well.

image

Tried looking though the [CS reference](https://github.com/Unity-Technologies/UnityCsReference/search?q=ExecuteMenuItem&unscoped_q=ExecuteMenuItem) to see what they changed it to, but apparently it's completely gone now?

**Pull request closed without merging**
