### PR TITLE
Update SceneSystemGettingStarted.md

### PR DESCRIPTION
**Pull request by sostel**
Several typo fixes. 
By the way, there is no " ! [ ] (../Images/SceneSystem/MRTK_SceneSystemProfileEditorSettings.png)"

### CODE REVIEW

**Comment by thalbern** [comment]
> Several typo fixes.
> By the way, there is no " ! [ ] (../Images/SceneSystem/MRTK_SceneSystemProfileEditorSettings.png)"

file exists for me in mrtk_development

**Comment by sostel** [comment]
> > Several typo fixes.
> > By the way, there is no " ! [ ] (../Images/SceneSystem/MRTK_SceneSystemProfileEditorSettings.png)"
> 
> file exists in mrtk_development https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/Images/SceneSystem/MRTK_SceneSystemProfileEditorSettings.PNG

No picture is displayed though when I click on the page. Seems the relative reference is incorrect then. It seems that the system is picky about the lower-/uppercasing of the "PNG" part. Either change the file name to a lowercase png or change it in the text. Otherwise nothing is displayed.

image

**Comment by thalbern** [comment]
> > > Several typo fixes.
> > > By the way, there is no " ! [ ] (../Images/SceneSystem/MRTK_SceneSystemProfileEditorSettings.png)"
> > 
> > 
> > file exists in mrtk_development https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/Images/SceneSystem/MRTK_SceneSystemProfileEditorSettings.PNG
> 
> No picture is displayed though when I click on the page. It seems that the system is picky about the lower-/uppercasing of the "PNG" part. Either change the file name to a lowercase png or change it in the text. Otherwise nothing is displayed.
> 
> image

oh yes you're right! I didn't realize the file ending bc the docfx build didn't report it as an error either (that process should actually check any relative broken link)

**Comment by sostel** [comment]
> > > > Several typo fixes.
> > > > By the way, there is no " ! [ ] (../Images/SceneSystem/MRTK_SceneSystemProfileEditorSettings.png)"
> > > 
> > > 
> > > file exists in mrtk_development https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/Images/SceneSystem/MRTK_SceneSystemProfileEditorSettings.PNG
> > 
> > 
> > No picture is displayed though when I click on the page. It seems that the system is picky about the lower-/uppercasing of the "PNG" part. Either change the file name to a lowercase png or change it in the text. Otherwise nothing is displayed.
> > image
> 
> oh yes you're right! I didn't realize the file ending bc the docfx build didn't report it as an error either (that process should actually check any relative broken link)

Yeah, weird! I would have also thought it would throw some broken link error. I guess, we could advise to use some alternative text in the square brackets to make it more obvious for a visual check at least.

**Pull request merged**
