### PR TITLE
Pass correct Unity version for each of the agent pools

### PR DESCRIPTION
**Pull request by macborow**
This change addresses problems introduced in PR #7390 - i.e. it allows to use a different version of Unity when building on internal agents.
Unfortunately, it turns out that variable expansion still doesn't work when specifying agent capabilities, so I wasn't able to remove all duplication (although I made sure that the version numbers in "demands" sections are filled in consistently)

### CODE REVIEW

**Comment by davidkline-ms** [comment]
Looks like building the standalone player failed:

https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=9766&view=logs&j=c1841906-0df4-5516-e3c5-68840a78c082&t=28dd5aec-e719-511a-e8f9-abca8b0210a6

**Comment by macborow** [comment]
> Looks like building the standalone player failed:

Variable expansion uses $() and parameter expansion uses ${}. It's consistently confusing :/

**Comment by macborow** [comment]
FYI, I created a feature request for variable expansion in agent pool "demands" - please up-vote when you get a chance:
https://developercommunity.visualstudio.com/idea/931161/variables-expansion-should-work-in-demands-section.html

**Pull request merged**
