### PR TITLE
Update min version of DotNetWinRT to latest (0.5.1049)

### PR DESCRIPTION
**Pull request by davidkline-ms**
This change instructs MSBuild for Unity to the latest version, as of 2020-05-04. This version adds new functionality.

### CODE REVIEW

**Comment by keveleigh** [comment]
Should we update it in the nuspec too?

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/274399fed1fb9fa2f29ec05d73f359ba4e8ec640/Assets/MixedReality.Toolkit.Foundation.nuspec#L17

**Comment by davidkline-ms** [comment]
>Should we update it in the nuspec too?

We should. Thanks for the catch!

**Comment by wiwei** [comment]
@davidkline-ms can you add a few notes here about what you're doing to test these upgrades? i.e. should we be trying the remoting (or any other scenarios) each time we do something like this

**Comment by davidkline-ms** [comment]
I confirmed that the adapter successfully downloads and that it is dated at leat 04/14/2020 (the publication date).

For those with a sufficiently strong GPU, please confirm that remoting of hands continues to work on HoloLens 2.

**Comment by keveleigh** [comment]
Can also check the holographic reprojection settings on-device, which depend on DotNetWinRT

**Comment by wiwei** [comment]
@davidkline-ms I think going forward we should make sure that we've done some verification on the core scenarios this powers before submitting - in case there are regressions in the plugin itself or in our usage of it.

**Pull request merged**
