### PR TITLE
Add tests for data provider registeration

### PR DESCRIPTION
**Pull request by Troy-Ferrell**
## Overview

Data provider registration has changed dramatically in the stabilization branch. As per desires for original design, ownership of dataprovider registeration has moved entirely to the particular MixedRealityService utilizing that DataProvider. These tests are added to get coverage on this paradigm.

## Changes
- Fixes: #5563 

## Verification
All tests pass

> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by wiwei** [comment]
Changes look good - just a warning, this will probably conflict with stuff currently sitting in mrtk_development:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5570

I don't think these tests need to be targetted to this branch, given that the tests are for folks working on the project, rather than folks consuming it.

@Troy-Ferrel, what are you thoughts on retargetting to mrtk_development and getting it in there instead?

**Comment by davidkline-ms** [comment]
Tests succeeded in validation. 

I would like to echo @wiwei's comment re: merging this into mrtk_development instead of the stabilization branch.

**Comment by Troy-Ferrell** [comment]
@wiwei and @davidkline-ms , sure that works. Either or works. I'll switch to MRTK_development

**Comment by julenka** [comment]
Hey @Troy-Farrell something seems fishy with the conflicts here and the size of the code delta (52 files changed, many not related to data provider tests) -- can you merge / update with latest?

**Comment by Troy-Ferrell** [comment]
@julenka, it’s because the PR was updated to target mrtk_development but the branch hasn’t been updated to correctly commit over that branch. I just have to move the changes over.

**Comment by keveleigh** [comment]
#5623 has been merged!

**Comment by Troy-Ferrell** [comment]
Closing in favor of #5659

**Pull request closed without merging**
