### PR TITLE
Reduce count and improve assembly naming consistency

### PR DESCRIPTION
**Pull request by davidkline-ms**
This change combines core and some editor assemblies to reduce the number of dlls generated and visual studio projects in the solution.

It also moves most editor related code into a single Editor folder.

Lastly, it updates all assembly names to follow the pattern of Micosoft.MixedReality.Toolkit.<name> and renames the asmdef files to match.

Gets as close as is currently possible (without significant code changes) to #4453.

Testing performed:
- Solvers scene
    - Verify input, teleport, diagnostics and boundary systems function as expected
- Edit mode tests pass

### CODE REVIEW

**Comment by wiwei** [comment]
I'll probably hold off reviewing this until the build comes back green (looks like it fails pretty early on in CI).

I do have some general questions however about this change, since it looks like there was some discussion on the related issue, but it seems like we didn't fully land on all of open issues before sending out this PR:

1) This optimizes heavily for consumers of the MRTK who aren't making day to day changes to the MRTK, which is great for consumers. For folks who are working on the MRTK itself, it means that build times for making changes to things like inspectors (which is super common) will now go up. There are a few possibilities that could exist here:

- Consumer focus is so high that from an MRTK contributor perspective, any amount of pain we have is okay because we should be willing to take really large build times (i.e. 30 minutes) if it marginally increases consumer benefit it will be worth it regardless of the cost. This example is explicitly chosen to be arbitrarily high to emphasize that this path involves no cost/benefit weighing.
- There is some tradeoff where we can weigh benefit to consumers (i.e. reduced assembly count) to cost to contributors (i.e. 30 seconds additional build time per change)

It feels like our philosophy right now is #1, even though it feels like we should have done the due diligence to measure the impact of this change (which AFAICT wasn't done). This could be as informal as say, having one repo with changes one without, making some changes to some editor code and then using a stopwatch to time difference.

2) It seems like this only solves a subset of the problems - i.e. how many assemblies still remain after this? It feels like there may be a more general solution that involves CI-pipeline work that would post-process the asmdefs to collapse them into a smaller count (similar to how UnityEngine.dll has its own set of smaller DLLs but in the end you link against UnityEngine.dll)

I just want us to be very explicit about the degree to which we're solving the problem and the due diligence being done here (and to write it down)

**Comment by davidkline-ms** [comment]
> l probably hold off reviewing this until the build comes back green (looks like it fails pretty early on in CI).

Should be fixed. Thanks to @keveleigh for spotting the breaking change.

> I just want us to be very explicit about the degree to which we're solving the problem and the due diligence being done here (and to write it down).

Agreed. 

The goal of this PR is to optimize for the largest set of customers (i.e. non-contributors). Based on what was discovered working on this, it was not possible to remove as many assemblies as was originally desired (were able to merge three editor assemblies down to one).

The largest benefit of this change is the improved consistency in assembly naming (some were not following the pattern of "Microsoft.MixedReality.Toolkit.<name>".

**Comment by davidkline-ms** [comment]
Not encountering errors building the .net backend version on my local PC. retrying the CI

**Comment by davidkline-ms** [comment]
closing to revisit in the next major release as the code layout and dependencies need to be thoroughly reviewed analyzed

**Pull request closed without merging**
