### PR TITLE
Allow a SingleInstance to be null without spamming the debug console.

### LINKED ISSUE #1031: Instance isn't found if class is on a disabled GameObject.
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/62491815d88337f8cf98060c1d45e6d19554eae1/Assets/HoloToolkit/Utilities/Scripts/SingleInstance.cs#L21
If the derived class is attached to an object that starts out as disabled, its Instance won't be found because the method used here doesn't find disabled objects. changing to use `Resources.FindObjectsOfTypeAll<T>();` resolves the issue.

### PR DESCRIPTION
**Pull request by timGerken**
Fixes #1031

### CODE REVIEW

**Comment by timGerken** [comment]
@StephenHodgson Not sure I know how to change the target of this PR.
Also, inadvertently (again, sigh) added another change to my repo which has now added itself to this PR...

**Comment by StephenHodgson** [comment]
@timGerken, probably will need to rebase your branch, or pull the master and make the changes and submit a new PR.

**Comment by keveleigh** [comment]
The way I did it earlier was to create a new branch from master with a different name, cherry-pick these commits in, force create a new branch (git branch -f) from that with the same name as this one so it overwrites, then force push it to GitHub. Then, come here and change the compare base to master. There may be a better way, but it worked!

**Comment by keveleigh** [comment]
Oh actually, that won't work as well here, since this is coming out of your fork's dev branch instead of a separate feature branch.

**Comment by StephenHodgson** [comment]
Making a new branch off of master and just copying and pasting your changes might be easiest.

**Comment by timGerken** [comment]
OK. I'll abandon this PR and create two new ones off of master.

**Pull request closed without merging**
