### PR TITLE
Bugfix/gltf flat shading

### PR DESCRIPTION
**Pull request by FreakTheMighty**
## Overview
Currently, when glTF's are loaded on device they do not receive directional lighting. This pull request may not fix the underlying issue, but I figured I'd offer it anyways, as we haven't had any luck finding the root cause of the problem.

Currently, when constructing a glTF material `new Material` is used. This pull request replaces it with `Resource.Load`. This refers to a `StandardglTFMaterial`. If we were to support another material type, such as an unlit extension, we would add a new material template to the resource directory.

## Changes
- Fixes: #6685

## Verification
* Build and run `Gltf-Loading-Demo` on device
* Note that the avocado now receives directional lighting

### CODE REVIEW

**Comment by keveleigh** [comment]
Yep, I've been meaning to submit a review here, and my proposal was going to be your option C:

>Option C) Somewhere within one of the MRTK Profiles we have a "commonly" referenced assets section which has a handful of asset property references of any assets we might what to dynamically load. (Such as a material with directional lighting enabled.) That way any project using this MRTK Profile will automatically pull in the required assets at build time.

I don't think we want to add a `Resources` folder in MRTK itself, to leave that decision up to developers since there's a potential size cost there when packaging the app.

I wonder if, maybe in addition to the common assets, we want to add a "glTF profile" with specific options to load the material. That way we only create the default material at runtime if one isn't provided, but otherwise we use the specifically configured material from the profile.

**Comment by Cameron-Micka** [comment]
> I wonder if, maybe in addition to the common assets, we want to add a "glTF profile" with specific options to load the material. That way we only create the default material at runtime if one isn't provided, but otherwise we use the specifically configured material from the profile.

Ah, I like that idea! Then it's blatantly configurable in case developers have a specific material and/or shader they want to use for GLTF loading.

**Comment by FreakTheMighty** [comment]
@keveleigh @Cameron-Micka are you suggesting that simply having a Material with directional lights enabled in Resources should be enough to fix this issue? So far that hasn't been my experience. For example, I have tests with a material, directional light turned on, applied to to a cube that is in the scene at build time.

>That way we only create the default material at runtime if one isn't provided, but otherwise we use the specifically configured material from the profile.

I have yet to find a way to create the material at runtime and have directional lighting work.

**Comment by Cameron-Micka** [comment]
Hi @FreakTheMighty, we're suggesting that we remove the resources folder all together and instead have a material reference living somewhere within one of the MRTK profiles. For the sake of simplicity here is a contrived example: 
```
private static async Task<Material> CreateMRTKShaderMaterial(GltfObject gltfObject, GltfMaterial gltfMaterial, int materialId)
{
    // Pretend this is MixedRealityToolkit.Instance.ActiveProfile..."Common Assets"...glTFMaterialDefault;
    var defaultMaterial = GameObject.FindObjectOfType<MaterialContainer>().glTFMaterialDefault;

    var material = new Material(defaultMaterial)
    {
        name = string.IsNullOrEmpty(gltfMaterial.name) ? $"glTF Material {materialId}" : gltfMaterial.name
    };

    // etc.
```

To test this works "MaterialContainer" is simply this (the real solution would live somewhere within a serialized MRTK profile): 
```
using UnityEngine;

public class MaterialContainer : MonoBehaviour
{
    public Material glTFMaterialDefault;
}
```
Looking at the rest of the CreateMRTKShaderMaterial method I see there is a lot of Enable/Disable keywords occurring which may not work in built Unity apps. We should also switch these over to: 

```
MixedRealityToolkit.Instance.ActiveProfile..."Common Assets"...glTFMaterialMask;
MixedRealityToolkit.Instance.ActiveProfile..."Common Assets"...glTFMaterialBlend;
MixedRealityToolkit.Instance.ActiveProfile..."Common Assets"...glTFMaterialEmission;
etc.
```

I'll open a separate issue for this!

**Comment by FreakTheMighty** [comment]
Awesome @Cameron-Micka , thank you for the code sample, that made it more clear to me. I'm gonna close this pull request then, seems like there's a cleaner more robust solution.

**Comment by FreakTheMighty** [comment]
@Cameron-Micka did you ever get around to creating a ticket for the gltf materials?  It looks like #7582 may solve the underlying problem as well, but might be a more involved fix.

**Comment by Cameron-Micka** [comment]
Thank you @FreakTheMighty for bringing this up again. I remember some conversations around adding "core assets" to the profile system. @wiwei or @keveleigh, do you know if this was already completed? If not, we should open up an explicit task as well as do #7582.

**Comment by keveleigh** [comment]
Not completed yet unfortunately. I'll get it tracked for 2.5!

**Comment by Cameron-Micka** [comment]
Awesome, thank you!

**Pull request closed without merging**
