### PR TITLE
Fixes two omissions in the ExtensionServiceCreator

### PR DESCRIPTION
**Pull request by LocalJoost**
## Overview
1. ExtensionServiceCreator ignores namespace supplied by user, always takes default instead
2. ExtensionServiceCreator creates inspector even when "Generate Inspector" is unselected

## Changes
1. ExtensionServiceCreator now uses NameSpace in stead of DefaultExtensionNamespace while creating the files. This also required adaption of the template files as those now have a missing "using" on top now they are no long in Microsoft.MixedReality.Toolkit.Extensions;
2. Added simple "if(UsesInspector)" around creation of inspector. This was read from the UI and clearly intended to use for this, but was not checked

### CODE REVIEW

**Comment by wiwei** [comment]
@Railboy, can you take a look as well?

**Comment by wiwei** [comment]
Thanks for fixing this! Change lgtm, would like to get @Railboy's eyes because he wrote this.

**Comment by davidkline-ms** [comment]
Changed base to stabilization branch so that this makes it into the next release.

**Comment by LocalJoost** [comment]
Glad to be of service. I had run into this limitation for quite some number of times, and I am glad I could lend a helping hand

**Pull request merged**
