### PR TITLE
Fixed a few issues with speech input handler

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
- Made sure Windows Speech Input's event data was raised by the gaze's input source, as Focused Object is determined by the event's input source.
- Updated `SpeechInputHandler` to only check if speech commands profile was null instead of if the speech commands were enabled.
- Added an error helpbox to the speech input handler if a previously registered keyword is no longer in the speech command profile

Changes
---
- Fixes: #2834

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I'm not really liking the way I fixed the speech commands by replacing the InputSystem with the gaze directly like that.

In out generic input source creation we set the input source's pointer to be the gaze pointer if no pointers are assigned.

In the Mixed Reality Input Manager's event handler method, we should be getting the focused object based on the event data, which should give us whatever object the gaze pointer is currently focused on, but it's not.

Going to look into and test that first.

**Comment by StephenHodgson** [comment]
I removed the changes to the WindowsSpeechInputDeviceManager and will address the focus bug in a separate PR

**Comment by StephenHodgson** [comment]
@alcooper91 can you test this and make sure it fixes the Null Ref you were running into please?

**Comment by alcooper91** [comment]
I won’t be able to check until Monday but I’ll let you know then.

**Comment by StephenHodgson** [comment]
No worries :) much appreciated.

**Comment by StephenHodgson** [comment]
image

**Comment by StephenHodgson** [comment]
Thanks @keveleigh!

**Pull request merged**
