### PR TITLE
Input handler refactor

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Cleans up unnecessary Spatial Input Handler with a single interface with generic implementations.

Changes
---
- Fixes: #3075

### CODE REVIEW

**Comment by StephenHodgson** [comment]
`OnSourcePoseChanged` is not one of the events that are changed with this PR.

Only events handled by `IMixedRealitySpatialInputHandler` such as:
- `OnPoseInputChanged`
- `OnRotationChanged`
- `OnPositionChanged`

I did add references to the obsolete message with the appropriate new usages.

I did consider updating the source events as well, but thought it was better that these were rather explicit.

**Comment by davidkline-ms** [comment]
Those were what I meant. Thanks for the clarification @StephenHodgson.

**Comment by davidkline-ms** [comment]
> I did add references to the obsolete message with the appropriate new usages.

That's a good start. At some point, though, those messages / obsolete methods will no longer exist. We still need good how -to docs :)

**Comment by StephenHodgson** [comment]
I thought we agreed that obsolete things wouldn't be removed until 2019 tech branch?

**Pull request merged**
