### PR TITLE
Fixes  failing to find msbuild when VS 2015 not installed and using 14393 SDK

### LINKED ISSUE #1146: MSBuild.exe is missing or invalid (path=). Note that the default version is 14.0
When trying to build an appx I am returned the following:
Unable to find a valid path to Visual Studio Instance!
UnityEngine.Debug:LogError(Object)

MSBuild.exe is missing or invalid (path=). Note that the default version is 14.0
UnityEngine.Debug:LogError(Object)

I've tried updating everything.  Unity. (2017.1.2.f1) The Windows SDK.  Visual Studio with all of the additional components listed.  No luck.

Any suggestions on how to correct this issue?

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixes #1146 Wouldn't build for SDKs that use ms build version 14 and VS 2015 was not installed.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@reillydonovan, @brean let me know if this fixes it for you guys.

**Comment by jessemcculloch** [comment]
@brean @reillydonovan - Can you two test and see if this resolves the issues, so we can merge the fix?

Thanks!

**Comment by reillydonovan** [comment]
I can confirm that this works when publishing via the MRT build window to APPX and deployed to the hololens via the device manager.  

Tested using:

Fall Creators Update 
Unity 2017.2.0f3
VS 2017 v 15.4.0 with all recommended supported dependencies
Windows 10 SDK 10.0.16299

**Comment by StephenHodgson** [comment]
The fix is for publishing to an older SDK without vs 2015.

So the real test is building and deploying while targeting the 14393 SDK

**Pull request merged**
