### PR TITLE
Add error logs on destroying event system with dangling listeners

### PR DESCRIPTION
**Pull request by googlan**
## Overview

This change has originally been triggered by #5116 to first of all ease test debugging, when test runtime environment is not clean after running another test.
So, the change should only have been messages in `BaseEventSystem`. However, adding these messages highlighted few fundamental issues:
* Mrtk had incorrect order of deinitialization for core systems. They should be disabled and destroyed in a reverse order to how they are initialized. This PR fixes that.
* Unregistering event handlers in unity `OnDestroy` is semantically incorrect: Mrtk tear down happens in the middle of `Update` loop, which Deinitializes and Destroys all global services. When components are then destroyed _in the end_ of the `Update` loop, they can't rely on valid state of services (e.g. Input System). Ideally we would like global listeners to go away in `OnDisable`. However, this would require to move their initialization to `OnEnable`, which is much trickier to do. Solved this by modifying `IMixedRealityCursor` interface. I don't like it, but it solves an issue.

### CODE REVIEW

**Comment by wiwei** [comment]
@keveleigh to take a peek here as well.

The change to IMixedRealityCursor feels not great to me too, though the alternative (of having a separate interface just for the shutdown/destroy method) really feels like overkill. It feels like the lesser of two evils.

Technically this is a breaking change (though because we provide the base implementation as well in BaseCursor I think that it should be okay

**Comment by googlan** [comment]
@wiwei Agree about everything said regarding `IMixedRealityCursor`. Just need to choose the lesser evil.

**Comment by googlan** [comment]
Apparently when unloading a scene Unity disables/destroys game objects in a scene in an arbitrary order. `HandInteractionExamples` scene generates different sequence of error messages for every "play-stop" in the Editor (not tests, just running it from the Editor). 
I'm gonna disable these warnings in `EventSystem.Destroy` by default and enable them in our play mode tests, which use standard TestSetup. They can be enabled for normal debugging if necessary, but I think in most non-test cases they will cause more confusion than benefit.

**Pull request merged**
