### PR TITLE
Fixed MixedRealityCameraEditor not serializing updated values correctly

### LINKED ISSUE #1258: Mixed Reality Camera Manager settings not stored/retained
image
I tried to set near clip to 0.3 and quality to simple. Save scene, close Unity, Start Unity, settings are reverted again. At least in Unity 2017.1.2.f1, which is the recommended Unity version for a HoloLens app

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixed #1258

### CODE REVIEW

**Comment by keveleigh** [comment]
Will this change need to be made for any other Editor scripts?

**Comment by StephenHodgson** [comment]
Idk, shouldn't affect anything else.

**Comment by keveleigh** [comment]
Can this PR also rename the script? Missing an a: MixedRealityCameraMan**a**gerEditor.cs

**Comment by StephenHodgson** [comment]
Can Do!

**Pull request merged**
