### PR TITLE
Fixing remote mapping for IL2CPP support

### LINKED ISSUE #265: IL2CPP support?
Does this package support being compiled with IL2CPP?  I just tried doing that but got a bunch of errors like this:

```
Assets\Plugins\HoloToolkit\SpatialMapping\Scripts\RemoteMapping\MeshSaver.cs(10,24): error CS0234: The type or namespace name 'Tasks' does not exist in the namespace 'System.Threading' (are you missing an assembly reference?)
Assets\Plugins\HoloToolkit\SpatialMapping\Scripts\SpatialProcessing\SurfaceMeshesToPlanes.cs(11,24): error CS0234: The type or namespace name 'Tasks' does not exist in the namespace 'System.Threading' (are you missing an assembly reference?)
Assets\Plugins\HoloToolkit\CrossPlatform\Scripts\Reflection\ReflectionExtensions.cs(90,59): error CS0246: The type or namespace name 'TypeInfo' could not be found (are you missing a using directive or an assembly reference?)
```

### PR DESCRIPTION
**Pull request by keveleigh**
See #265 

This also fixes a bug where spatial mapping file saving didn't properly get data from the remote mapping source.

### CODE REVIEW

**Comment by keveleigh** [comment]
@StephenHodgson Yep, it should! I put it in this branch first, since porting efforts to Windows Mixed Reality are more likely to come from IL2CPP, as opposed to HoloLens apps. It's definitely a fix that needs to go everywhere though.

**Comment by StephenHodgson** [comment]
Good to hear. Please be sure to keep the issue open until it's merged into the master branch.

**Comment by StephenHodgson** [comment]
In fact I wouldn't mind seeing a new PR for this along side this one.

**Comment by keveleigh** [comment]
Will do! I believe GitHub does that by default, auto-closing the issue when the PR actually gets merged into master.

**Comment by StephenHodgson** [comment]
Just have to remove the first line of your initial comment to prevent that.

I'd change it to `See: #265` instead of Fixes.

**Comment by keveleigh** [comment]
I think this is the preferred way to do it, since GitHub [doesn't close the issue](https://help.github.com/articles/closing-issues-using-keywords/) until the PR is merged into the default branch.

Of course, if we're merging a separate PR into master, the contents of this one doesn't really matter haha.

**Comment by StephenHodgson** [comment]
That's what I'm saying. I would like to close the issue with the other PR.

**Comment by keveleigh** [comment]
Merging this into the dev branch would not have closed the issue automatically, but I changed the wording anyway.

image

**Comment by StephenHodgson** [comment]
Ah I see. Thanks for clarifying

**Comment by keveleigh** [comment]
PR into master opened: #965

**Pull request merged**
