### PR TITLE
Ensured Input System is valid before setting cursor on Gaze Provider.

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Added await to start to make sure the input system is initialized before setting cursor.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@wassx

**Comment by wassx** [comment]
Thanks, very neat solution!

**Comment by StephenHodgson** [comment]
@wassx, could you review and approve this, if you agree with the change?

Did it fix your issue?

**Comment by wassx** [comment]
Tested and it works! Thanks

**Comment by wassx** [comment]
Sadly problem still occurs in the GazeTest sample

**Comment by wassx** [comment]
I'm using unity 2018.1.9f2. I retested the Basic GazeTest example from the original issue and there is still the error message (after stopping) and no gaze cursor.

**Comment by StephenHodgson** [comment]
Even tho it may not fix his problem we should still make this change.

**Comment by StephenHodgson** [comment]
Hi @wassx. Sorry I've been so busy lately. I left your issue open and plan to revisit and solve it as soon as I can.

**Comment by wassx** [comment]
@StephenHodgson Thank you! 👍

**Pull request merged**
