### PR TITLE
Improve Hand Mesh Performance

### PR DESCRIPTION
**Pull request by Troy-Ferrell**
## Overview
This PR is part of an upcoming set to address some of the hand mesh tracking performance issues. This particular PR fixes the problem of constant re-allocation and re-assignment of mesh data every frame. With this change, the MRTK hand interaction example scene renders at 60 FPS with one hand mesh shown. Unfortunately, two hand meshes will easily kick it below 60 still.  

To achieve this improvement, there were two primary changes in this PR:
1) Create re-usable vertex/normal buffers in WindowsMixedRealityArticulatedHandDefinition both for the Windows API buffer (i.e HandMeshVertex) and the UnityEngine.Vector3 vertex/normal buffers. These buffer pointers are passed through HandMeshInfo in the OnHandMeshUpdated events. 
**BEFORE** this change, MRTK was allocating 4 arrays of Vector3's every frame. One handmesh is ~453 vertices => 4 * sizeof(vector3) [12 bytes] * 453 => **21.744 MB per frame**

2) Update BaseHandVisualizer to only update the vertices & normals property of the mesh every frame. The triangles/indices and UV properties are only updated if the mesh changes size or if it's the first time the mesh is being set. 

3. More minor but also added conversion extension functions that allow conversion of a System.Numerics.Vector3 to UnityEngine.Vector3 effectively in-place by using pass-by-reference. This was the construction, copy and assignment are avoided since this operation is executed every frame for ~500 vertices & ~500 normals.

Use of Parralel.For concurrency instead of for-iteration loop is about 2.5-2.7x faster. Setting only the vertices/normals property every update (since triangles/uvs remain same) is about 2.8x-3x faster. There is also significant speed improvements for not re-allocating the 21MB of data every frame but this was not measured directly. 

Future Potential PR work:
1) Look at updating MRTK to utilize new Mesh.SetVertexBufferData() and related functions in 2019.3+ to maximize performance
2) Save HandMesh data into file like HandJoints to leverage in editor with InputSimulationService?
3) [MINOR] EnableHandMeshVisualization and HandJoint are both pulled from Profile instead of service?

## Changes
- Fixes: #7170

### CODE REVIEW

**Comment by julenka** [comment]
Out of curiousity and to prove improvement, could you please share some benchmark data here? It would be good to set this as an example. Something like time spend obtaining and rendering mesh data before and after the change.

**Comment by Troy-Ferrell** [comment]
> Out of curiousity and to prove improvement, could you please share some benchmark data here? It would be good to set this as an example. Something like time spend obtaining and rendering mesh data before and after the change.

You mean like overall time before and after change? I did include some data in PR description:
> Use of Parralel.For concurrency instead of for-iteration loop is about 2.5-2.7x faster. Setting only the vertices/normals property every update (since triangles/uvs remain same) is about 2.8x-3x faster. There is also significant speed improvements for not re-allocating the 21MB of data every frame but this was not measured directly.

**Comment by julenka** [comment]
> > Out of curiousity and to prove improvement, could you please share some benchmark data here? It would be good to set this as an example. Something like time spend obtaining and rendering mesh data before and after the change.
> 
> You mean like overall time before and after change? I did include some data in PR description:
> 
> > Use of Parralel.For concurrency instead of for-iteration loop is about 2.5-2.7x faster. Setting only the vertices/normals property every update (since triangles/uvs remain same) is about 2.8x-3x faster. There is also significant speed improvements for not re-allocating the 21MB of data every frame but this was not measured directly.

Ah, thank you! I just missed it. Was looking for pictures for some reason.

**Pull request merged**
