### PR TITLE
Adding Fluent Icon Set Font

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview 
Created MRTK Fluent UI icon set font. Picked about 140 crucial icons [from the open-source Fluent Icon Set](https://github.com/microsoft/fluentui-system-icons) TMP asset size @512x512 texture, about 580KB. (1024x1024 texture's quality is obviously better but the asset size is too big (around 2MB). 512x512 looks good enough for the interaction distance.)
- Added MRTK_FluentIconSet SDF.asset (MRTK Standard Assets/Icons)
- Added MRTK_FluentIconSet.ttf font file (MRTK Standard Assets/Icons)
- Added MRTK_FluentIconSet Font Icon Set config file (MRTK Standard Assets/Icons)
- Updated FontIconExample scene
- Updated non-canvas Button prefabs to use font icon. **Sprite icon is still available (hidden).**
- Updated canvas button prefab **Sprite icon is still available (hidden).**
- **Removed holomdl2 SDF.asset file (~8MB)**
- Removed unnecessary sprite icon

 
2022-05-25 17_25_37-MRTK3_MRDevDays_DataBinding_Theming pptx - PowerPoint

## Non-canvas button prefab update

2022-05-25 19_14_29-MRTKDevTemplate - UITearSheet - Universal Windows Platform - Unity 2020 3 30f1 P

2022-05-25 19_41_56-MRTKDevTemplate - UITearSheet - Universal Windows Platform - Unity 2020 3 30f1 P

## Canvas button prefab update

2022-06-24 14_23_26-MRTKDevTemplate - CanvasUITearsheet - PC, Mac   Linux Standalone - Unity 2020 3

## Quality comparison - Sprite vs Icon Font
2022-06-24 14_28_29-Greenshot

2022-06-25 15_19_21-MRTKDevTemplate - CanvasUITearsheet - PC, Mac   Linux Standalone - Unity 2020 3

### CODE REVIEW

**Comment by Zee2** [comment]
Some prefabs seem to have their icons broken.

image

**Review by Zee2 — CHANGES_REQUESTED** [review]
Some prefabs seem to have their icons broken.

image

(These are non-canvas ones, featured in HandInteractionExamples)

Also, the FontIconSelector doesn't register changes with the Undo System correctly. When you select a new icon, you can't Ctrl-Z it.

**Comment by Zee2** [comment]
@cre8ivepark , I submitted a fix for the FontIconSelector problems in a separate PR: #10710

**Comment by Zee2** [comment]
The StateVisualizer setups on all of the UX controls haven't been modified to point at the new font icons for things like dimming during disabled state(s), toggle icons, etc.

image

**Comment by cre8ivepark** [comment]
> Some prefabs seem to have their icons broken.
> 
> image
> 
> (These are non-canvas ones, featured in HandInteractionExamples)
> 
> Also, the FontIconSelector doesn't register changes with the Undo System correctly. When you select a new icon, you can't Ctrl-Z it.

Updated toggle prefabs which has switch, check, radio, etc to hide the icons:

2022-07-07 14_59_45-Greenshot image editor

**Comment by cre8ivepark** [comment]
> The StateVisualizer setups on all of the UX controls haven't been modified to point at the new font icons for things like dimming during disabled state(s), toggle icons, etc.
> 
> image

Added UIButtonFontIcon to the Graphics Tint list under Disabled state along with the existing Sprite icon.
Are there any additional states that we need to add?
2022-07-07 14_55_19-MRTKDevTemplate - UITearSheet - PC, Mac   Linux Standalone - Unity 2020 3 36f1 g

**Comment by Zee2** [comment]
image

This will need to get changed at some point (the checkboxes/etc don't use the proper font icons, but that'll probably require some stateviz changes)

**Comment by Zee2** [comment]
image

@cre8ivepark FontIconExample seems to be broken.

**Comment by cre8ivepark** [comment]
> image
> 
> image
> 
> @cre8ivepark FontIconExample seems to be broken.

Looks like I forgot to bring the update for the example scene from the ADO repo. Update applied!

2022-07-09 13_30_29-MRTKDevTemplate - FontIconExample - PC, Mac   Linux Standalone - Unity 2020 3 36

**Comment by cre8ivepark** [comment]
Applied random icons in the tear sheet scenes to show examples of using font icons:

2022-07-09 13_48_45-MRTKDevTemplate - UITearSheet - PC, Mac   Linux Standalone - Unity 2020 3 36f1 g
2022-07-09 13_43_35-MRTKDevTemplate - CanvasUITearsheet - PC, Mac   Linux Standalone - Unity 2020 3

**Review by Zee2 — APPROVED** [review]

**Pull request merged**
