### PR TITLE
adding example scene 3 -- for VR

### PR DESCRIPTION
**Pull request by beaufolsom**
Overview
---
I've added a scene called **"Playground"**
 
mr_playground-scene_01
mr_playground-scene_02

**Features**
- Multiple customize-able surfaces to use for testing interactions -- with collisions for physics objects.
- Cloth simulation banners -- Needs 2 sided shader
- Light, fast, and human scale -- it runs under 10ms on Ultra quality settings. 
- Everything in the scene is named to be human readable and very clear to new users.
- Minimal textures. 

mr_playground-hierachy_01

**Experiments**
- I added in a "ghost" shadow, to help anchor the VR user in the world. --needs improvement--
- The **Target** models are built to allow each ring to disappear when struck. -- needs some programmer help.
- The sun can be moved and the lighting in the space will update in real-time if needed.
- There are physics balls in the scene (disables) that I used to test collisions. They can be turned on to view physics in action in the scene.

Changes
---

1. Since we are using the **Standard Shader**, I switched the lighting in **Player Settings** from **Gamma** --> **Linear** -- (Linear lighting is required by the Standard Shader for PBR to work.)
mr_playground-playersettings_01

2. I changed the Quality settings from **Very Low** --> **Ultra**, for better lighting, and MSAA support in VR.
mr_playground-qualitysettings_01

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Just a note, the quality settings are probably going to be overridden by the confirmation profile based on the platform selected. For example, if building for HoloLens, the graphic settings will switch to lowest, and VR should usually default to the highest.

**Comment by StephenHodgson** [comment]
Over all this looks very cool. Detailed review coming soon.

**Comment by SimonDarksideJ** [comment]
Looks awesome, although it needs to clearly state the objectives of the scene (do we even have a boss and arrow mechanic yet?)

Can't review properly till I get back to apc, but the main thing is change is the sky box to something more like what is in the first example (resembling the WMR start scene sky box)

Keep up the great work

**Comment by beaufolsom** [comment]
@SimonDarksideJ -- Thanks! The targets are not for Bow & Arrow, but for tossing and throw mechanics _<-- requested by the Experience Design team at Microsoft_. As for the Sky -- I'm not familiar with the WMR Start scene sky... are you talking about the "Cliffhouse"?

**Comment by SimonDarksideJ** [comment]
The empty scene you see when wmr starts, before the cliff house.
I made an attempt in the example one scene here.

**Comment by beaufolsom** [comment]
@SimonDarksideJ -- Is there a project reason the sky should be changed? If you are referring to the dark grey _tron-like_ sky during calibration and start-up, that would be a mistake both artistically and technically. The mood and lighting of the scene relies heavily on the sky ( and since the scene is **PBR**, the sky's _**brightness**_ factors in to the overall lighting contribution). We could get away with a more overcast white, but we would loose all the bounced blue that helps sell the simple scene. I stuck with the default sky for flexibility, light contribution, and file-size reasons... proper (.exr) files are HUGE. IMO, it's an easy change for an end user to make (swap the sky) -- But if we are shipping this for download, it's best to keep it light.

**Comment by davidkline-ms** [comment]
Nice work, Beau!

**Pull request merged**
