### PR TITLE
Adding the scene reorientation functionality

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
Based on the feedback, adding re-center functionality to MRTK Examples Hub.

- Added ReorientContent() to MixedRealitySceneContent.cs 
- Updated ToggleFeaturesPanelExamplesHubStore.prefab for Examples Hub to include reorient functionality.
   - Re-Center button added
   - ReorientContent.cs added which calls MixedRealitySceneContent.ReorientContent() 

## How to test
Run MRTKExamplesHub scene. Use the 'Re-Center' button on the floating menu to test reorientation.

2021-07-20 20_54_00-Unity 2018 4 35f1 -  PREVIEW PACKAGES IN USE  - MRTKExamplesHub unity - MixedRea

## Changes
- Fixes: #7034

### CODE REVIEW

**Comment by cre8ivepark** [comment]
Need help: Currently, it does not give content proper z offset from the user since it uses camera position.

**Comment by cre8ivepark** [comment]
@RogPodge 
Currently, when the Re-Center button is pressed, it becomes like this (too close to the user)
2021-08-12 12_46_55-Window

Wanted to maintain proper z-position as well. Something like this:
2021-08-12 12_47_03-Window

**Comment by cre8ivepark** [comment]
It works well! I just tested with HandInteractionExample scene with Align with Head Pose option and it works well even after Hub Menu was reoriented. Thanks @RogPodge !

**Comment by cre8ivepark** [comment]
# WORK-IN-PROGRESS 
Updating example scenes to have proper MixedRealitySceneContent object with (0,0,0) position and set Alignment Type 'Align with head pose'

**Comment by cre8ivepark** [comment]
@RogPodge Somehow, reorientation does not work in the device. Not sure if there is any non-device specific code for reorientation?

**Comment by davidkline-ms** [comment]
@RogPodge, can you sync with @cre8ivepark and see if you can push it over the finish line? Thx!

**Comment by RogPodge** [comment]
FInally vetted it all and it looks good, will merge as soon as it passes CI

**Review by RogPodge — APPROVED** [review]

**Pull request merged**
