### PR TITLE
Consolidated setup prompts into one, and added VR setup

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Turns on VR support and consolidated optional first install prompts into one.

image

Changes
---
- Fixes: #2975
- Fixes: #2860

### CODE REVIEW

**Comment by davidkline-ms** [comment]
Curious on this one... In HTK, we had a similar dialog that defaulted checkboxes to make each recommended change and allowed developers to opt out of individual settings.

Why not the same approach for vNext?

While each of these are good settings, it is really handy to be able to opt out of one or two without needing to find the underlying option in the Unity UI.

**Comment by SimonDarksideJ** [comment]
The approach in Mrtk is slightly different to htk, in that the scriptable object config replaces most of what was configured on the htk screens.

The config settings here are only those that prevent the default operation of the MRTK (. Net/IL2CPP/VR on etc) but things that are optional.

I feel that this simple prompt which appears before Unity even loads fully, ensures that 90% of consumers starting a new project will benefit from a hassle free startup.
The other advanced users know these options and if they choose not to take them can sort it out later. 
Plus most of these settings are on one screen, the player settings. 

Aim is to ensure new users have the simplest setup experience and are welcomed in to the project and removing and manual setup or hinderence.

This is essential for the Beta, where most users will simply be trialling the experience and we can gather their feed back to improve this if need be for the Beta after that

**Comment by keveleigh** [comment]
I'm not sure these are required for the default operation of the MRTK. Visible meta files and force text serialization were requirements in the legacy Toolkit so that contributions back were formatted correctly, but use of the Toolkit doesn't need them.

Enabling XR makes sense, and changing to IL2CPP is nice to have, but it'd be great to be able to pick which one(s) I want instead of being given all at once.

**Comment by SimonDarksideJ** [comment]
Not possible to have choices on startup, else I works agree and putting them later when you sold be choosing before you begin just handicaps as "something else you need to do"

The Meta files options are just good practice and highly recommended for git sourced projects (as can be found in every tutorial for using unity with source control) 

Advanced users can simply select later and it won't prompt ever again and they can do it themselves. 

But for the majority of user, we want add smooth a process to adoption as possible with no barriers

In the beta, users can request more or less from this setuo, but at least then we will have usage feedback. 

Our aim for the first beta should require the fewest actions to hit play and see your connect in the headset as possible. This option reduces it to 3 clicks for a new project with no editor windows

**Comment by SimonDarksideJ** [comment]
As an FYI, this is the current "new user" setup experience we are trying to improve.
https://drive.google.com/file/d/1OMlFHdbTeiMns5KYpydKGv446Ua2gwBh/view?usp=sharing

Ultimately we NEED to reduce this to a single message / box click, to get users started quickly

**Comment by StephenHodgson** [comment]
Could you share the YouTube link directly?

**Comment by StephenHodgson** [comment]
I can't build the dll until https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2988 is in.

I'd like to do that in a separate PR

**Comment by StephenHodgson** [comment]
Just to reiterate, all I've done is consolidated the _optional_ editor settings to a simple dialogue.

These have always been part of mrtk/htk and *do not* relate to the "configuration" screens from HTK.

We didn't want to inundate the user with 5 popups right after import.

**Pull request merged**
