### PR TITLE
[Shell Parity] [Button] Highlight Plate Shell Behavior

### PR DESCRIPTION
**Pull request by Cameron-Micka**
## Overview
This change animates in/out the HoloLens 2 pressable button's highlight plate based in button focus to closer match the shell design. This change also reduces overdraw performance issues on the button.

Hightlight
(Note, gif compression doesn't represent on device visuals.)

This change also introduces an new iridescent backplate texture to closer match the shell.

Part of #4200 [MRTK Shell Parity] UX Controls Parity with HoloLens 2 Shell

## Changes
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4977

## Verification
The best scene to test these changes in would be the HandInteractionExamples scene.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by Cameron-Micka** [comment]
Thank you @cre8ivepark!

**Comment by keveleigh** [comment]
Merging with three approvals and all checks passing.

**Pull request merged**
