### PR TITLE
Add support for OpenXR controller model

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

Adds support for the controller render models via OpenXR.

Also works in-editor!

image

## Changes
- Fixes: #9699

### CODE REVIEW

**Review by MaxWang-MS — COMMENTED** [review]
The TryRenderControllerModel and TryRenderControllerModelWithModelProvider functions look very similar if not identical in the two controller scripts. Is there any chance we can reuse the code?

**Comment by keveleigh** [comment]
>Is there any chance we can reuse the code?

We can! I started going down this path a couple days ago, refactoring out a `MixedRealityControllerModelCreator` that's responsible for more fully setting up the controller (more than just providing the model). This would also de-dupe code in a few other controllers, like https://github.com/microsoft/MixedRealityToolkit-Unity/blob/4bc46b31fd90bc9282096891dbf1ac53b956d8bf/Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKMotionController.cs#L155-L203.

I ended up dropping that thread after i realized i couldn't refactor out as much as I had wanted, due to the original implementation using inheritance to define `TryAddControllerModelToSceneHierarchy`. I'll revive the work though and see what I can do!

**Comment by RogPodge** [comment]
Looks good to me barring the same comments on potentially deduping code that Max had.

**Comment by keveleigh** [comment]
@MaxWang-MS @RogPodge I refactored out `MixedRealityControllerModelHelpers` to de-dupe some of that code!

**Review by RogPodge — APPROVED** [review]

**Review by MaxWang-MS — APPROVED** [review]

**Pull request merged**
