### PR TITLE
Adding in interaction starter package and adaptive performance tools

### PR DESCRIPTION
**Pull request by keluecke**
AdaptivePerformance replaces FPSViewportQualityBundle.

This tool is meant to help apps achieve frame rate on different hardware by adapting quality settings, as well as hint at a good starting level on first run.  See usage instructions here:
https://developer.microsoft.com/en-us/windows/mixed-reality/Performance_recommendations_for_immersive_headset_apps

### CODE REVIEW

**Comment by StephenHodgson** [comment]
My apologies. It seems it's just replacing what's already there.

**Comment by StephenHodgson** [comment]
So what's the reasoning for including this as an asset package instead of the source?  

How do we know what contents were changed, removed, or added?

**Comment by DDReaper** [comment]
Agreed, the source should be included in "Examples" or "Tests".  Then the assets added in the release as (optional) extras.
Also, they will need documentation to describe what they bring and how to use them.

**Comment by StephenHodgson** [comment]
@keluecke we've merged the dev branch back into master. Please reopen this PR after re-targeting it and adding the source.  Thanks.

**Pull request closed without merging**
