### PR TITLE
Fixed null reference when setting icon in icon generator with bad dimensions.

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixed null reference when setting icon in icon generator with bad dimensions.

### CODE REVIEW

**Comment by keveleigh** [comment]
Huh, for my own reference, how did moving that line around fix this issue? It looks like the order of a dialog box and setting newIcon was reversed, so I can't wrap my head around what that changes haha.

**Comment by StephenHodgson** [comment]
If the texture was null and we set the newIcon we get null reference exceptions on in the dialogue popup.

**Comment by StephenHodgson** [comment]
So we show the popup, then reset the newIcon.

**Comment by keveleigh** [comment]
@StephenHodgson Aha! I knew I was missing something obvious. Thanks!

**Comment by keveleigh** [comment]
@StephenHodgson Aha! I knew I was missing something obvious. Thanks!

**Pull request merged**
