### PR TITLE
Cherrypick/6048

### PR DESCRIPTION
**Pull request by julenka**
## Overview
Cherry picks #6048 into stabilization.

### CODE REVIEW

**Comment by davidkline-ms** [comment]
will merge once validation completes

**Comment by davidkline-ms** [comment]
Hitting the following error building for standalone in validation, Will investigate: **Assets\MixedRealityToolkit.Tests\PlayModeTests\PressableButtonTests.cs(615,29): error CS0111: Type 'PressableButtonTests' already defines a member called 'AreApproximatelyEqual' with the same parameter types**

**Comment by julenka** [comment]
I think I forgot to push a change, since it worked for me locally. Will check when I get in.

**Comment by davidkline-ms** [comment]
> I think I forgot to push a change, since it worked for me locally. Will check when I get in.

I'm also trying it locally

**Pull request merged**
