### PR TITLE
Fix spatial awareness mesh w.r.t. camera scale

### PR DESCRIPTION
**Pull request by fast-slow-still**
## Overview

Modify the parenting of SpatialAwareness nodes hanging off the MixedRealityPlayspace to not absorb any scale from the MRPlayspace, and then correct the (de-scaled) mesh positions.

## Changes
- Fixes: #8250.

## Verification
There might be a better way to address this.

Note that this PR only addresses uniform scale in the camera hierarchy. Non-uniform scale is unlikely to be robustly handled, and is specifically [recommended against by Unity](https://docs.unity3d.com/Manual/configuring-project-for-xr.html).
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by wiwei** [comment]
Change looks good - would be interesting if we could add a test case for this (even using the in-editor mesh thingy)

**Comment by wiwei** [comment]
If you're open to writing that in this PR that works, but if you want to get this in to unblock further work elsewhere (i.e. in the WLT area) then we can also push this in first.

**Comment by fast-slow-still** [comment]
Agreed @wiwei on adding the test, but I'm going to be out for a while and would like to get this in before I go. I'll put the test on my to-do for when I get back. Thanks!

**Pull request merged**
