### PR TITLE
Update the Toggle Features Panel prefab to have a working profiler button

### PR DESCRIPTION
**Pull request by wiwei**
A previous change to the visualization toggle scripts had updated instances of it, but missed updating the prefab itself - this was initially revealing itself as references to dead scripts, which was fixed by the input recording PR. 

This change makes it so that the profiler button works again on the prefab.

### CODE REVIEW

**Comment by cre8ivepark** [comment]
@wiwei shell we remove the toggle profiler button?
2019-05-21 12_04_05-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof

**Comment by wiwei** [comment]
> @wiwei shell we remove the toggle profiler button?
> 2019-05-21 12_04_05-Unity 2018 4 0f1 Personal - HandInteractionExamples unity - MRTK-Public-Microsof

**Comment by julenka** [comment]
@wiwei I added the script that David had deleted as part of #5018. But, I made a mistake -- I had only modified the ToggleFeaturesPanel in the HandInteractionExamples scene, not the prefab. Can you update this PR to include the new script, but in the prefab? Just look at how I did this in the HandInteractionExamples scene.

The change makes it so that the toggle profiler button works again :-)

**Comment by wiwei** [comment]
@julenka, sorry for the delay - I removed the VisualProfilerControl reference on the instance in handinteractionexamples, and added it to the prefab itself.

All I did was remove + add that script (and hit save)

**Comment by wiwei** [comment]
Ah wait, hold on a sec...

**Comment by wiwei** [comment]
Okay, it's done!

**Pull request merged**
