### PR TITLE
State sharing system

### PR DESCRIPTION
**Pull request by Railboy**
State Sharing System (and related sub-systems)
---

Opening this PR so we can evaluate and discuss these systems as a whole. Once we've settled on which systems to incorporate I will close this PR and open a smaller PR for each system.

Descriptions of SessionManager, UserManager / DevicePool and AnchorSynchronizer / UserAlignment will be expanded as discussion continues. Example scenes will be created once MRTK-related refactoring is finished.

StateArray
---
The backbone of app state sharing. Essentially a dictionary of structs. Changes made to this dictionary on the server are stored locally until `Flush` is called, at which point the new states propagate to all clients. Changes made on the client are stored locally until they are replaced by a value from the server. 
```
public interface IStateArray<T> : IStateArrayBase, IEnumerable<T> where T : struct, IItemState<T>
{
    T this[sbyte key] { get; set; }
    void Flush();
}
```

State structs must implement the IItemState interface:
```
public interface IItemState<T>
{
    sbyte Key { get; }
    sbyte Filter { get; }
    bool IsDifferent(T from);
    T Merge(T clientValue, T serverValue);
}
```

`Key` is used to assign and retrieve the state. (We found that keeping the key attached to states vastly simplifies state sharing in general.)

`Filter `is used to identify which session a state belongs to in multi-session sharing apps.

`IsDifferent `is used to determine when a state has changed. This is preferable to a straight value equality comparison for a couple of reasons:
- Value-type comparisons can generate garbage.
- States often have fields or properties which would result in redundant comparisons (eg a Vector3 property which draws from a set of shorts for its value).
- States often have fields or properties that require interpretive comparison (eg time-related values).

`Merge `is used to resolve conflicts between client and server states. If an incoming state from the server is found to be different than a locally stored state on the client, the two states are merged before the client value is over-written.

**Issues**
- Currently hard-coded to use sbytes as keys and filters. This was intended to suggest a maximum number of shared states. This should probably be changed to an unsigned short.
- Currently implemented using SyncListStruct from UNet's HLAPI - this will obviously have to change.
- **Server** concept should be changed to **Authority** to make system more peer-to-peer friendly.
- We need a better system for crunching / serializing item states, especially position / rotation states.

AppState
---
Manager class for user-defined StateArrays. Makes the business of getting / setting / adding states to StateArrays straightforward.

Main interfaces / methods:
```
public interface IAppStateReadOnly
{
    T GetState<T>(sbyte stateKey) where T : struct, IItemState<T>;
    void Flush<T>() where T : struct, IItemState<T>;
    void Flush();
    ...
}

public interface IAppStateReadWrite : IAppStateReadOnly
{
    void AddState<T>(T state) where T : struct, IItemState<T>;
    void SetState<T>(T state) where T : struct, IItemState<T>;
    ...
}
```

`Flush` serves a different purpose on client / server. On client, flush sends all locally stored values to the server via the state pipe. On server, Flush just calls Flush on the targeted StateArray(s).

**State Pipes**
AppState also allows devs to assign input / output pipes to provide synchronization from client to server, or (potentially) between peer-to-peer clients.

```
public interface IStatePipeOutput
{
    Queue<object> StatesReceived { get; }
}

public interface IStatePipeInput
{
    bool Sending { get; }
    void SendStates(IEnumerable<object> states);
}
```
In the current implementation (`AppStatePipe`) the state pipe is a component on the Player object, which UNet automatically spawns with authority.

**Initialization**
By default AppState has no StateArrays. On startup AppState automatically seeks out IAppStateSource components, which provide a list of IItemState types for which StateArrays are needed. (Eg `AppStateUsersSource` which requests StateArrays for UserState and UserSlot.)
```
public interface IAppStateSource : INetworkBehaviour
{
    bool Synchronized { get; set; }
    IEnumerable<Type> StateTypes { get; }

    void GenerateRequiredStates(IAppStateReadWrite appState);
}
```

**Issues**
- Currently implemented using UNet HLAPI. AppStateSource components are required to define public fields with a SyncListStruct, which is gathered using reflection. This will have to change.
- Due to the HLAPI's requirement that SyncListStruct classes be defined within the NetworkBehavior that uses them, the sync lists being used by AppState's StateArrays are defined in IAppStateSource components. Another reason to move away from UNet.
- StatePipe system needs to be reworked to be more peer-to-peer friendly.

StateObjects
---
This system handles a ton of boilerplate for spawning / updating objects associated with a particular item state. Typical use case would be generating and updating Holograms.

Developers create a set of prefabs for each state type requiring an associated in-game object. Each prefab must have a component that inherits from the StateObject base class, which implements the IStateObject interface:
```
public interface IStateObject<T> : IGameObject where t : struct, IItemState<T>
{
    sbyte ItemNum { get; }
    bool IsUserType { get; }
    bool IsLocalUser { get; }

    IAppStateReadOnly AppState { get; }
    IUserView Users { get; }
    IStateView StateView { get; }

    T PreviousState { get; }
    T CurrentState { get; }
}
```
Additional components on this prefab (including the class inheriting from StateObject) can implement the IStateListener interface to receive updates about state changes:
```
public interface IStateListener<T> where T : struct, IItemState<T>
{
    void OnStateInitialize(IStateObject<T> stateObj, T initState);
    void OnStateChange(IStateObject<T> stateObj, T oldState, T newState);
}
```
Lastly, the state object can be used as a conduit for state changes via the ChangeState method:
```
public class HologramStateObject : StateObject<HologramState>, IStateListener<HologramState>

    void OnStateChange(IStateObject<HologramState> stateObj, HologramState oldState, HologramState newState) 
    {
        if (timeToChangePosition)
        {
            newState.Position = transform.position;
            // automatically writes to app state
            ChangeState(newState);
        }
    }
    ...
}
```

**Issues**
- Currently intertwined with SessionManager system. Responsibility for updating session state should be moved to the SessionManager, or to another manager entirely.
- Currently intertwined with User system. This is useful for updating user-related objects, but this could probably be separated as well.

SessionManager
---
Provides a skeletal framework for a structured mixed-reality sharing experience using AppState and StateObjects. Runs set of developer-defined 'stages' in a sequence. Example of a session stage progression might be:
1. JoinGame
2. ChooseRole
3. PlayGame
4. ShowHighScores
(Repeat)

Session stages are stored as prefabs and instantiated at runtime. These prefabs must have a component that implements the abstract class SessionStageBase, which has the following methods:
```
public abstract void OnStageEnter (ITimeSource timeSource, IAppStateReadWrite appState,  IUserView users, IStateView stateView);
public abstract void OnStageExit (ITimeSource timeSource, IAppStateReadWrite appState,  IUserView users, IStateView stateView);      
public abstract IEnumerator TransitionIn (ITimeSource timeSource, IAppStateReadWrite appState,  IUserView users, IStateView stateView);
public abstract IEnumerator RunStage (ITimeSource timeSource, IAppStateReadWrite appState,  IUserView users, IStateView stateView);
public abstract IEnumerator TransitionOut (ITimeSource timeSource, IAppStateReadWrite appState,  IUserView users, IStateView stateView);
```
TransitionIn, RunStage and TransitionOut are enumerators to make starting / stopping / pausing trivial.

The main purpose of a session stage is to monitor / modify the app state in response to user actions. This keeps flow of control for the app as a whole out of the hands of individual StateObjects making it easier to track / control.

Since stages are instantiated as prefabs they can be accompanied by objects which are controlled by the stage script (eg a scoreboard). This provides an alternative to the one-state, one-object approach of StateObjects.

**Issues**
- Should probably be renamed to differentiate from network session.
- No support for scene loading / unloading, which is a must IMO.
- No support for branching experiences.

UserManager / DevicePool
---
System for managing users and devices associated with a user. Uses AppState to manage user slots and user states.

**Issues**
- Lobby system is bare-bones.
- Requires manual redefinition of enum values for UserTypeEnum / UserTeamEnum - would be better if this were templatized.
- Assumes the existence of an AnchorSynchronizer.

AnchorSynchronizer / UserAlignment
---
System for synchronizing locally acquired anchor positions, then using that shared information to align users to the same shared physical space.

### CODE REVIEW

**Comment by davidkline-ms** [comment]
per shiproom, let's create a feature branch for this.

**Comment by StephenHodgson** [comment]
Agreed, also let's target this PR to that new branch

**Comment by StephenHodgson** [comment]
I'd like to do a rundown of some initial comments before we merge it so we can get some initial tasks going

**Comment by Railboy** [comment]
@davidkline-ms Initial commit reverted.

**Comment by StephenHodgson** [comment]
> didn't see your request to target this PR to the new branch until after I created it. I can revert the initial commit, or we can roll with it and just close this PR, your call.

No worries! If it's not too much work, that'd be nice just so we can make a few comments and make tasks then go from there. 

If it's already done, than that's okay too.

**Comment by Railboy** [comment]
@StephenHodgson PR has been retargeted.

First task should probably be an implementation of StateArrays that isn't based on UNet.

**Comment by SimonDarksideJ** [comment]
Please remove all Unity asset files (anything in ProjectSettings) so we can get this merged to the new feature branch.
Also, refresh with current development branch to kee it fresh please @mr0ng  :D

**Comment by SimonDarksideJ** [comment]
Is this PR still Needed @Railboy as it now has conflicts with the latest updates, likely need refreshing with the source branch if it does.

However, the conflicting files should not be changed in my opinion and should be reverted

**Comment by SimonDarksideJ** [comment]
Any update @Railboy ?  Can we get the merge conflicts sorted and push this update to the feature branch?

**Comment by Railboy** [comment]
@SimonDarksideJ These tools have changed quite a bit since this PR was opened. I'm going to close / re-open this PR from a fresh branch since not much discussion has taken place yet.

**Pull request closed without merging**
