### PR TITLE
Fixed GetAsync method in Rest class

### PR DESCRIPTION
**Pull request by Proton-V**
## Changes
- Fixes: #10766

## Overview
Fixed problem with using request in Rest.cs class

## Fixes
- ProcessRequestAsync method in Rest.cs

### CODE REVIEW

**Comment by Proton-V** [comment]
@keveleigh 
Hello. I see this warning from azure. 
I think you can approve these changes and pipeline will accept branch?

**Comment by keveleigh** [comment]
> @keveleigh Hello. I see this warning from azure. I think you can approve these changes and pipeline will accept branch?

I'll pull this down and test it out today! Thanks!

**Comment by Zee2** [comment]
@keveleigh updates on this?

**Review by keveleigh — APPROVED** [review]

**Comment by keveleigh** [comment]
Thanks for this fix! Worked great for me locally.
I pushed one slight change to `BytesToString`, as I was hitting a null ref in cases where the connection wasn't successful. This change allowed subsequent errors to surface for debugging purposes.

**Pull request merged**
