### PR TITLE
Disable Teleport Gesture on Hololens

### PR DESCRIPTION
**Pull request by RogPodge**
## Overview
Disabling the teleport pose on Hololens, due to not having a good way to specify valid teleport surfaces, as well as not having a great use case for teleporting on Hololens yet.

## Changes
- Fixes: #9807

### CODE REVIEW

**Review by davidkline-ms — APPROVED** [review]
looks good. why use IsNull vs != null when checking the camera system?

**Comment by RogPodge** [comment]
> looks good. why use IsNull vs != null when checking the camera system?

Matching the uses of IsNull() when looking at other systems under CoreServices
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/5d07c72ec0d62669bd5cdb7ab8b464831d46019a/Assets/MRTK/Core/Providers/BaseGenericInputSource.cs#L29

**Comment by keveleigh** [comment]
This feels really weird. Didn't we specifically add this for HL2 (in addition to already having it for Quest) because we were getting quite a few requests for it? We should probably make this configurable instead of filtering HL2 always.

**Comment by RogPodge** [comment]
> This feels really weird. Didn't we specifically add this for HL2 (in addition to already having it for Quest) because we were getting quite a few requests for it? We should probably make this configurable instead of filtering HL2 always.

I think though we had this intention, there's no great way of using it as of now, and we've gotten some requests to disable it due to the input getting picked up a bit too easily.

One problem for making it configurable at the moment is that there's not good spot on the configuration profile to disable it at the moment, as putting it on the pointer prefab would make it difficult to use the same prefab when deploying both to Quest and HL2, while adding a new field to the pointer profile would make the it more platform specific than scenario specific.

Maybe we can disable the teleport gesture universally when the Teleport System is disabled? What do folks think about that solution @keveleigh @sloh-ms 
I'm thinking we'll have a better hololens x teleport scenario after we get teleport hotspots working, as that should provide a better guided teleportation experience for AR devices.

**Comment by keveleigh** [comment]
I like the idea of more strongly tying the teleport pointer to the teleport system being enabled or some setting on it. Their relationship is a little bit weirdly bidirectional at the moment (mostly due to originally only being able to register Unity Objects as global listeners, but now we could technically register the teleport system directly and move some logic around).

Then what about a teleport system profile with the ability to set something like transparent / opaque / both flags?

**Comment by RogPodge** [comment]
At that point I feel like we're moving slowly into the territory of having AR/VR be a toggle on the broader experience settings, which I think we opted to not go for.

**Comment by RogPodge** [comment]
@keveleigh it seems we already have several basic QoL guards in check (teleport gesture disabled when the teleport system is disabled, teleport pointer inactive when the IsNearObject flag is on). Given that we already have these safeguards and developers are still stumbling upon this, I think it's better to leave teleport as un-selectable for now, at least until we have a better story for how HL2 users might make good use of the teleportation system.

**Comment by keveleigh** [comment]
Is the spatial mapping not teleport-able? If so, that seems reasonably usable to me.

Regardless, I really don't think we should remove this feature from HL2, especially since it shipped in 2.6 and we called it out in the release notes:

https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-26-release-notes#teleportation-with-the-teleport-gesture-now-supported-on-all-platforms

**Comment by keveleigh** [comment]
I think for the original issue, if someone is building an experience that doesn't support teleportation, the profiles are fully customizable! I'm not a fan of removing a feature from a device for everybody after we've shipped it though :/

**Comment by RogPodge** [comment]
I'm convinced since we've highlighted it, PR out: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9822

**Pull request merged**
