### PR TITLE
Fixed teleport animations/scripts to not reset animator state

### PR DESCRIPTION
**Pull request by RogPodge**
#Overview
Previously the SetVisibility function would set the hand visual object as active/inactive for the teleport cursor. This interfered with the cursor since it's animation state was tied to the hand visual object. This PR changes the SetVisiblity script and the animation so that they no longer conflict with each other.

handteleportfix
## Changes
- Fixes: #8755

> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by RogPodge** [comment]
no visual teleport pointer related regressions when testing on Quest as a heads up

**Comment by davidkline-ms** [comment]
looks good to me. i will defer to @cre8ivepark for final verdict

**Review by cre8ivepark — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
