### PR TITLE
Mrtk base controller changes

### PR DESCRIPTION
**Pull request by Alexees**
I changed a couple of the already existing properties to forward either their backing instance or null. This makes way for using Null coalescing and conditional operators, in this particular example the BaseController class.

- Starts fixing: #3707  .

### CODE REVIEW

**Comment by Alexees** [comment]
@MenelvagorMilsom This is a freshly created pull request and seem to suffer from the same problem the one you contacted me about had.

**Comment by MenelvagorMilsom** [comment]
@Alexees that's strange. Again this current problem is unrelated to your PR. For some reason Unity is still holding a lock from previous builds. I'll investigate and get back to you.

**Comment by MenelvagorMilsom** [comment]
Oh wait, looks like things are fixed in [build 345](https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=345). Apologies, but the CI system is new and quite brittle.

**Comment by MenelvagorMilsom** [comment]
So it looks like the newest failure may actually be related to your changes. Can you try running build.ps1 found in the MRTK root and verify that it doesn't fail.

**Comment by StephenHodgson** [comment]
Can you confirm that the Resharper Unity plugin still raises warnings/errors about this even after moving the null checks to the properties?

**Comment by Alexees** [comment]
From the looks of #3707 it's more like not making use of the two operators at all.

**Pull request closed without merging**
