### PR TITLE
Unity UI (UGUI) Examples Polish

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
Unity UI (UGUI) Pressable Button prefabs and examples polish.
- Fixed UGUI Pressable Button's highlight plate proximity behavior (Added separate material for UGUI)
- Added Slate + UGUI ScrollView example (Added as a Prefab variant)
- ScrollView example includes grid layout example with mixed 2D contents: image, text, GUIs...
- Updated HandInteractionExamples scene

MRTK_UGUIExample

## Changes
- Fixes: #7305

## Before & After Screens
UGUI Pressable Button Before: Wrong proximity highlight behavior
MRTK_UGUIButton1

UGUI Pressable Button After:
MRTK_UGUIButton3

HandInteractionExamples scene: Before:
2020-02-12 09_43_12-Unity 2018 4 13f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples

HandInteractionExamples scene: After:
2020-02-12 09_33_16-Unity 2018 4 13f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples

### CODE REVIEW

**Comment by cre8ivepark** [comment]
Found an issue: direct touch scroll requires deeper touch than expected. Investigating.

**Comment by thalbern** [comment]
Looks amazing Yoon!

**Comment by wiwei** [comment]
@cre8ivepark are you good to have this go in now, or are you still wanting to address @thalbern's comment?

**Comment by cre8ivepark** [comment]
@wiwei I'll add sound and push.

**Comment by cre8ivepark** [comment]
Added audio feedback for the far interaction, added See-it, Say-it label.
2020-02-21 15_14_43-Unity 2018 4 13f1 Personal -  PREVIEW PACKAGES IN USE  - HandInteractionExamples

**Comment by keveleigh** [comment]
Looks good! @cre8ivepark is this ready to be merged?

**Comment by cre8ivepark** [comment]
@keveleigh Yes, ready to merge. I just reverted an accidental commit (check box/radio/toggle button update)

**Pull request merged**
