### PR TITLE
Update MRTK code to use CoreServices

### PR DESCRIPTION
**Pull request by Troy-Ferrell**
## Overview

NOTE: No functional changes done. Only re-routing to use CoreServices cache instead of lots of local caches

This updates the MRTK code to use the CoreServices helper class

I know lots of file changes but all the same consistent change and again not a functional change

## Changes
- Fixes: # .

### CODE REVIEW

**Comment by Troy-Ferrell** [comment]
> Hitting errors in input simulation...
> 
> Assets\MixedRealityToolkit.Services\InputSimulation\SimulatedArticulatedHand.cs(80,21): error CS0103: The name 'InputSystem' does not exist in the current context

Did you pull latest? ...or maybe I didn't push latest.

**Comment by davidkline-ms** [comment]
Hit some in the UWP build as well...

Assets\MixedRealityToolkit.Providers\WindowsMixedReality\BaseWindowsMixedRealitySource.cs(165,17): error CS0103: The name 'InputSystem' does not exist in the current context

**Pull request merged**
