### PR TITLE
Ported default cursor into SDK to test cursor visibility & functionality 

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixed a few issues with Focus Provider.

- Wasn't updating the default gaze transform on start before pointer was created which broke stuff.
- Added a few more assertions for easier debugging.

blocked by #2412

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
I take it were also waiting on an actual script in the SDK to present the cursor. I don't see one.
Note, the MRTK shouldn't render the cursor, the SDK component for visualizing the cursor should.

**Comment by davidkline-ms** [comment]
Do these animations have the same 0 frame length issue that master has? #2067. If so, we should fix or remove before merging

**Comment by SimonDarksideJ** [comment]
This PR is still showing changes from the previous PR?  does the branch need refreshing?

**Comment by StephenHodgson** [comment]
> I take it were also waiting on an actual script in the SDK to present the cursor. I don't see one.
Note, the MRTK shouldn't render the cursor, the SDK component for visualizing the cursor should.

It's been in there for a while.  I suppose you're asking to move the cursor implementation from the core to the SDK layer.

**Comment by StephenHodgson** [comment]
>This PR is still showing changes from the previous PR? does the branch need refreshing?

Yeah I haven't merged in the changes from the dev branch yet. I currently don't have internet so that might have to wait until tomorrow.

**Comment by SimonDarksideJ** [comment]
That's correct @StephenHodgson , the SDK should be responsible for rendering the cursor, utilising the InputSystem.  Not Core.

**Comment by StephenHodgson** [comment]
> Do these animations have the same 0 frame length issue that master has?

I didn't get any warnings when I imported it.

Take a pull and find out.

**Comment by StephenHodgson** [comment]
> the SDK should be responsible for rendering the cursor

The renderer component is rendering it 😉.

You mean to say that the cursor class that determines the cursor implementation should be in the SDK, correct?

**Comment by SimonDarksideJ** [comment]
> You mean to say that the cursor class that determines the cursor implementation should be in the SDK, correct?

That's correct @StephenHodgson 
Helpers can be in core, but the actual vizualization and implementation should be in the SDK.

**Comment by SimonDarksideJ** [comment]
On further review, I'm happy with the direction this SDK prefab has taken.
Sent a PR to @StephenHodgson to remove the #IF WSA checks in cursor (as it's related)

**Pull request merged**
