### PR TITLE
Add version files (semver) and propogate license to package roots

### PR DESCRIPTION
**Pull request by davidkline-ms**
Overview
---
Added Version.txt file containing the following: Mixed Reality Toolkit <package subname> <version> to each root level package folder (ex: Assets\MixedRealityToolkit).

Add license.txt from the repository root to the packages roots.

- Fixes: #1858  .

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Did we want three different license text files for each folder?

**Comment by StephenHodgson** [comment]
But they're essentially the same exact file? 

We could write an exporter that can update the version and copy the version text and license into the proper folder.

**Comment by davidkline-ms** [comment]
true, the license files are the same. the version files are not since we MIGHT support limited mixing and matching of the packages.

**Comment by StephenHodgson** [comment]
This PR was also missing meta files for these assets.

**Pull request merged**
