### PR TITLE
Add support for controller haptics across legacy, Windows XR Plugin, and OpenXR

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

Add support for controller haptics across legacy, Windows XR Plugin, and OpenXR (might work for Oculus too). It can be accessed by querying an object (likely an `IMixedRealityController` if it supports `IMixedRealityHapticFeedback`.

## Changes
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9734

### CODE REVIEW

**Review by RogPodge — APPROVED** [review]

**Review by davidkline-ms — APPROVED** [review]
looks great!

**Pull request merged**
