### PR TITLE
Changed near smoothing default to true to keep existing behavior.

### PR DESCRIPTION
**Pull request by thalbern**
## Overview
Changed the new Near Smoothing property in Object Manipulator to true so the default behavior stays the same. This used to be one flag for smoothing for both near and far. After splitting it up near smoothing got a different default which will change the defaults and therefor introduce a breaking change.

## Changes
- Fixes: #8523

### CODE REVIEW

**Comment by cre8ivepark** [comment]
@thalbern Thanks, Bernadette! One question - would this change will update all example scenes?

**Comment by thalbern** [comment]
> @thalbern Bernadette Thalhammer FTE Thanks, Bernadette! One question - would this change will update all example scenes?

no - scenes that have been saved already with the wrong default won't be automatically updated. only the ones that don't have this serialized yet. Do we want this off in all our scenes? i can do a quick search an replace for it if so.

**Comment by cre8ivepark** [comment]
@cre8ivepark Yes, we need to make Smoothing Near 'on' for all prefabs (e.g. NearMenu) and objects in the example scenes (e.g. coffee cup) If there is a way to automate it, it would be amazing.

**Review by cre8ivepark — APPROVED** [review]

**Comment by thalbern** [comment]
scenes and prefabs are all up to date now / using smoothing for near interaction

**Comment by jbienz** [comment]
Actually, I don't agree with this being on by default. The main reason for this change was so that objects feel more 'connected' to the users hand when they are directly grasped.

I guess we should maybe talk about what consists of a breaking change. My understanding was that a breaking change was breaking when it broke a build for a customer. In that definition there was no breaking change because the previously existing property still remains with a deprecated attribute.

I do agree that there is a _behavioral_ change. But in my opinion that was both by design and desired. Also, note that this is not the only behavioral change that was merged in my PR. Not only was Near Smoothing turned off by default, Near Physics was turned off by default too.

This _may_ come down to a matter of preference, but I believe this is something that should run through user testing. If you decide to do this, here are some recommendations I think would be helpful as part of that testing:

- Make sure there are several objects in the scene. 
- Some objects should be movable and others should be fixed
- All objects should be of various shapes and sizes
- All movable objects should have RigidBodys
- All movable objects should have varying mass (via RigidBody)
- Any object being manipulated should also have a RigidBody (it should already since it's movable, just want to be clear)
- There should be a stack of movable objects (e.g. stack of boxes) that can be knocked over
- The objects in the stack should have heavier than average mass

** Here is a potential test script:**

Have users pick up different objects and move them around the scene (using near manipulation). Encourage them to collide the object they're holding into other objects. Ask users to describe how they feel about:

1. The movement of the object in their hand, especially when they move their hand quickly.
1. Interactions between movable and immovable objects.
1. Holding a low mass object and colliding with a high mass object.
1. Holding a high mass object and colliding with a low mass object.
1. Colliding the held object into the stack of objects.

Perform all above steps with Use `Physics for Near Manipulations ON` & `Near Smoothing ON`
Perform all above steps with Use `Physics for Near Manipulations ON` & `Near Smoothing OFF`
Perform all above steps with Use `Physics for Near Manipulations OFF` & `Near Smoothing ON`
Perform all above steps with Use `Physics for Near Manipulations OFF` & `Near Smoothing OFF`

Compare the feedback and decide what the defaults should be.

IMO you will find a strong preference for the object to stick to the users hand rather than honor physics. I expect this will be especially prevalent in cases where the user is holding a light mass object and interacting with a heavy mass object. I expect this to be most prevalent when holding a light mass object and attempting to knock the stack over.

Think of the following example: 

Throwing an empty cardboard box at a stack of partially filled boxes will have little to no affect on the stack. But if I hold onto the box, there's a good chance I can use it as leverage to push the stack over.

This is the difference between Use Physics for `Near Manipulations` `ON` and `OFF`. When `Use Physics for Near Manipulations` is `ON`, the box will act as though it's being "thrown" rather than "held". You can actually see this in the code where we're using physics methods like `AddForce`.

The difference between `Near Smoothing` `ON` vs `OFF` is just lag. It won't keep the boxes from being knocked over, but the object being held will lag behind the users hand. IMO, once the user _notices_ this lag, they will prefer jitter over lag. But that would have to be verified in user testing. I could not remove this lag no matter how small I set the smoothing values. If it's possible to remove jitter without adding lag, I'm all for it. But with the current implementation I would still prefer smoothing to be OFF by default for near manipulations.

**Review by jbienz — CHANGES_REQUESTED** [review]
Please see my lengthy post in the main discussion about why I'd prefer not to make this change. Note that there are also other behavioral changes that were made aside from this one (Use Physics for Near Manipulation is now OFF by default too).

**Comment by jbienzms** [comment]
Actually, I don't agree with this being on by default. The main reason for this change was so that objects feel more 'connected' to the users hand when they are directly grasped.

I guess we should maybe talk about what consists of a breaking change. My understanding was that a breaking change was breaking when it broke a build for a customer. In that definition there was no breaking change because the previously existing property still remains with a deprecated attribute.

I do agree that there is a _behavioral_ change. But in my opinion that was both by design and desired. Also, note that this is not the only behavioral change that was merged in my PR. Not only was Near Smoothing turned off by default, Near Physics was turned off by default too.

This _may_ come down to a matter of preference, but I believe this is something that should run through user testing. If you decide to do this, here are some recommendations I think would be helpful as part of that testing:

- Make sure there are several objects in the scene
- Some objects should be movable and others should be fixed
- All objects should be of various shapes and sizes
- All movable objects should have RigidBodys
- All movable objects should have varying mass (via RigidBody)
- Any object being manipulated should also have a RigidBody (it should already since it's movable, just want to be clear)
- There should be a stack of movable objects (e.g. stack of boxes) that can be knocked over
- The objects in the stack should have higher-than-average mass

**Here is a potential test script:**

Have users pick up different objects and move them around the scene (using near manipulation). Encourage users to collide the object they're holding into other objects in the scene. Ask users to describe how they feel about:

1. The movement of the object in their hand, especially when the hand is moving quickly.
1. Interactions between movable and immovable objects.
1. Holding a low mass object and colliding with a high mass object.
1. Holding a high mass object and colliding with a low mass object.
1. Colliding the held object into the stack of objects.

Perform all above steps with Use `Physics for Near Manipulations ON` & `Near Smoothing ON`
Perform all above steps with Use `Physics for Near Manipulations ON` & `Near Smoothing OFF`
Perform all above steps with Use `Physics for Near Manipulations OFF` & `Near Smoothing ON`
Perform all above steps with Use `Physics for Near Manipulations OFF` & `Near Smoothing OFF`

Compare the feedback and decide what the defaults should be.

IMO you will find a strong preference for the object to stick to the users hand rather than honor physics. I expect this will be especially prevalent in cases where the user is holding a light mass object and interacting with a heavy mass object. I expect this to be most prevalent when holding a light mass object and attempting to knock the stack over.

Think of the following example: 

Throwing an empty cardboard box at a stack of partially filled boxes will have little to no affect on the stack. But if I hold onto the box, there's a good chance I can use it as leverage to push the stack over.

This is the difference between `Use Physics for Near Manipulations` `ON` and `OFF`. When `Use Physics for Near Manipulations` is `ON`, the box will act as though it's being "thrown" rather than "held". You can actually see this in the code where we're using physics methods like `AddForce`.

The difference between `Near Smoothing` `ON` vs `OFF` is just lag. It won't keep the boxes from being knocked over, but the object being held will lag behind the users hand. IMO, once the user _notices_ this lag, they will prefer jitter over lag. But that would have to be verified in user testing. I could not remove this lag no matter how small I set the smoothing values. If it's possible to remove jitter without adding lag, I'm all for it. But with the current implementation I would still prefer smoothing to be OFF by default for near manipulations.

**Review by jbienzms — CHANGES_REQUESTED** [review]
Please see my lengthy post in the main discussion about why I'd prefer not to make this change. Note that there are also other behavioral changes that were made aside from this one (Use Physics for Near Manipulation is now OFF by default too).

**Comment by thalbern** [comment]
> Actually, I don't agree with this being on by default. The main reason for this change was so that objects feel more 'connected' to the users hand when they are directly grasped.
> 
> I guess we should maybe talk about what consists of a breaking change. My understanding was that a breaking change was breaking when it broke a build for a customer. In that definition there was no breaking change because the previously existing property still remains with a deprecated attribute.

That's not entirely true - the old property was split up in 2 properties where only one of them sticked to the original default behavior. Usually I would agree when introducing a new property that this is of course no breaking change. But in this case we are changing the default behavior of existing functionality. We should be avoiding changing defaults if there's no strong argument against it, or if that's not possible make a note in the release notes. 


> 
> I do agree that there is a _behavioral_ change. But in my opinion that was both by design and desired. Also, note that this is not the only behavioral change that was merged in my PR. Not only was Near Smoothing turned off by default, Near Physics was turned off by default too.
> 

That's a good point. If we agree on this change we should change the near physics property back as well. 

> This _may_ come down to a matter of preference, but I believe this is something that should run through user testing. If you decide to do this, here are some recommendations I think would be helpful as part of that testing:
> 
> * Make sure there are several objects in the scene
> * Some objects should be movable and others should be fixed
> * All objects should be of various shapes and sizes
> * All movable objects should have RigidBodys
> * All movable objects should have varying mass (via RigidBody)
> * Any object being manipulated should also have a RigidBody (it should already since it's movable, just want to be clear)
> * There should be a stack of movable objects (e.g. stack of boxes) that can be knocked over
> * The objects in the stack should have higher-than-average mass
> 
> **Here is a potential test script:**
> 
> Have users pick up different objects and move them around the scene (using near manipulation). Encourage users to collide the object they're holding into other objects in the scene. Ask users to describe how they feel about:
> 
> 1. The movement of the object in their hand, especially when the hand is moving quickly.
> 2. Interactions between movable and immovable objects.
> 3. Holding a low mass object and colliding with a high mass object.
> 4. Holding a high mass object and colliding with a low mass object.
> 5. Colliding the held object into the stack of objects.
> 
> Perform all above steps with Use `Physics for Near Manipulations ON` & `Near Smoothing ON`
> Perform all above steps with Use `Physics for Near Manipulations ON` & `Near Smoothing OFF`
> Perform all above steps with Use `Physics for Near Manipulations OFF` & `Near Smoothing ON`
> Perform all above steps with Use `Physics for Near Manipulations OFF` & `Near Smoothing OFF`
> 
> Compare the feedback and decide what the defaults should be.
> 
> IMO you will find a strong preference for the object to stick to the users hand rather than honor physics. I expect this will be especially prevalent in cases where the user is holding a light mass object and interacting with a heavy mass object. I expect this to be most prevalent when holding a light mass object and attempting to knock the stack over.
> 
> Think of the following example:
> 
> Throwing an empty cardboard box at a stack of partially filled boxes will have little to no affect on the stack. But if I hold onto the box, there's a good chance I can use it as leverage to push the stack over.
> 
> This is the difference between `Use Physics for Near Manipulations` `ON` and `OFF`. When `Use Physics for Near Manipulations` is `ON`, the box will act as though it's being "thrown" rather than "held". You can actually see this in the code where we're using physics methods like `AddForce`.
> 
> The difference between `Near Smoothing` `ON` vs `OFF` is just lag. It won't keep the boxes from being knocked over, but the object being held will lag behind the users hand. IMO, once the user _notices_ this lag, they will prefer jitter over lag. But that would have to be verified in user testing. I could not remove this lag no matter how small I set the smoothing values. If it's possible to remove jitter without adding lag, I'm all for it. But with the current implementation I would still prefer smoothing to be OFF by default for near manipulations.

This is something where I would rather have an interaction designer follow up (@cre8ivepark , @julenka) - I think that both cases are valid use cases (having smoothing and physics enabled or not as a default). 
Having some user tests is a good idea, however if this is something you would want then this needs to be planned separately as it's currently beyond my working capacity for MRTK.

**Comment by cre8ivepark** [comment]
@jbienzms Smoothing was added and made as default by the team after experiencing and testing various types of HL2 projects (internal & external partners) For the default behavior, we wanted to provide shell-parity experience first and from there, developers can easily customize. We see hand-tracking related jitter without smoothing provides degraded experience especially for the UI (Near Menu, etc.) I think it would be better to maintain the default consistency and provide clear documentation & an example scene that communicates the new option for turning off smoothing. I can imagine many people who have been using ObjectManipulator confused by unexpected jitter and spend time to find the cause of the changed behavior.

**Comment by jbienzms** [comment]
@cre8ivepark Thanks for your thoughts Yoon.

I absolutely agree with shell parity. Though I'm unaware of an example in the shell where any _held_ object can collide with another object. The Start menu and App slates will hover above walls, but the start menu can't be held and windows don't have mass or collide with each other.

Ultimately I trust your intuition Yoon. Whatever your gut tells you, I'll accept.

One thing I'd really like ask for is to leave `Use Physics for Near Manipulations` `OFF` by default. Again, I can't think of a scenario in the shell where objects collide or have mass. I really do believe that when an object is held, the user should be able to push that object through a stack of objects (even if the objects in the stack have more mass).

Again I will defer to you. But I'd like to humbly request extra thought and care be put into this one.

Thanks

**Comment by cre8ivepark** [comment]
@jbienzms Thank you the comments! The examples of grabbing and moving objects in the shell are the objects placed in the world - 3D app icons, 3D holograms from the 3D viewer, and 2D slates - they show default smoothing behavior with tether line visuals. Regarding the 'Use physics' option, I remember that it was added to achieve the collision with the spatial mesh. (again, just like the shell - when you grab and move 3D holograms or 2D slates) Customers continuously requested this shell-parity behavior and we didn't have this proper collision until we have new Object Manipulator. 
And this was the video about it :)
https://twitter.com/cre8ivepark/status/1253537742874525698?s=20

**Comment by thalbern** [comment]
given @cre8ivepark s comment . should i reenable physics for near interaction by changing the flag to default enabled and patching up the scene files? (it's currently per default off on near interaction since @jbienzms introduced the flag).

**Comment by jbienzms** [comment]
The problem with that video @cre8ivepark, is that it's far manipulation not near manipulation. I agree with physics being enabled for far manipulation. 

From my original pull request, please not how little effort is required for a user to knock over these boxes when physically holding the coffee cup in this video:

**Video A:**
NoSmoothing

Now compare that with how much effort is required to knock over the same boxes while holding the coffee cup in this video:

**Video B**
Smoothing

Which video above would you prefer to be the default? If **Video A**, then Physics should be `OFF` for Near Interactions. If **Video B**, then Physics should be `On` for Near Interactions.

**Comment by cre8ivepark** [comment]
@jbienzms As long as the object can collide with the spatial mesh while manipulating it, yes I think it sounds great. 
Summary - It seems 'Use Forces for Near Manipulation' is already OFF by default and in this PR, we only check Smoothing Near.
2020-09-15 13_23_19-MRTK-Public - HandInteractionExamples - Universal Windows Platform - Unity 2019

**Comment by cre8ivepark** [comment]
@thalbern I'll fix the scene merge conflict. It must be the conflict about the description panels.

**Comment by thalbern** [comment]
thanks @cre8ivepark ! I've done a second pass of hand coach because there were a lot of unrelated changes now - want to make sure we're not adding any unnecessary diffs in this PR as we're touching a lot of files in stabilization. 

@jbienzms , @cre8ivepark  we have smoothing for near default enabled now but physics for near off. If that is correct I would try to get this PR in today. :)

**Comment by jbienzms** [comment]
Yes, thanks @cre8ivepark, I should have actually looked at the inspector. Every time I wrote "Use Physics" I should have been writing "Use Forces". I realize that added to the confusion and I will go back and edit my post for clairty.

I believe we are all in alignment. I do still believe there is lag with near smoothing that I would eventually love to see addressed, but I'm happy to see _Forces_ still defaulting to Off for near.

Thank you both!

**Comment by thalbern** [comment]
> Yes, thanks @cre8ivepark, I should have actually looked at the inspector. Every time I wrote "Use Physics" I should have been writing "Use Forces". I realize that added to the confusion and I will go back and edit my post for clairty.
> 
> I believe we are all in alignment. I do still believe there is lag with near smoothing that I would eventually love to see addressed, but I'm happy to see _Forces_ still defaulting to Off for near.
> 
> Thank you both!

Maybe we can add another example scene for the next release that will cover your scenario @jbienzms ? It might be good to show the other scenario in action :) - there's already two other object manipulator examples. we could integrate the different constellations of using the flags there?  That way you can also point to that scene in the docs.

**Comment by thalbern** [comment]
@jbienzms  can you change your vote please so we can merge the PR?

**Comment by jbienzms** [comment]
Whoops! Sorry, fixing right away.

**Review by jbienzms — APPROVED** [review]

**Pull request merged**
