### PR TITLE
Updating shader paths to MixedRealityToolkit and adding licenses where missing

### PR DESCRIPTION
**Pull request by keveleigh**

### CODE REVIEW

**Comment by keveleigh** [comment]
@StephenHodgson Woah! I'm seeing that too...

**Comment by StephenHodgson** [comment]
I think GitHub is broken atm.

**Comment by StephenHodgson** [comment]
This is a relatively minor change. I think it's safe to merge it if you're finished updating so we can get it in that master / dev sync PR.

**Comment by StephenHodgson** [comment]
@keveleigh, actually, my other repositories are fine to edit. Might be a new MSFT policy on all their GitHub projects.

**Comment by StephenHodgson** [comment]
[edit] Nope. Just seems to be _this_ repository only.  The main MRTK repo is also unaffected.

**Pull request merged**
