### PR TITLE
Clean example scenes for Depth LSR support

### PR DESCRIPTION
**Pull request by Troy-Ferrell**
## Overview

High-Level changes:
- Make all example scenes & any related assets Depth LSR supported
- Convert text to TextMeshPro where appropriate
- Convert all uses of Unity Standard Shader to MRTK Standard Shader

It is a lot of files in this change and looks like a lot. But the changes themselves are simple (i.e switching material shader from Unity to MRTK, turning off realtime global illumination, etc)

Details:
- updated scenes to use textmeshpro & updated related scripts for TMP when outputting text
- Updated some textmesh components to have opaque panels so info can be stable with depth LSR
- Update Text3DShader for TextMeshs to use ZWrite On & CullMode default Off (textmeshes are usually flat planes and if behind text, generally still want to see it - i.e on a 3D transparent slate)
- Updated Text3DSelawik* materials to use cullmode off
- Updated asmdef for MRTK Examples to utilize TextMeshPro so as to access library in scripts
- Changed Gesture scene material from Unity Standard Shader to MRTK standard
- Updated piano.prefab to use TextMeshPro
- Updated PanelBorder* transparent materials used in Material example scenes to ZWrite to depth @Cameron-Micka 
- Updated Placard Prefab textmesh to write to depth
- Updated SceneDescriptionPanel.prefab & EyeTrackingDemos_SceneDescriptionPanel.prefab to have parent canvas width/height equal to 1 (this makes it less annoying to select objects in scene) as well as add canvasutility
- Updated Mars Rover Materials from Unity Standard shader to MRTK standard shader
- Disabled Realtime Global Illumination for all examples scenes (even with low quality settings we have seen computation impact)
- Fixed PrimaryPointerExample to have material on CursorHighlight object (was rendering pink)
- Fixed scene description panel in InspectorFieldsExample scene due to odd rich text issues
- Deleted standard shader materials in ManipulationHandlerExample scene and used standard asset MRTK materials
- Fixed ObjectCollectionExample scene to not use default material Unity Standard shader but standard asset MRTK material
- Updated LinesExample scene to use latest particle unlit shader instead of legacy shader

## Changes
- Fixes: #5332 

## Verification
Verified in editor for key, changed scenes
TODO: Need to run HandInteractionExamples scene on device

> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by Cameron-Micka** [comment]
This is great! I was hoping a lot of these changes could be made before GA. I can pull this down and review when I get a free moment.

**Comment by cre8ivepark** [comment]
Re-assigned missing materials for the Mars Rover in the Tooltip Examples scene.
2019-07-19 12_37_28-Unity 2018 4 2f1 Personal - TooltipExamples unity - MRTK-GitHub - Universal Wind

**Comment by cre8ivepark** [comment]
@Troy-Ferrell It seems like there is one merge conflict (InteractablesExamples.unity) with your previous PR #5321

**Comment by Troy-Ferrell** [comment]
> @Troy-Ferrell It seems like there is one merge conflict (InteractablesExamples.unity) with your previous PR #5321

Merged done!

**Pull request merged**
