### PR TITLE
Platforms

### PR DESCRIPTION
**Pull request by trzy**
Add QueryTopology_FindLargestPositionsSittable() to Unity and update the Spatial Understanding demo with this query. This is the companion to: https://github.com/Microsoft/HoloToolkit/pull/86

(Do I need to also submit the compiled DLLs or will one of the maintainers build and update them?)

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@trzy, please be sure to sign the CLA

**Comment by trzy** [comment]
How do I sign it? I see no option to do so?

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/HoloToolkit-Unity/blob/master/CONTRIBUTING.md

**Comment by trzy** [comment]
Thanks! That was really buried in there :) Signed!

**Comment by trzy** [comment]
Any plans to merge this in?

**Comment by StephenHodgson** [comment]
Needs two approvals.

Sorry I hadn't had time to pull and review it.

**Comment by StephenHodgson** [comment]
Please also include the updated dll

**Comment by trzy** [comment]
I'd be happy to but are you sure you want me to do that? As a matter of security policy, is it a good idea to allow random people to incorporate binaries into the repo? Seems to me that an official, trusted moderator should compile and commit them. However, I'll add them in a moment anyway in case you'd like to use them.

**Comment by StephenHodgson** [comment]
Good point. Generally the dlls are copied from the other repo by MSFT. We can hold off for it to be approved there.

**Comment by trzy** [comment]
Okay -- so nothing more to be done? Hopefully my changes can get merged over there soon...

**Comment by StephenHodgson** [comment]
For now, yes. Let's see this get merged in the HTK first, and get the binaries from there.

**Comment by NeerajW** [comment]
Looks like Kurtis merged the HoloToolkit PR.

**Comment by trzy** [comment]
Reopened? Anything needed on my end?

**Comment by StephenHodgson** [comment]
I was just trying to get the CLA check to pass.  No, once we get the binaries updated from the main toolkit this will get merged in.

**Comment by trzy** [comment]
Ok, thanks! Any ETA on binaries being merged in? There is still more functionality that I may want to expose in the C# interface in the near future but I'd rather have these merged in first.

**Comment by StephenHodgson** [comment]
I wish I could tell you.  I don't have the ability to merge on that project, and it seems like it's been dead there for a while.

**Comment by trzy** [comment]
I understand. Maintaining a separate HoloToolkit branch is becoming painful though. Anyway to let MS grant you authority to merge on that project? Going forward, it seems this is a pretty severe bottleneck to HoloToolkit progress. I suppose another possibility is to just rip SpatialUnderstanding out of HoloToolkit altogether and maintain a separate project.

**Comment by DDReaper** [comment]
Any progress on getting the updated binaries sorted @StephenHodgson , this PR does seem to be falling behind and may need rebasing.

**Comment by StephenHodgson** [comment]
MSFT said they were going to sign the binaries and copy them to this repo.  Not sure about the timeline.

**Comment by StephenHodgson** [comment]
@trzy can you update the branch for the conflicts please?

@NeerajW  and @keveleigh are going to migrate the binaries and sign them soon.

**Comment by trzy** [comment]
I'll try to check it out tonight. I wasn't aware there were any conflicts (merge conflicts?).  As I recall it was just an addition of a couple lines.

**Comment by trzy** [comment]
Sorry, wasn't sure how to pull in the extensive changes without creating a new branch. I've created a new pull request. Please close this one and approve https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1435 instead.  Thank you!

**Pull request closed without merging**
