### PR TITLE
StandardShaderGUIFix

### PR DESCRIPTION
**Pull request by Alexees**
## Overview

The way the "Albedo Alpha Mode" was drawn in the inspector was not correct.

- Fixes: #5978

### CODE REVIEW

**Comment by Alexees** [comment]
@Cameron-Micka just went through the issue list and found the issue this PR fixes still open. Isn't there a good mechanism to auto close related issues?

**Comment by Cameron-Micka** [comment]
@Alexees I just manually closed the issue. That's a good question, @keveleigh might know if there is a process to auto close related issues or why we don't currently do that.

**Comment by keveleigh** [comment]
@wiwei has been thinking through retooling our branches a bit (#5780) to help us take advantage of auto issue closing. I've noticed that sometimes the build bot account is able to auto close issues when they're referenced in a commit name when it commits the docs (for example, see the Closed message at the bottom of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5996), but I'm not fully sure why that happens, since it's not committing to a default branch.

**Comment by Cameron-Micka** [comment]
Ah, thank you for the insight @keveleigh!

**Pull request merged**
