### PR TITLE
Asset Organization

### LINKED ISSUE #866: Merge Examples and Test folders
I'd like to propose we merge the Examples and Tests folders into one.

There seems to be many tests in examples and examples in tests.
Also we already have a folder for Unit Testing.
This would also reduce the number of asset packages in each release.

If this proposal is accepted we should do it at the same time we rename the folders from `HoloToolkit` to `MixedRealityToolkit` (See https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/867)

### LINKED ISSUE #867: Rename HoloToolkit folders to MixedRealityToolkit
I know this is already on the roadmap but I'd like to put it here for tracking purposes.

### LINKED ISSUE #987: MicStreamSelector.dll fails to pass WACK
`MicStreamSelector.dll` does not pass WACK compliance for the Windows Store.

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixes #867
Fixes #866 
Workaround for #987 by temporarily moving dll out of the core toolkit.
(It will be put back when passing [WACK](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-app-certification-kit))
- Updated URLs and links in all readme files.
-  Merged `HoloToolkit-Tests` into `HoloToolkit-Examples`.
-  Renamed `HoloToolkit `folders to `MixedRealityToolkit`.
-  Renamed `SpeechKeywordRecognizedEventData` to `SpeechEventData`.
-  Moved `MicStreamSelector.dll` to Examples because it does not pass WACK compliance.
-  Moved `MicStream.cs` to `MixedRealityToolkit-Examples/Input`.
-  Moved `VoiceChat` folder in sharing to the `MixedRealityToolkit-Examples/Sharing/SharingSerivce`.
- Removed Obsolete `KeywordManager` & `DisplayKeywords`.
- Removed Obsolete `GameControllerManipulator `.

### CODE REVIEW

**Comment by DDReaper** [comment]
Can we please move all the "Tests" folders from what is currently "HoloToolkit" to a new root folder, aka "HoloToolkit-TestScenes" ("MixedRealityToolkit-TestScenes")
Or also put them in the examples folders.

Reason being, the current structure makes it very hard to make a reusable Asset.  Should be able to Import and then just delete the examples in a production project.

**Comment by StephenHodgson** [comment]
The examples and test scenes are already excluded from the release packages.

**Comment by DDReaper** [comment]
Ahh, as I'm using the dev branch source for MR, I didn't realise that.

**Comment by StephenHodgson** [comment]
Thanks,  I've already addressed this issue in the MR branch PR for the same issue.

**Comment by DDReaper** [comment]
Any update @StephenHodgson on when the major breaking changes will be merged.  Seeing several ranging from Merging core MRToolkit updates, Merge to 2017.2 branch and renames, etc.

Seeing the Public release (Oct 17th) is fast approaching, would be good to get this tidied up sooner. Happy to help and pitch in if required.

**Comment by StephenHodgson** [comment]
As soon as we get two approved reviews on this PR.

**Comment by DDReaper** [comment]
Does this PR not conflict with #972 as there seem to be TWO reorg PR's outstanding.  Would it not be better to include all the reorg in one go?

**Comment by StephenHodgson** [comment]
I'm going to close this.  I'd like to see a few of the folder structures get updated before doing the rename.

**Pull request closed without merging**
