### PR TITLE
Fixed a bug where the grab action was classified incorrectly

### PR DESCRIPTION
**Pull request by RogPodge**
## Overview
The grab interaction mapping was misclassified as DeviceInputType.TriggerPress before, making articulated hand interactions behave differently on the XRSDK pipeline compared to the Legacy XR pipeline. This PR fixes this by classifying the grab interaction correctly as DeviceInputType.GripPress, making the grab interaction behave identically across both platforms.

## Changes
- Fixes: #9007

### CODE REVIEW

**Comment by RogPodge** [comment]
The DefaultOpenXRControllerMappingProfile needs an update, however when I run the "Update Controller Mapping Profiles" option, the size of the change is pretty immense. @keveleigh I think you're a bit more informed on what parts need to stay the same in that profile, can you try reserializing it after this PR gets in?

**Comment by keveleigh** [comment]
@RogPodge Can do! If you have Unity 2020 installed, reserializing it there should produce more expected results

**Review by keveleigh — APPROVED** [review]

**Pull request merged**
