### PR TITLE
Update roadmap for new version scheme

### PR DESCRIPTION
**Pull request by ryzngard**
As discussed in #2888

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Couldn't we just use it as the unity targeting version?

For example:

Unitys version is 2018.1.9f1
MRTK version is 2018.1.[release].[revision]

**Comment by ryzngard** [comment]
NuGet only supports 3 numbers, as is specified by SemVer. I'm not sure why we have 4. 

If we are strictly following SemVer, we can encapsulate Unity version as [prod].[release].[revision]-Unity2018.1

**Comment by ryzngard** [comment]
[NuGet Versioning](https://docs.microsoft.com/en-us/nuget/reference/package-versioning) does have one interesting part but isn't documented well. 

```
1.00 is treated as 1.0
1.01.1 is treated as 1.1.1
1.00.0.1 is treated as 1.0.0.1
```

That seems to indicate that 4 numbers might be supported, but isn't specified in SemVer.

**Comment by davidkline-ms** [comment]
Let's stick to 3 version components as it is the most commonly used and is more compatible with other systems (ex: Windows Store)

**Comment by davidkline-ms** [comment]
>Couldn't we just use it as the unity targeting version?
For example:
Unitys version is 2018.1.9f1
MRTK version is 2018.1.[release].[revision]

I'd rather not as we will eventually lock on the Unity LTS release (ex: 2018.4) which would result in an essentially unused parameter (and that is a step quite a bit backward to the HTK versioning scheme).

**Comment by davidkline-ms** [comment]
> Why is the fourth always zero?
I'm in favor of dropping it but didn't explicitly bring that up for consensus.

I'm fine with us only specifying 3. It's not like we are using a VersionInfo struct :)

**Comment by StephenHodgson** [comment]
> It's not like we are using a VersionInfo struct 

Actually we do, but that's in the build window ;)

**Pull request merged**
