### PR TITLE
Feature/back strafing steps

### PR DESCRIPTION
**Pull request by SGHolospace**
## Overview
In a game world or VR world its normal to have uneven planes and borders. Current teleport pointer does n't allow climbing steps when doing back strafe or its not block the movement if there is collider in the back. This pull request has one implementation to solve this issue, which checks whether there is flat plane exist so the user can back strafe or its just wont do the move if there is no plane or slope. Kindly check this pull and let me know if there is a better way to handle this.

## Changes
- Fixes: # back strafing on slopes and steps

### CODE REVIEW

**Comment by keveleigh** [comment]
This looks related to #6706

**Comment by RogPodge** [comment]
@SGHolospace do you have time to fix the issues in the pipeline? Otherwise I was thinking of incorporating it into here: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9428 which helps fix issues we've had with teleport height.

**Comment by RogPodge** [comment]
Heads up, moving development into https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9697 so that we can close on this issue this week!

**Comment by RogPodge** [comment]
Closing with the merge of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9697

**Pull request closed without merging**
