### PR TITLE
[UX] Hand menu improvement - voice command (accessibility)

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
Currently, there is no way to invoke or hide the hand menu if the user cannot use both hands.
This PR updates hand menu examples and prefabs with voice commands added 'show hand menu' and 'hide hand menu'. Includes updated README file.

**MRC** : https://gfycat.com/slightdelayedfalcon

2020-12-02 22_00_39-MRTK_UX_BuildingBlocks_MSKorea_YoonPark_Nov2020 pptx - PowerPoint

**SpeechInputHandler.cs** script is used to enable voice command input. On "Show hand menu" keyword recognition, the example enables Follow solver and changes SolverHandler's tracked target type to Head to achieve tag-along behavior. The example disables HandConstraintPalmUp since the menu should stay within the user's FOV without hand detection for hands-free mode. For "Hide hand menu" keyword, Follow solver is disabled, SolverHandler's tracked target type to Hand Joint, and HandConstraintPalmUp is enabled.

Voice command keywords are defined in **HandMenuSpeechCommandsProfile**.

2020-12-04 18_50_28-Unity 2018 4 28f1 -  PREVIEW PACKAGES IN USE  - HandMenuExamples unity - MRTK -

## Changes
- Fixes: #8994

### CODE REVIEW

**Comment by julenka** [comment]
Is there a way to dismiss the tag-along hand menu WITHOUT using the "Hide hand menu" voice command? I wonder if there may be issues with discovering the "hide hand menu" voice command, especially if that command gets triggered on accident and user didn't know how they made this menu appear. Perhaps a was to close the menu via a button would be helpful?

**Review by julenka — APPROVED** [review]

**Comment by cre8ivepark** [comment]
@julenka Good point! We could use the same close button displayed on auto-world-lock example. Might be good to be paired with an explicit (floating) button for opening the menu. I'll do this in a separate PR. Thanks!

**Pull request merged**
