### PR TITLE
Add nuget docs to TOC and polish

### PR DESCRIPTION
**Pull request by Troy-Ferrell**
## Overview
The documentation page for nuget packaging with MRTK is not in the TOC and thus makes it more difficult to find.

[MRTK Nuget packages](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MRTKNuGetPackage.html)

This change also cleans up some polish for the MRTK nuget doc page. Furthermore, add some see also links to related articles in the "Getting started with MRTK" section.

## Changes
- Fixes: #7129

### CODE REVIEW

**Comment by keveleigh** [comment]
@CDiaz-MS @andreiborodin Do we have steps in the docs for consuming the packages via MSBuildForUnity? Looks like these are all Nuget for Unity based

**Comment by davidkline-ms** [comment]
> Do we have steps in the docs for consuming the packages via MSBuildForUnity

i think we should add those instructions in a separate pr, when all of the steps are confirmed

**Comment by CDiaz-MS** [comment]
We do not have steps for consuming packages via MSBuildForUnity yet, but they can be added.

**Pull request merged**
