### PR TITLE
Round Shell Parity Button + Additional Button prefabs in different dimension

### PR DESCRIPTION
**Pull request by Cameron-Micka**
## Overview
Many developers use circular buttons within their UI and would like an HoloLens 2 Shell-like an example button to use within their applications. This pull request introduces a circular button prefab for developers to "drag and drop" into their application:

CircularButtons

This pull request also introduces a new shader feature which aides in developing "2D" content such as button plates and slates. The "Ignore Z Scale" option allows developers to specify any depth (Z) scale without effecting border width or other scale reliant shader features.

This PR also includes additional button prefabs in different sizes. You can find these updates in the PressableButtonExamples scene.
2019-07-23 12_35_10-Unity 2018 4 2f1 Personal - PressableButtonExample unity - MRTK-GitHub - Univers

## Changes
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5400

## Verification
Please review the examples found in the PressableButtonExample scene.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by Cameron-Micka** [comment]
Thank you Yoon!

**Comment by cre8ivepark** [comment]
Some additional example updates and prefabs.
2019-07-23 12_35_10-Unity 2018 4 2f1 Personal - PressableButtonExample unity - MRTK-GitHub - Univers

**Comment by Cameron-Micka** [comment]
Love the circular layout, thanks Yoon!

**Comment by Cameron-Micka** [comment]
@cre8ivepark would you like to handle the documentation on new buttons types/sizes? 

@wiwei I agree, many partners are unsure which button to use. I wonder if this warrants a MRTK menu item in the scene heirarchy ([[MenuItem("GameObject/MRTK/Default Button", false, 10)]](https://docs.unity3d.com/ScriptReference/MenuItem.html)) for a bunch of commonly used MRTK prefabs?

**Comment by cre8ivepark** [comment]
@Cameron-Micka @wiwei Yes! I am working on separate PR for the UX related Docs update, including the clarifications on the button prefabs that we provide in MRTK.

**Comment by cre8ivepark** [comment]
@wiwei @Cameron-Micka Updated documentation!
https://github.com/Cameron-Micka/MixedRealityToolkit-Unity/blob/round_shell_button/Documentation/README_Button.md
2019-07-24 15_59_43-Preview README_Button md - MRTK-Public-Microsoft - Visual Studio Code

**Pull request merged**
