### PR TITLE
Build Utilities update

### PR DESCRIPTION
**Pull request by StephenHodgson**
# Overview

- Opened up some of the build window methods so they can be called from third party libraries.

### CODE REVIEW

**Comment by davidkline-ms** [comment]
is this post beta or should we retarget the change?

**Comment by StephenHodgson** [comment]
Depends on how we plan the release. Are we building packages from stabilization, or are we merging stabilization back into dev and then building packages?

We're using these changes in our active project, so I thought I'd bubble them up.

**Comment by davidkline-ms** [comment]
> Are we building packages from stabilization

I intend to merge stabilization into release then tag and produce the packages

**Comment by StephenHodgson** [comment]
Doesn't matter as I consume the MRTK as a submodule anyway.

**Comment by SimonDarksideJ** [comment]
If you are actively using this @StephenHodgson in your project, then it seems fit to go in to the Beta as you are consuming this already.
Thoughts @davidkline-ms ?

**Comment by StephenHodgson** [comment]
Seems like a trivial change as we're just making the accessors public.

**Comment by StephenHodgson** [comment]
I'd rather keep bug fixes and beta critical things on stabilization

**Pull request merged**
