### PR TITLE
Homogenize Script Asset Icons Round 2

### PR DESCRIPTION
**Pull request by Railboy**
## Overview
Updates meta files to use consistent script icons.
Also adds a 'Test' script icon to mark our testing scripts.

Follow-up to #4059

### CODE REVIEW

**Comment by wiwei** [comment]
One thought here, based on feedback we got from customers, is that the fact that we have custom CS script icons is actually super confusing for people who are used to stock Unity.

It might be MORE appropriate to do a pass where we don't do custom icons for .cs files, so that they can look like regular scripts that Unity devs are used to.

**Comment by Railboy** [comment]
@wiwei I'm up for either option, but while we're deciding we should keep things consistent.

**Comment by wiwei** [comment]
> @wiwei I'm up for either option, but while we're deciding we should keep things consistent.

Sounds good to me

**Comment by wiwei** [comment]
> > @wiwei I'm up for either option, but while we're deciding we should keep things consistent.
> 
> Sounds good to me

The consistency argument will win me over 99% of the time.

**Pull request merged**
