### PR TITLE
Add 3D app launcher visualization and move to global build handler

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

* Adds a visualization to the 3D app launcher in the build window

    image

* Adds an additional access point to setting the 3D app launcher in MRTK build settings, which allows it to be used on _any_ build, not just a build through the build window

    image

* Updates the 3D app launcher field to only accept glTF files
* Adds a scrollbar to the AppX Build Settings pane in the build window, since the model visualization takes up some vertical space (recommend hiding whitespace changes when reviewing)
* Assigns an MRTK icon to our build settings

## Changes
- Follow-up to #6309, #1231

### CODE REVIEW

**Comment by MaxWang-MS** [comment]
Could you mention the change in the release notes?

**Comment by keveleigh** [comment]
>Could you mention the change in the release notes?

@MaxWang-MS Added!

**Comment by MaxWang-MS** [comment]
I just tried the PR in editor and it looked good except for when trying to build unity project/appx package I received the following warning in the console. Could you confirm whether this is expected behavior?

null texture passed to GUI.DrawTexture
UnityEditor.Editor:OnInteractivePreviewGUI(Rect, GUIStyle)
Microsoft.MixedReality.Toolkit.Build.Editor.MixedRealityBuildPreferences:DrawAppLauncherModelField() (at Assets/MRTK/Core/Utilities/BuildAndDeploy/MixedRealityBuildPreferences.cs:88)

**Comment by keveleigh** [comment]
@MaxWang-MS I wasn't able to consistently repro, but I did see it a couple times. I added the only other null check I could think of to help prevent it! Not sure if it made a big difference though, and I'm not sure a way to prevent it :/

**Review by davidkline-ms — APPROVED** [review]

**Review by MaxWang-MS — APPROVED** [review]
Just tested and looks good to me!

**Pull request merged**
