### PR TITLE
Extends SceneInfo refresh to arrays and lists

### PR DESCRIPTION
**Pull request by Railboy**
## Overview

This updates SceneInfoUtils to drill deeper into component and scriptable object fields to ensure SceneInfo data are up-to-date in editor and when building.

SceneInfoUtils will also not try to cache component types while the player is building.

## Changes
- Fixes: #6429, #6448

## Verification
Try moving the entire MRTK into a new folder.
- If you open the examples hub scene and enter play mode, the examples hub should still work.
- If you build the project _without first opening any scenes_, the examples hub should also work.

> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by Railboy** [comment]
@Kjakubzak Can you verify that this fixes your build problem?

**Comment by Kjakubzak** [comment]
> @Kjakubzak Can you verify that this fixes your build problem?

It will take me a bit to do so since I need to build a nuget and bring it into our project. I'll start now to confirm.

**Comment by Kjakubzak** [comment]
Just verified that it fixed that issue. Now we're getting a different one, but I'm pretty sure that's on us and the .NET SpatialCoordinate workaround we have to use:

` **.UnityEditorInterface.targets(125,5): error : Assets\VirtualKeyboard\Scripts\SystemKeybo
ardPlacement.cs(51,149): error CS7069: Reference to type 'SpatialCoordinateSystem' claims it is defined in 'Windows', but it could not be found `

**Comment by Railboy** [comment]
@Kjakubzak Glad to hear it. I can't speak to the other build problem. You may want to open a separate issue.

**Pull request merged**
