### PR TITLE
Fixes double entry in Create Menu

### PR DESCRIPTION
**Pull request by Railboy**
## Overview

- Fixes: #6557

### CODE REVIEW

**Comment by wiwei** [comment]
Possibly a good candidate also for some build time validator (to ensure that we don't have another thing that creates a double menu entry)

Obviously separate change.

**Comment by davidkline-ms** [comment]
@Railboy, can you rebase this change to prerelease/2.2.0_stabilization? If you do not have the time, we can merge here and cherry-pick.

Thanks!

**Comment by Railboy** [comment]
@wiwei I'll also update the service extension wizard so it adds a correct create asset menu attribute.

**Comment by Railboy** [comment]
@davidkline-ms I'd prefer if you cherry-picked since it's such a tiny change.

**Comment by davidkline-ms** [comment]
> I'd prefer if you cherry-picked since it's such a tiny change.

Will do once this passes validation

**Pull request merged**
