### PR TITLE
Updating example scenes

### PR DESCRIPTION
**Pull request by cre8ivepark**
Overview
---
Based on the feedback(#1599  ) from the community and our discussion, I did the first pass for the improvement. This update focuses on UX folder and some input related scenes. I'll continue working with @NeerajW and @keveleigh to identify obsolete scenes and assets.
Thanks!

- Refined design & text readability in some important scenes such as InputManagerTest and MotionControllerTest
- Replaced some obsolete/duplicated materials with FastConfigurable series.
- Started adding a common template for the In-Project scene description. This panel will be included in every example scene so that developers can easily understand what the scene is about before looking at the readme file. 
- Removed Medical example due to the heavy asset size

Some screenshots (before & after):
---
mrtk_examplesupdate1
mrtk_examplesupdate3
mrtk_examplesupdate2

Updated scenes in this PR:
---

- AdaptiveQuality
- Boundary Test
- ColorPicker
- FastConfigurableShader
- GazeRuler
- Input - InputManagerTest
- Input - MotionControllerTest
- MotionControllers-GrabMechanics
- UX - GestureInteractiveExample
- UX - InteractableObjectExample
- UX - InteractiveButtonComponents
- UX - InteractiveElementInstantiate
- UX - InteractiveExample
- UX - LineExamples
- UX - ObjectCollectionExample
- UX - SliderSamples
- UX - TextPrefabSamplesTest

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@cre8ivepark did we test this on both HoloLens and Desktop?

**Comment by cre8ivepark** [comment]
@StephenHodgson I haven't updated any code in this update but yes, I have tested on both HoloLens and immersive headset.

**Comment by cre8ivepark** [comment]
@StephenHodgson Added the list of updated scenes.

**Comment by DDReaper** [comment]
Looks fantastic, will test as soon as I'm able

**Comment by NeerajW** [comment]
@DDReaper I did not merge since you are still partying on that branch :) Please merge when you are ready!

**Comment by DDReaper** [comment]
I completely missed these were being proposed in to the Feature_Namespace branch.  
What's the plan here @NeerajW ?  Are we waiting until all the example scenes are updated prior to merge.

Granted, appreciate removing examplex, as it eases my workload for the upcoming shader rename

**Comment by DDReaper** [comment]
OK, a few comments (from a standards perspective)

- All examples should use the same folder structure, recommend the Unity standard of Scenes, Scripts, etc as subfolders (e.g. adaptive quality has none)
- The Readme file should have a template which each example should adhere to.  E.g. Sections for Title, high level description, use, further reading, etc (must include screenshots of the sample scene) - Grabmechanics is a good example but still needs work as it's cluttered.
 - All scenes should use the same SkyBox (recommend the plain skybox as used in MotionControllersTest as it's cleaner.  But I've noted all currently use the Unity default two tone)
 - Standardise on a color set, no more than four colors.  Else scenes look cluttered or focus on the wrong things. (motion controller test scene is a great example)

I've played with the scenes and they are a great improvement but we need to apply the same standard to everything in the examples.

**Comment by cre8ivepark** [comment]
@DDReaper Thanks! Could you help with the item 1 and 2 (folder structure change + Readme template)? For the item 3 and 4, we will do different PR later, dedicated to the environment/skybox/material.

**Comment by DDReaper** [comment]
It would be easier for you to do Item 1 @cre8ivepark on your current PR.  Just create/check the folders needed for the standard in the examples.
E.g. 
- Adaptive Quality has none (should have Scripts / Scenes)
- Boundary has folders for Scripts / Scenes

Just compare to some of the larger examples for the correct folder names.

I'll try and whip up a good template for the examples and push it to the Feature_NameSpace branch.  Let's Merge your PR once the folders are done, then we can do the rest as new PR's to keep it clean.

Sound OK?

**Comment by cre8ivepark** [comment]
@DDReaper Sounds great!

**Comment by cre8ivepark** [comment]
Updated folder/file structure for the examples based on @DDReaper 's suggestion:
Thanks!
2018-01-29 15_24_01-unity 2017 2 1f1 64bit - windowocclusion unity - mixedrealitytoolkit-unity - u

**Comment by DDReaper** [comment]
rofl, already done, merged and closed :D 
Looks good

**Comment by StephenHodgson** [comment]
If we do `_Readme` then they'll all be at the top.  If it's worth it haha.

**Comment by DDReaper** [comment]
The top level folder in any of the examples should be empty, so it'll always be at the top :P

**Comment by StephenHodgson** [comment]
fixes: #1574

**Comment by StephenHodgson** [comment]
fixes: #1682

**Pull request merged**
