### PR TITLE
Add a default set of profiles that are optimized for getting started with HoloLens2

### PR DESCRIPTION
**Pull request by wiwei**
The default MRTK profile is good at showing off a lot of the features in VR and AR, but has some extra settings that either aren't necessary in AR (teleportation, boundary) or aren't performant (hand mesh visualization). Furthermore, there are also some settings that must be enabled specially in order to use HL2 features (such as Eye Tracking), which should really be set by default.

This copies a subset of the configuration profiles with deltas as follows:

1. Boundary system is disabled.
2. Teleport system is disabled.
3. Spatial awareness system is disabled.
4. Eye tracking provider is added (https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_BasicSetup.html#create-an-eye-gaze-data-provider)
5. Eye simulation is enabled by default (for input simulation).
6. Hand mesh visualization is disabled.
7. Camera profile settings are set to match, so that visual quality in the editor and device will look similar.

#4351 

For reviewers, please comment on where you think this should actually go - I opted not to put it in examples because I felt like for folks who just grab the foundation package, this should also be available to them.

Also if there are other defaults that should be set/updated, let me know.

### CODE REVIEW

**Comment by julenka** [comment]
Should we make this the default profile in HandInteractionExamples scene?

**Comment by sostel** [comment]
> Should we make this the default profile in HandInteractionExamples scene?

Good question. There is a bug that prevents hands and eyes to be used together right now [1]. If this is the default profile and it includes both near and far hand interactions, eye input won't be of much use and we would still need a different profile to use eye tracking. Not sure how we want to address this. Thoughts? 

[1] https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4431

**Comment by davidkline-ms** [comment]
> Spatial awareness system is disabled.

Curious as to why this system is disabled?

**Comment by wiwei** [comment]
> > Should we make this the default profile in HandInteractionExamples scene?
> 
> Good question. There is a bug that prevents hands and eyes to be used together right now [1]. If this is the default profile and it includes both near and far hand interactions, eye input won't be of much use and we would still need a different profile to use eye tracking. Not sure how we want to address this. Thoughts?
> 
> [1] #4431

We should fix that other bug separately, so yeah, I can make the change to swap hand interaction examples to use this as its default profile

**Comment by wiwei** [comment]
> > Spatial awareness system is disabled.
> 
> Curious as to why this system is disabled?

I'm open to bringing it back - some of our other interactables and example scenes also had this disabled. Lemme know what folks want to do here.

**Comment by Cameron-Micka** [comment]
> Spatial awareness system is disabled.
> 
> Curious as to why this system is disabled?
> 
> I'm open to bringing it back - some of our other interactables and example scenes also had this disabled. Lemme know what folks want to do here.

We usually disable the spatial awareness system to avoid the spatial mesh being calculated/rendered/etc.

**Comment by wiwei** [comment]
@julenka @keveleigh I updated the hand interaction examples scene to use the new default HL2 profiles

**Pull request merged**
