### PR TITLE
enabled diagnostics / disabled spatial awareness for default xrsdk config

### PR DESCRIPTION
**Pull request by thalbern**
## Overview
fixes missing profiler in hand interaction scene if you're starting the examples with xr sdk default profile (unity 2019.4)
disabled spatial awareness setting

both flags now match the hl2 profile

### CODE REVIEW

**Comment by davidkline-ms** [comment]
moving to 2.6. we should have matching versions of all default profiles for xrsdk

**Review by wiwei — APPROVED** [review]

**Comment by thalbern** [comment]
@davidkline-ms  should I close this PR and we create a separate xr sdk hl2 profile? or is this good to go into the xr sdk default one?

**Comment by davidkline-ms** [comment]
> @davidkline-ms should I close this PR and we create a separate xr sdk hl2 profile? or is this good to go into the xr sdk default one?

Since this change would cause the two default profiles to differ, it would be great to create a separate xr sdk hl2 profile and make this one match the legacy xr default (enable diags, re-enable spatial)

**Review by davidkline-ms — APPROVED** [review]

**Pull request merged**
