### PR TITLE
Send Slider Value on Update - Stabilization

### PR DESCRIPTION
**Pull request by Gaweph**
Overview
---
Allows for value to be sent when invoking **OnUpdateEvent** method.

Changes
---

Can Specify a method that accepts a float

image

image

Previous behavior works correctly (specifying a method and supplying a value)

image

image

- Fixes: #1760 .

### CODE REVIEW

**Comment by Gaweph** [comment]
Closed old PR: #1761.  Targetting the Stabilization branch as suggested by @DDReaper

**Comment by DDReaper** [comment]
This should be considered the first PR for the next Stabilisation patch release.  Thoughts @davidkline-ms / @StephenHodgson

**Comment by davidkline-ms** [comment]
100% agree, @DDReaper

**Comment by DDReaper** [comment]
Then lets delete Stabilisation now that it's merged, create the new branch from it and retarget this (and any other pending PR's, so we don't lose track.

**Comment by davidkline-ms** [comment]
the stabilization branch has been deleted and a Patch4_Dev branch created for fixes to the next release.

**Pull request merged**
