### PR TITLE
Use local rotation as start value of InteractableRotationTheme's interpolation

### PR DESCRIPTION
**Pull request by Bertrand75014**
## Overview
This PR is following the issue I posted about the the InteractableRotationTheme behaviour. It replaces the usage of world rotation for the start value of the interpolation by local rotation, which seems to be more adapted.  

## Changes
- Fixes: #7080

### CODE REVIEW

**Comment by Bertrand75014** [comment]
Hi @julenka, thanks for the review. I totally understand your point.
Between the 2 solutions you propose, I'd rather go for the first one, adding an option, than having a second _Theme_.
However, if we agree that the current implementation is wrong (start from the world rotation and apply it to the local rotation), it shouldn't be a simple boolean to switch between world and local, because it doesn't really correspond to any of these 2 options. 
In my opinion, it would rather be a popup with values like _Legacy_ (the current one, by default), _World_ and _Local_. Does it makes sense to you ?

**Comment by Troy-Ferrell** [comment]
@Bertrand75014 
Thanks for catching this.

Reading everything thus far, I'd say yes it needs to be fixed but also make it a property. 

There should be two theme properties

Relative Rotation (default = false) [EXISTING]
Local Rotation (default = true) [NEW]

and then use eulerAngles or localAngles based on that check. I'd say make the local rotation true by default as that is closer to the "default" existing behaviour....it just retrieves the wrong value

**Comment by Bertrand75014** [comment]
Hi @Troy-Ferrell, 
The dropdown list I proposed is actually a theme property (like for example the _Color Property_ of the _InteractableColorTheme_), and would not induce a breaking change since the default value will trigger the current behaviour.
Maybe I didn't understand well what you propose, but setting the local rotation true by default will be a breaking change, right ?

**Comment by Troy-Ferrell** [comment]
@Bertrand75014 
So there are two types of properties in the themes (currently poorly named)
1) ThemeProperty  - one value per theme instance
2) ThemeStateProperty - one value per available state in the theme (i.e a color per state)

I was saying add another ThemeProperty in InteractableRotationTheme like the "Relative Rotation" currently there. This property would indicate whether to set hostTransform.localRotation or hostTransform.rotation in `public override void SetValue(ThemeStateProperty property, int index, float percentage)` and likewise based on this property to use hostTransform.localEulerAngles or hostTransform.eulerAngles in `public override ThemePropertyValue GetProperty(ThemeStateProperty property)`

Right now, as you said, we are currently mixing the two by using hostTransform.localRotation but hostTransform.eulerAngles.

**Comment by Troy-Ferrell** [comment]
Closing this out due to #7377

**Pull request closed without merging**
