### PR TITLE
Final merge of dev branch into master, including alternate model loading

### PR DESCRIPTION
**Pull request by keveleigh**
The Dev_Unity_2017.2.0 branch will be retired after this PR to prevent future work from being done in it.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
yeah we should have caught that he submitted to the dev branch. Awe well.

**Comment by keveleigh** [comment]
I caught it but figured it'd be easier to do it myself, since there had been some big changes to this script in master.

**Comment by StephenHodgson** [comment]
Yeah I was tempted to delete that branch too, but wanted to check first if it was okay.

**Comment by keveleigh** [comment]
After this, we should delete it.

**Comment by MsDerekMa** [comment]
Sorry about that. Everything looks good to me.

**Comment by keveleigh** [comment]
@MsDerekMa All good!

**Pull request merged**
