### PR TITLE
Input Simulation camera movespeed and profile adjustment

### PR DESCRIPTION
**Pull request by RogPodge**
Untied the camera movespeed from the frame rate.
Adjusted the camera's movespeed accordingly
Changed the fast control key from Right Ctrl to Right Shift so the user can't accidentally call Ctrl + S

## Changes
- Fixes: #7692

### CODE REVIEW

**Comment by RogPodge** [comment]
> Looks good to me! Might be worth documenting the key (and behavior) change in the release notes.
> To make sure any tracking's updated, was there a specific issue that had reported this?
There wasn't a reported issue it was just something I had noticed while trying to use MRTK. I'll add the change to the release notes

**Comment by wiwei** [comment]
lgtm

**Pull request merged**
