### PR TITLE
Remove Manager.prefab

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Removed the `Manager.prefab`,  Users should be using the `InputManager.prefab`.
Updated the Getting Started docs to reflect this change.

Changes
---
- Fixes: #1341

### CODE REVIEW

**Comment by DDReaper** [comment]
I thought the point of the "Manager" prefab was to introduce a standard way for grouping all managers used by the MRTK?  Why remove it?

**Comment by StephenHodgson** [comment]
Because it duplicates existing prefabs and increases the level of complexity when updating them.

If nested prefabs were supported in Unity, I'd totally be fine with this, but as it stands the Manager.prefab only has the Input Manager, and a duplicate event system.

So every other manager and prefab we add to it will have to be updated as well, whenever one of these prefabs gets changed, and will only cause more overhead when it comes to upkeep.

**Comment by DDReaper** [comment]
Fair enough. Will just need to update guidance and docs until nested Prefabs appear :D

**Comment by StephenHodgson** [comment]
I did.  No scenes are using the Manager.prefab.

**Comment by StephenHodgson** [comment]
Actually I did find a scene.  I also combed though all the scenes and removed any extra EventSystems as well.

**Pull request merged**
