### PR TITLE
[Dev→master] MRTK/Standard shader, update .mat, add test scene

### PR DESCRIPTION
**Pull request by davidkline-ms**
Port MixedRealityToolkit/Standard shader from Dev_Working_Branch, including related editor and runtime scripts.
Update materials that formerly used MixedRealityToolkit/FastConfigurable and Unity's Standard shader to use the MRTK shader.
Add StandardShader example scene from Dev_Working.

### CODE REVIEW

**Comment by cre8ivepark** [comment]
Updated InteractableObject and ObjectCollection example scene with MRTK/Standard shader. 
2018-03-20 15_14_27-unity 2017 2 1p2 64bit - objectcollectionexample unity - johnnew - universal w
2018-03-20 15_13_40-unity 2017 2 1p2 64bit - interactableobjectexample unity - johnnew - universal

**Comment by davidkline-ms** [comment]
Thanks @cre8ivepark! Those look great!

**Comment by StephenHodgson** [comment]
I thought we agreed we weren't putting new features into the master branch?

**Comment by timGerken** [comment]
from the discussion around Simon's YADFS document, summary from David:
>**2.**	Create a new Dev branch for master to work on new features / fixes that our customers need sooner rather than later (SJ Agreed, but I thought that was Patch4 was about.) 
>    **a.**	Define t he key features (BoundingBox, Multi-Pointer) for our next full release out of master (SJ Agreed, but with some reservations)
>    **b.**	Task a few people to cherry-pick from the current dev branch to bring over features that are done and work to complete those that are not (SJ Agreed)

**Comment by SimonDarksideJ** [comment]
Those points are correct @timGerken the main outcome of that discussion surrounded the resources available to work in each area.  @StephenHodgson  and I are wholly focused on vNext at the moment, with support from @keveleigh where possible.
So if @davidkline-ms can spare the resource to patch small items in to master through a route agreed in the release strategy, that is also fine.
Although, I didn't think we had finalised that release strategy doc yet. 

Anyway, this is a subject of discussion best done in slack rather than muddy a PR.

**Comment by StephenHodgson** [comment]
Sounds good guys, just wanted to make sure we were on the same page.

**Comment by StephenHodgson** [comment]
My biggest concern is duplicated or wasted effort.

**Comment by Cameron-Micka** [comment]
Thank you @davidkline-ms  and @cre8ivepark for porting this over! I will pull it down and take a look this afternoon.

**Comment by davidkline-ms** [comment]
@Cameron-Micka, I would be very interested to know if I missed updating or bringing over one or more pieces. It seems to work, but there is always a chance as this was a manual, not Git, cherry-pick.

Dave

**Comment by StephenHodgson** [comment]
Couldn't this module be a standalone package without any other bits of the toolkit? Or do we have dependencies?

**Comment by cre8ivepark** [comment]
@StephenHodgson HolographicButton prefab and some UX components are based on this shader.

**Comment by Cameron-Micka** [comment]
@StephenHodgson This could certainly be a standalone package. Internally we have it in a NuGet package other packages (like our UI ones) include it as a dependency.

**Comment by davidkline-ms** [comment]
@StephenHodgson, this is one of the features that I personally get asked about often. While it is possible, as @Cameron-Micka mentions, to make this a separate package, a great deal of the value here is to get the improved shader and materials out to existing MRTK customers in our next patch release.

**Comment by Cameron-Micka** [comment]
@davidkline-ms I just had a chance to pull down this PR and review it. It looks great sans a few minor things I fixed in clone of your cpStdShader branch: https://github.com/Cameron-Micka/MixedRealityToolkit-Unity/tree/cpStdShader see commit 54b49d3, c090c2a, and 9432b7e. You should be able to pull this branch into yours and it will automatically fast forward you. (Unless there is another way to do this, I'm new to GitHub.)

On a side note, I could also update the shader to changes our team has made since my last PR if this is the right/time and place to do that (it's 100% optional).

**Comment by StephenHodgson** [comment]
@Cameron-Micka so we're waiting for these changes to be merged?

**Comment by Cameron-Micka** [comment]
@StephenHodgson Yes, the above 3 commits should be merged in so this branch is on parity with what is currently in Dev_Working_Branch.

That's also a good point, if we want to take in updated changes to the shader I'll make sure to create a PR for Dev_Working_Branch.

**Comment by davidkline-ms** [comment]
@Cameron-Micka,  I'll take your commits today.
Let's also update the shader. We might as well do one change to Patch4/master rather than two.

**Comment by Cameron-Micka** [comment]
@davidkline-ms Perfect! I just update the shader in my branch, please see commit 8c9a942.

I will also create a PR for Dev_Working_Branch with these changes later today.

**Comment by davidkline-ms** [comment]
Pulled @Cameron-Micka's changes into my branch. Is there anything else left for master?

**Comment by Cameron-Micka** [comment]
@davidkline-ms Looks perfect! I would approve the PR but it looks like I no longer can.

**Comment by davidkline-ms** [comment]
@StephenHodgson, @keveleigh, would you two care to approve on @Cameron-Micka's behalf?

Thanks!

**Pull request merged**
