### PR TITLE
Remove UnityAR from foundation NuGet package

### PR DESCRIPTION
**Pull request by davidkline-ms**
Removes UnityAR from the foundation package and does some packaging cleanup (ex: removing source) for the 2.3 release

### CODE REVIEW

**Comment by keveleigh** [comment]
Looks like there are some conflicts

image

**Comment by davidkline-ms** [comment]
> Looks like there are some conflicts

Knew about those. Working on them now

**Comment by keveleigh** [comment]
I think this is getting caught between the 2.3 and 2.4 version number changes in stabilization. Please merge in the stabilization branch again, which should fix this up.

**Pull request merged**
