### PR TITLE
removed roll from "maintain rotation to user" one hand manipulation mode

### PR DESCRIPTION
**Pull request by thalbern**
manipulation handler one hand manipulation set to maintain rotation to user will now not take roll into account anymore.

## Changes
- Fixes: #4295 

## Verification
tested with WMR headset

### CODE REVIEW

**Comment by wiwei** [comment]
Change looks good - if there's a way to add a simple test for this (i.e. play mode test to ManipulationHandlerTests.cs) that would also be great to get coverage for this behavior.

**Comment by thalbern** [comment]
> Change looks good - if there's a way to add a simple test for this (i.e. play mode test to ManipulationHandlerTests.cs) that would also be great to get coverage for this behavior.

done!

**Pull request merged**
