### PR TITLE
5.6 & 2017.1 Build fixes

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Fixes compatibility with 5.6 & 2017.1 unity builds.

### CODE REVIEW

**Comment by NeerajW** [comment]
Why are we making these changes on a build of Unity that toolkit branch does not support?

**Comment by StephenHodgson** [comment]
It _does_ support it, this fixes that broken support.

**Comment by NeerajW** [comment]
Incorrect. Toolkit is currently on 2017.2.* builds. If you want to be on older versions of Unity please use older packages. We cannot force multitude of files to have these if defs. They are not maintainable, don't work with intellisense and just not something we do with versioning.

**Comment by StephenHodgson** [comment]
Older packages are usually missing bugfixes and improvements from the current releases.

although, I agree that it does add difficulty to maintaining the toolkit.

These backwards compatibility issues shouldn't affect people using the latest versions.

**Comment by NeerajW** [comment]
We decided that once Unity MRTP builds move out of the MRTP mode, we will drop support for older Unity builds and remove IF DEFs for them. So approving based on shiproom notes.

**Pull request merged**
