### PR TITLE
vNEXT: Spatial Mouse Input

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
- Adds Spatial Mouse Input
- Added Setter to `ControllerPoseSynchronizer.Handedness`

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@Cameron-Micka I was having trouble getting a cursor material that renders over everything, could you help me out with that?

**Comment by StephenHodgson** [comment]
This is what I have so far:
image

**Comment by Cameron-Micka** [comment]
@StephenHodgson Your material looks 90% of the way there! The last bit you need is to tell the cursor to "always pass" depth testing. To do that set your Rendering Mode to "Custom" then Depth Test to "Always." Please let me know if this does/doesn't work for you since I haven't pulled down your branch yet.

renderingmode

**Comment by StephenHodgson** [comment]
It worked!

**Comment by StephenHodgson** [comment]
> FYI, when testing in editor, mouse will be trapped in game window, until you press esc key. We may want to call this out in the documentation.

Yup I did that intentionally bc we lock the mouse to the center of the screen so it doesn't wander outside of the game window. Not sure where to add it in docs, but it's a well known Unity Mouse thing.

**Comment by StephenHodgson** [comment]
Let's hold off merging this until @davidkline-ms approves. I'll let him decide if they want it in the internal fork.

**Pull request merged**
