### PR TITLE
Hand Menu example polish

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
- Menu button layout polish.
- Updated options layout in the scene for easier selection.
- No code changes.

2019-09-19 17_47_49-Unity 2018 4 6f1 Personal - HandMenuExample unity - MRTK-Public-Microsoft - Univ
2019-09-19 15_23_36-Unity 2018 4 6f1 Personal - HandBasedMenuExample unity - MRTK-Public-Microsoft -

## Changes
- Fixes: #5164

### CODE REVIEW

**Comment by Troy-Ferrell** [comment]
nit: Should "Show on palm detection" be taken out. Seems redundant since they all do the same thing there

**Comment by cre8ivepark** [comment]
@Troy-Ferrell Good point! I was thinking about the same thing.

**Comment by cre8ivepark** [comment]
@Troy-Ferrell Updated:
2019-09-20 14_18_22-Unity 2018 4 6f1 Personal - HandMenuExample unity - MRTK-Public-Microsoft - Univ

**Pull request merged**
