### PR TITLE
regenerate meta files

### PR DESCRIPTION
**Pull request by davidkline-ms**
Overview
---
Delete and re-create all .meta files in the mrtk_development branch

Changes
---
- Fixes: #2546 .

### CODE REVIEW

**Comment by keveleigh** [comment]
The GUIDs that I spot-checked don't look to have changed. Was that the intention?

**Comment by StephenHodgson** [comment]
I don't see any guid changes in a majority I checked.  Are we sure they were regenerated?

**Comment by davidkline-ms** [comment]
> The GUIDs that I spot-checked don't look to have changed. Was that the intention?
That was not the intention. The steps I took were:
- Close Unity
- Delete all .meta files
- Open Unity
- Expect all meta files to be recreated.

**Comment by davidkline-ms** [comment]
> Are we sure they were regenerated?

Would one of you like to give this a shot... I don't know why mine didn't change

**Comment by keveleigh** [comment]
Unity might be regenerating with the same GUID based on the Library folder?

**Comment by StephenHodgson** [comment]
Probably true. You'll need to close Unity, delete all the meta files, and library, temp folders, and open again.

We'll also need to go back and hook up any missing references on any prefabs, scene objects.

**Comment by davidkline-ms** [comment]
> Unity might be regenerating with the same GUID based on the Library folder?

Grumble...I'll re-clone my repository and try again.

**Comment by davidkline-ms** [comment]
closing to try again with a clean slate

**Pull request closed without merging**
