### PR TITLE
Fixed issues with double click events and see-it/say-it functionality

### PR DESCRIPTION
**Pull request by killerantz**
Overview
Fixed issues with double click events, especially when isGlobal is set. Fixed SeeIt-SayIt functionality, General bug fixes and filled in missing themes and receivers. Expanded custom receiver example in demo scene

Feature Details
 - IsGlobal : When set to true the Interactable registers as a global listener meaning it will get all events from Input manager even if it's not in focus. Use for things like Menu button on the controller or when the Interactable should be triggered by a speech command action. (will trigger with or without focus) MR headsets do not seem to trigger speech commands that are setup in the speech commands profile.

 - VoiceCommand: a way to assign a voice command to an Interactable directly. This feature was not hooked up previously, sorry for the confusion. Add a string to the Voice Command field. Check Requires Gaze if the event should only trigger when the interactable has focus, otherwise it will trigger globally. This feature has nothing to do with the Speech Commands profile. Examples in the demo scene include the Radial One, Radial Two, Radial Three global commands for the radial buttons and Button and Toggle button voice commands for Toggle Button ("Toggle Button") and Holographic Toggle Button ("Button" as the tool tip says). An advanced feature of the VoiceCommands is the ability to add multiple voice commands for toggle buttons or multi-state controls by adding a comma, with no spaces around commas.

 - Receivers: The demo scene has an example of a Component that looks at an Interactable and can contain a list of receivers that extend ReceiverBase. The example shows how to extend receiver base and turn off UnityEvents for custom receivers. The component (InteractableReceiverList) is an example of building a component that can receive updates from an Interactable for custom events. There are two main ways to handle Interactable events with code. 1. Extend ReceiverBase, follow the example in the demo. Now click New Event on the Interactable and choose your custom receiver from the drop-down list. This is the same Pattern for InteractableReceiverList and InteractableReceiver components. 2. Extend RecieveBaserMonoBehavior, This is a component that can listen to an interactable state changes and register as a handler. All receiver types will get OnClick and OnVoiceCommand event calls. OnVoiceCommand events fire using the VoiceCommands field on the Interactable or setting IsGlobal to true and selecting an Input Action that has a keyword setup in the Speech Commands Profile.

Updates
 - Fixed double event firing when an Interactive has IsGlobal set to true.
 - verified consistent functionality on MR Headset and HoloLens.
 - Added texture, material, audio, string (labels) and rotation themes
 - Added an audio OnClick receiver to make it easy to add audio to click events.
 - Removed Layout3D example scene and most of the code. Moved some of the code back into Interactables and the grid list into Collections. A member of our team is working on something that does the same thing better.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
> IsGlobal

maybe `IsFocusRequired`? That's really all that's going on here.

**Comment by killerantz** [comment]
@StephenHodgson "IsFocusRequired ?". That's a good question. IsGlobal registers the interactable to the input system to ignore focus. There's another property that's similar that we should address as well, RequiresGaze, which is a sub property of VoiceCommand. IsGlobal means that the interactable will receive events when not in focus, IsFocusedRequired seems like a practical term for that. RquiresGaze does not follow the pointer, focus pattern, but would be a very similar term, should we make this one VoiceCommandRequiresFocus? There would be a case where interacting with a pointer should require focus, but a voice command does not. The Radial buttons in the Example scene are setup this way and show both properties. I would not want them to be confusing.

**Comment by StephenHodgson** [comment]
See this conversation https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2957

**Comment by killerantz** [comment]
I have pattern working, we just need to make sure the terms are correct and make sense. To get an idea for what all is going on in this interactable, to get everything to work smoothly and allow events for grip and menu to fire correctly, as well as select. There are two systems, one is the input system which I listen to for global events, not select events and speech commands setup in the SpeechCommands profile. For the VoiceCommands that are setup on the Interactable directly by entering a string into the VoiceCommand field, it used it's own keyword recognizer. For the global stuff though, there are issues when the Input System and Pointer System overlap and they over lap differently on the HoloLens compared to MR Headsets. There are some redundancy check that could be optimized with more work, but it's working on both HoloLens and the headsets I tested this weekend.

**Comment by PJBowron** [comment]
@killerantz Hi Todd! Were these the components we discussed last week? Considering adding provision for registering with the input system as a fallback handler as well as (or instead of) a global listener?

**Comment by killerantz** [comment]
@PJBowron , yes, but I haven't added anything for marking an event as used or registering as a fallback. I guess, there's a little of that happening internally to avoid the Pointer and input events causing double OnClick events to be fired.

**Comment by cre8ivepark** [comment]
@killerantz Could you please add a README file for this? I think we can include [your diagrams from the task](https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2607). (add to External\ReadMeImages) 
It would be great if you can include quick summary of script files and recommended usage. (e.g. What is  custom Receivers? How can I use it? What should I do if I want to handle events in the script, not on the inspector panel?)

https://user-images.githubusercontent.com/22085553/37225808-afa6a7cc-238c-11e8-9cc2-fbd5dd7e3656.jpg

https://user-images.githubusercontent.com/22085553/37225790-9e23938e-238c-11e8-81a0-2b48661a3938.jpg

**Comment by StephenHodgson** [comment]
I think we should maybe we should have some meetings (similar to what we're doing with sharing) about the design and implementation of this feature.

**Pull request merged**
