### PR TITLE
[Stabilization 2.6.0] Slate example issues

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
In the HandInteractionExamples scene:

1. UGUI Slate example's UGUI Input Field is squashed and cannot press, cannot invoke keyboard.
- Deleted the UGUI slate example in the scene and replaced it with the prefab
2. UGUI HL2 button example slate's Bounding Box rotation handle behavior shows an unexpected pivot movement.
3. Slate's side rotation handles are hard to grab. It feels the grabbable area is very limited and has offset from the actual handle visual.

## Changes
- Fixes: #9359

## MRC: 1. UGUI Input Field is visible and interactable. 2. UGUI HL2 button example slate's rotation pivot adjusted
https://user-images.githubusercontent.com/13754172/108907991-ac0ec680-75d7-11eb-952d-36d26c0f6ef7.mp4

## MRC: 2. Slate's side rotation handle sizes adjusted
https://user-images.githubusercontent.com/13754172/108908891-b54c6300-75d8-11eb-96b5-eec3575f4ea6.mp4

### CODE REVIEW

**Review by MaxWang-MS — COMMENTED** [review]
These changes overall look good! Is there any chance that you can minimize the changes to the scene file so that the changes there are clearer?

**Comment by cre8ivepark** [comment]
@MaxWang-MS It seems it shows many changes in the scene file since I replaced two slate prefabs

**Review by davidkline-ms — APPROVED** [review]

**Comment by keveleigh** [comment]
I think the scene file was reserialized in a non-2018 version of Unity, which is why it shows so many changes. We'll need to double check that it still works in 2018, in case something like https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9330 has happened

**Comment by cre8ivepark** [comment]
@keveleigh Oh, I used 2018.4.31f1 and avoided 2019 for that reason. I'll double-check with a fresh clone.

**Comment by keveleigh** [comment]
> Oh, I used 2018.4.31f1 and avoided 2019 for that reason. I'll double-check with a fresh clone.

Oh! If it was going from 2019 to 2018 then, maybe we're okay! Apologies for assuming it was the other way around 😅

**Pull request merged**
