### PR TITLE
[MRTK3] Simplify NearMenu and HandMenu prefabs

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
Both NearMenu and HandMenu examples have been updated to canvas. Because canvas-based UIs are flexible and easy to construct menu size variations by simply adding Action Button prefabs inside the container, it doesn't make sense to provide predefined prefab variations anymore. 

- Deleted NearMenu and HandMenu prefab variants
- Updated example scene (unpacked prefabs)

## Changes
- Fixes: #11014 #11015

## Menu examples in the scenes are no longer prefabs.
2022-09-16 14_21_44-MRTKDevTemplate - NearMenuExamples - Universal Windows Platform - Unity 2020 3 3

2022-09-16 14_21_03-MRTKDevTemplate - HandMenuExamples - Universal Windows Platform - Unity 2020 3 3

### CODE REVIEW

**Comment by Zee2** [comment]
@cre8ivepark , might still be a good idea to have one prefab (one for near menu, one for hand menu) that has all of the affordances set up. (Like the grab bar, objmanip, solvers, etc..) Then have a simple sentinel object in the collection that explains that you should add more buttons to expand it? Or something?

**Comment by cre8ivepark** [comment]
> @cre8ivepark , might still be a good idea to have one prefab (one for near menu, one for hand menu) that has all of the affordances set up. (Like the grab bar, objmanip, solvers, etc..) Then have a simple sentinel object in the collection that explains that you should add more buttons to expand it? Or something?

Good idea!

**Comment by cre8ivepark** [comment]
> @cre8ivepark , just checking, are you going to add back the (single) prefabs to this?

Yes! I'll push updates sometime soon.

**Comment by cre8ivepark** [comment]
Working on this but having some issues with canvas not showing proper layout on runtime. Probably I configured something wrong. I might rebuild it from scratch.
NearMenuBase_Canvas

**Comment by cre8ivepark** [comment]
Added NearMenuBase.prefab and HandMenuBase.prefab so that users can easily add additional buttons based on their needs. 

## NearMenuBase Prefab
2022-09-23 17_30_17-MRTKDevTemplate - NearMenuExamples - Universal Windows Platform - Unity 2020 3 3

2022-09-23 17_30_35-MRTKDevTemplate - NearMenuExamples - Universal Windows Platform - Unity 2020 3 3

## HandMenuBase Prefab
2022-09-23 17_42_34-MRTKDevTemplate - HandMenuExamples - Universal Windows Platform - Unity 2020 3 3

**Comment by Zee2** [comment]
Not to be that guy again but it looks like the corner radii are out of whack again :D I can handle it though.

**Comment by Zee2** [comment]
OK, everything should be good to go now.

**Review by davidkline-ms — APPROVED** [review]

**Pull request merged**
