### PR TITLE
Added initial docs for architecture

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Added some stub files for upcoming documentation

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
These need to be filled in to merge.  Can't accept empty docs, so lets keep the PR open till they are complete.

**Comment by StephenHodgson** [comment]
Why not? It's just a template. I'm working on the core docs but it's a lot of stuff.

**Comment by StephenHodgson** [comment]
Also I was planning on doing each area as it's own pr

**Comment by davidkline-ms** [comment]
> These need to be filled in to merge. Can't accept empty docs, so lets keep the PR open till they are complete.

What about merging into a documentation branch? That would allow others to contribute as well (like we are doing for large features)

**Comment by SimonDarksideJ** [comment]
A separate branch would be good, to avoid putting "empty" stuff in the main dev branch

**Comment by StephenHodgson** [comment]
> Need to move spatial docs into their own folder after this... Willing to make the change?

Sure! but I figured I'd make that change when we merge the this back into that branch.

**Comment by davidkline-ms** [comment]
re-targeted to new mrtk_development_documentation branch

**Pull request merged**
