### PR TITLE
Event system fix where the event listeners array was being modified while an event was getting dispatched

### PR DESCRIPTION
**Pull request by keveleigh**
Fix a bug in input system where the event listeners array was being modified while an event was getting dispatched, because of nested dispatch.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Could you explain this one a bit more? I don't understand how there was a nested dispatch?

**Comment by StephenHodgson** [comment]
The change looks good though. I just want to better understand the problem.

**Comment by StephenHodgson** [comment]
Also, this wasn't an input system specific bug since it's the base event system that was modified, just to be clear the Teleport, Boundary, and Input systems are all affected by this.

**Comment by julenka** [comment]
Hi Stephen, here is the example that caused a bug:

A Controller would raise OnInputDown when select button was pressed.
  in the OnInputDown handler for the BaseControllerPointer, the BaseControllerPointer would raise OnPointerDown by calling MixedRealityToolkit.InputSystem.RaisePointerDown

In the first level, something unregistered itself, which caused the list to be modified.

**Comment by StephenHodgson** [comment]
Thanks Julia :)

**Pull request merged**
