### PR TITLE
Eliminate serialization warning message from the input simulation profile

### PR DESCRIPTION
**Pull request by davidkline-ms**
The input simulation service is only valid when running in the editor. However, since it uses a custom profile, it gets deserialized on the target runtime platform as part of loading the mixed reality toolkit profile.

The root cause of the issue was that the profile class was not known by the serializer because the assembly containing it was not in the runtime image. This is likely to be true for other, platform specific extensions and providers (guidance on how to resolve this warning needs documentation).

The solution was to create a types assembly for the input simulation service that is marked as all platforms. This assembly contains the profile and the required data types and is referenced by the other input simulation assemblies.

To avoid a circular asm reference, an interface was created (and located in the new assembly) from which the input simulation service now inherits.

Tested in editor (confirm simulation remains functional) and on device (confirm no serialization warning messages in the debugger)

- Fixes: #3971 .

### CODE REVIEW

**Comment by lukastoenneMS** [comment]
Instead of moving the non-editor-only parts into /Core, would it make sense to make the main InputSimulation assembly platform independent and in turn move the InputSimulationService into a new editor-only sub-assembly "InputSimulation/Service"? Seems that is the only class actually left in the editor part, and a bit more intuitive than nesting a platform independent assembly inside an editor-only one (even though technically they just live side-by-side).

**Comment by davidkline-ms** [comment]
It actually didnt move the non-editor parts into the core it just was a name i picked :) I am good with using a new name for the editor components (in fact, we would potentially merge the inspector assembly and the editor only class into the same assembly.

Thoughts?

**Comment by davidkline-ms** [comment]
@lukastoenneMS, updated the asmdef relationships per our discussion. the nicest thing about this is that we were able to go back to just two assemblies

**Pull request merged**
