### PR TITLE
MRTK vNext v2018.7 release branch refresh

### PR DESCRIPTION
**Pull request by davidkline-ms**
Overview
---
This checkin merges the work performed in mrtk_development into mrtk_release as the 2018.7.0.0 refresh.

Known Issues
---
- When teleporting, the play area visualization does not move with the user
- Automatic controller visualization is not currently working. 
    - Workaround: Add the Mixed Reality Controller Visualizer script to your scene
- Some controller options do not work correctly on OpenVR
- Actual controller models/GLTF support is not currently provided

### CODE REVIEW

**Comment by davidkline-ms** [comment]
If we can get the code review / testing done today, i'll add it to the tag. otherwise, it makes the next tag.... ok?

**Comment by SimonDarksideJ** [comment]
Need to get the open pr's for viz, open vr and shader updates in for this pr, else it's too much rework for adopters.

**Comment by StephenHodgson** [comment]
> Also 2018.7?? When did Unity skip ahead

That's not Unity's release cadence, I think it's ours haha.

**Comment by davidkline-ms** [comment]
> too much rework for adopters

I expect some churn for adopters until we land beta. that is when we will have a truly stable platform

**Comment by davidkline-ms** [comment]
merged per @StephenHodgson's previous approval and his approval of the only fix to be added since.

**Comment by SimonDarksideJ** [comment]
Can we have a more Detailed release doc with this alpha, documenting the issues and possible workarounds.

With the exception of the controller models, which is obvious. 

Also needs a quick start guide.

**Comment by davidkline-ms** [comment]
> Can we have a more Detailed release doc with this alpha, documenting the issues and possible workarounds.

Good idea.  Any volunteers? :)

The [release page](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2018.7.0.0-vNextAlpha) has *some* more details, but not everything that is being requested.

**Pull request merged**
