### PR TITLE
Add editor window and menu item for displaying the current MRTK version

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

For ease of figuring out which MRTK version you're running, this PR adds a menu item and corresponding pop-up to discover it!

image

IMPORTANT: This feature uses the AssemblyInfo.cs files that our CI generates. Therefore, if run from a clone of the repo, it will display `0.0.0.0` instead of any meaningful number.

## Changes
- Fixes: I thought we had an issue for this, but I can't find it...

### CODE REVIEW

**Review by davidkline-ms — APPROVED** [review]

**Comment by keveleigh** [comment]
@davidkline-ms @MaxWang-MS Added this message when we read `0.0.0.0`:

image

**Review by MaxWang-MS — APPROVED** [review]

**Pull request merged**
