### PR TITLE
fix hololens2 style toggle button

### PR DESCRIPTION
**Pull request by gilbdev**
## Overview
due to some changes in serialization, interactables and themes, the Hololens2 style toggle button was broken.

## Changes
- Fixes: #6169

in bold :
image

- didn't manage to add a them for the FrontPlate due to theme switch between selected/deselected state, it's hard to manage to push the frontplate when pressing the button (like a normal button, which has only one hteme with an offset)

- i branched from mrtk-development, so changes may be slightly different if applied to stabilization branch (even with cherrypick), i can redo the PR from there if this is safer 'dunno about all your merge branching policy ^^)

### CODE REVIEW

**Comment by Troy-Ferrell** [comment]
Huh, this isn't broken for me. I'm in the stabilization branch though

image

**Comment by Troy-Ferrell** [comment]
So does the HolographicButtonToggle prefab on stabilization
image

Actually I just pulled latest on mrtk_dev and there is the startDimensionIndex bug #6161 which makes rendering not possible

image

**Comment by gilbdev** [comment]
Hmm strange... i tested on stabilization!
 maybe some wieird stuff going on when i switch branch (mrtk-release => stabilization) or because of mrtk config i have on my project (or any other migration steps i didn't do).

on mrtk_dev i fixed the bug 6161 by hand to be able to fix this one.

i'll give it another try in a couple of hours. from a fresh clone.

**Comment by Troy-Ferrell** [comment]
It is using a FormallySerializedAs. Maybe a bad reload by Unity?

**Comment by gilbdev** [comment]
ok ..still not working. i just don't get it...
cleaned Library folder, tried the right click>Reimport.. nothing.
I still got dimension to 1
maybe the FormallySerializedAs does not take into account how prefab overrides works ?

if i change the Dimension to 2, the file does add another section
```
- target: {fileID: 8779034279059886464, guid: 3f1f46cbecbe08e46a303ccfdb5b498a,
        type: 3}
      propertyPath: dimensions
      value: 2
```
without removing the one with "Dimensions"

the only way i can make it work, is changing "Dimensions" to "dimension" directly in the .prefab fil by editing the text.

question is .. why does it work on your side :p

tested with unity 2018.4.9f1 and tested with unity 2018.4.4f1 on the last revision of 2.1.0_stabilization

**Comment by radicalad** [comment]
I just merged the latest mrtk_development for my open pr #6001 and am no longer able to select the Toggle option in General -> Selection Mode. Additionally I get these errors:

image

**Comment by gilbdev** [comment]
> I just merged the latest mrtk_development for my open pr #6001 and am no longer able to select the Toggle option in General -> Selection Mode. Additionally I get these errors:
> 
> image

this is related to the startDimensionIndex bug which is not fixed on mrtk_dev :p
you can cherrypick a430937127c5c0c10ce877d231e5654c6b0df293 "Fix serialized property name in the inspector that was broken due to property renaming"

**Comment by Troy-Ferrell** [comment]
@gilbdev, when you start clean, if you inspect the prefab file via notepad (without opening up inspector or Unity or anything),it should read "Dimensions: 2" yes? and capital D

Then when opening the prefab/project in Unity, it updates to dimensions: 1 automatically? And try without selecting the prefab and view in inspector. it's interesting if it updates without even the inspector code running

With data we have, it appears Unity is not treaing FormallySerializedAs attribute properly some of the time

**Comment by gilbdev** [comment]
it does read "Dimensions: 2" 

thing is it does not update "D[d]imensions" at all.
- i open the prefab
- it doesn't find any "Dimensions" property to deserialize to (but this is transparent in unity)
- it does fallback the "dimensions" property to the parent prefab which has 1 as value
-if i change the selection mode to 'Toggle' a "dimensions" property is created, but the "Dimensions" one stays.
i may have some unity cache somewhere (apart from Library Folder?)

what i can suggest is having a **Mixed Reality Toolkit > Utilities > Reserialize** 
but even with that, it does not work for this specific prefab (other prefabs are correctly renaming "Dimensions" into "dimensions")
if the Reserialize works on your side, it may be a good idea to submit it for all assets before 2.1 release.

**Comment by cre8ivepark** [comment]
I also experienced this issue before - sometimes, it was resolved when I deleted the Library folder and restart Unity. Just tested with the latest stabilization branch pull but it seems fine. I'll test with David's prerelease packages.

**Comment by cre8ivepark** [comment]
Confirmed. David's prerelease packages has broken toggle button. The Interactalbe is configured as normal Button.
2019-10-02 13_25_01-Unity 2018 4 6f1 Personal - HandInteractionExamples unity - MRTK10Test - PC, Mac

**Comment by cre8ivepark** [comment]
I opened a fresh clone of 2.1.0_stabilization branch and verified the PressableButtonHoloLens2Toggle is configured as regular Button. I think this fix should be applied to the 2.1.0_stabilization branch.
@davidkline-ms I'll test this fix with the stabilization branch.

**Comment by gilbdev** [comment]
@cre8ivepark this fix is probably not the best fix right now, as we figured out the bug was more on the "Dimensions" vs "dimensions" serialization throughout this conversation.
+ this PR does not put the button in the same state as it was (the FrontPlate is not moving anymore)
and if we only change the D=>d by text editing, there is still some bugs with the FrontPlate theme (same behaviour as the gif in the linked bug #6169)

**Comment by cre8ivepark** [comment]
I see. For the stabilization branch, I'll open PR for just restoring the Toggle button state & themes.

**Comment by cre8ivepark** [comment]
Opened #6185 for the stabilization branch.

**Comment by gilbdev** [comment]
closing.
see #6186 for the fix

**Pull request closed without merging**
