### PR TITLE
Fix build for non windows platforms

### PR DESCRIPTION
**Pull request by GAnatoliy**
Overview
---

Using UnityEngine.Windows.Speech namespace prevents build for other platforms than UWP (e.g. iOS).
Platform dependent compilation is used in other places in code, e.g. HoloToolkit.UI.Keyboard.Keyboard

But it is missed in HoloToolkit.Unity.Buttons.CompoundButtonSpeech that prevents build for ios.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@DDReaper was this because of the namespace refactor?

**Comment by keveleigh** [comment]
@StephenHodgson Looks like this is going into master, so unrelated to the refactor. We should probably take this in Stabilization?

**Comment by StephenHodgson** [comment]
Stabilization branch should build to other platforms just fine. I tested it before making it.

**Comment by StephenHodgson** [comment]
If anything, this class needs to use the ISpeechHandler.

**Comment by keveleigh** [comment]
Which platforms did you try? This PR calls out iOS specifically, but I'd imagine a `Windows` namespace would fail to build on any non-Windows platform.

**Comment by StephenHodgson** [comment]
yeah, the appropriate fix is for the class to use the speech input handler.

**Comment by StephenHodgson** [comment]
Ahh maybe that stuff needs to get removed then.  There's no reason to have it.  The source should handle the confidence level and such.

**Comment by StephenHodgson** [comment]
@keveleigh doesn't build for Android either

**Comment by StephenHodgson** [comment]
Also doesn't build for webGL.  Should we support that as well?

**Comment by StephenHodgson** [comment]
@GAnatoliy even with this change, we have a [dependency on glTF which also has issues compiling for iOS.](https://github.com/KhronosGroup/UnityGLTF/issues/97).

**Comment by DDReaper** [comment]
Any reason this change is just removing references and not holding them behind a precompiler flag?

I agree however, if MRTK is to support projects built for other platforms, it will need a much wider review than the changes here.

**Comment by keveleigh** [comment]
@DDReaper it looks like the references were left over from [a conversion from the MRDL](https://github.com/Microsoft/MRDesignLabs_Unity_Tools/blob/master/HUX/Scripts/Buttons/CompoundButtonSpeech.cs) to the Toolkit's `ISpeechHandler`. Of course, now it isn't clear where (if at all) the keyword from the button's text is actually being registered on a recognizer, so I think this might be broken anyway.

**Pull request merged**
