### PR TITLE
Added multiplication operator for MixedRealityPose

### PR DESCRIPTION
**Pull request by hyungilkim**
## Overview
- Added multiplication operator for MixedRealityPose, for convenient pose operations.

### CODE REVIEW

**Comment by wiwei** [comment]
We should probably get a test + doccomments for this as well (i.e. I see that there was a commit to fix the wrong multiplication order, which makes me think that it's easy to forget the right order/get things wrong here).

**Comment by wiwei** [comment]
For these probably just an edit mode test would be best since it's just a really basic unit test

**Comment by hyungilkim** [comment]
@wiwei Thank you for your comment! I added documentation and an edit mode test for the multiplication.

**Comment by wiwei** [comment]
Thanks for adding the test!

**Comment by wiwei** [comment]
And docs!

**Pull request merged**
