### PR TITLE
Fixing Null Reference Exception in SystemKeyboardExample 

### PR DESCRIPTION
**Pull request by Cameron-Micka**
## Overview

When running the HandInteractionExamples the Unity log is spammed with null reference exceptions from the SystemKeyboardExample due to the debug text not being set up in the inspector. This pull request address this by assigning the reference and performing runtime checks.

## Changes
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5501

## Verification

1. Run the HandInteractionExamples on a HoloLens 2.
2. Download the UnityPlayer.log
3. Verify no exceptions from Microsoft.MixedReality.Toolkit.Examples.Demos.SystemKeyboardExample.Update

>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by cre8ivepark** [comment]
@Cameron-Micka @davidkline-ms I think this should be included in the GA branch. However, this PR was based on dev branch. After David's target branch change, I see many unrelated commits from dev branch. We might need a new PR for GA branch.

**Comment by davidkline-ms** [comment]
yes. we should take a separate PR for stabilization, unless we believe the other fixes contained here (from the dev branch) meet the release bar.

**Comment by Cameron-Micka** [comment]
I can make another PR targeting stabilization if that is desirable?

**Pull request merged**
