### PR TITLE
Reserialize metas

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview
This change reserializes our metas via 2018.4. Updating our serialization will help reduce errant, seemingly unrelated changes in both PRs into this project and other projects that consume the MRTK via source / unitypackage.

For the most part, these changes are just the removal of stale `timeCreated` and `licenseType` info, which are no longer included in meta files.

image

## Changes
- Part of #4914

### CODE REVIEW

**Comment by wiwei** [comment]
How did you do this exactly? Do you have a script that might be worth sharing out?

**Comment by wiwei** [comment]
> How did you do this exactly? Do you have a script that might be worth sharing out?

Mostly I ask this because, hey, this is cool, I wanna learn how to do this!

**Comment by keveleigh** [comment]
@wiwei I basically ran the code posted in the issue:

```c#
[MenuItem("Mixed Reality Toolkit/Utilities/Reserialize Prefabs and Scenes")]
private static void ReserializeAll()
{
    var array = GetAssets("t:Prefab t:Scene t:ScriptableObject");
    AssetDatabase.ForceReserializeAssets(array);
}
private static string[] GetAssets(string filter)
{
    string[] allPrefabsGUID = AssetDatabase.FindAssets($"{filter}");

    List<string> allPrefabs = new List<string>();
    foreach (string guid in allPrefabsGUID)
    {
        allPrefabs.Add(AssetDatabase.GUIDToAssetPath(guid));
    }
    return allPrefabs.ToArray();
}
```

I wonder if it's worth, at some point, splitting out some of these "tools that might help with development but aren't directly used in your app" out into their own package / section. The dependency viewer, the shader checker/upgrader, maybe this, input recording?, screenshot utility, etc

**Pull request merged**
