### PR TITLE
Graduate UnityAR camera settings provider

### PR DESCRIPTION
**Pull request by davidkline-ms**
Based on customer feedback seen / received since the Unity AR camera settings provider was originally released as an experimental component (MRTK 2.2), it is ready to graduate.

This change updates the namespace to remove "Experimental".

### CODE REVIEW

**Comment by davidkline-ms** [comment]
Converting to draft while we work through reconciling with XR SDK provider

**Comment by wiwei** [comment]
Given that our stance is that graduating an experimental feature involves adding tests:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/ExperimentalFeatures.html#graduating-experimental-code-into-mrtk-code

I don't think that this is aligned with our own docs.

I don't think that we should be creating future work for ourselves (i.e. "we'll add tests later") because it might not happen going forward (i.e. we get pulled into fixing other things, forget things, etc).

Note that not all things there will be applicable (i.e. example scene is probably just hand interaction example), but we shouldn't defer that work to the future - we have not done the right thing by saying it's been "shipped" when we haven't added the right supporting materials.

**Comment by davidkline-ms** [comment]
> I don't think that we should be creating future work for ourselves

Agreed. Appropriate tests will be added before leaving draft status.

**Pull request closed without merging**
