### PR TITLE
Correction for Dialog documentation

### PR DESCRIPTION
**Pull request by MichaelLykkeStrand**
## Overview
Correction for Dialog documentation.

## Changes
- Example text now reflects the code in the Small dialog example.

### CODE REVIEW

**Review by keveleigh — APPROVED** [review]

**Comment by keveleigh** [comment]
@polar-kev @MaxWang-MS What's the best way to approach docs PRs from now on? Merge them and manually migrate to the new repo?

**Comment by keveleigh** [comment]
ping @polar-kev @MaxWang-MS 

>What's the best way to approach docs PRs from now on? Merge them and manually migrate to the new repo?

**Comment by polar-kev** [comment]
@keveleigh thanks for the ping.

For docs issues and PRs in the future, I think we should point people to make their changes in the new public MRTK docs repo. https://github.com/MicrosoftDocs/mixed-reality

For issues in particular, each page on the new MRTK docs has a Feedback button that opens a github issue for that corresponding page, 
image

I've opened an issue for Dialog https://github.com/MicrosoftDocs/mixed-reality/issues/240

**Comment by polar-kev** [comment]
Thanks for your contribution @MichaelLykkeStrand, this change has been made in the new MRTK docs repo so this PR can be closed (see MicrosoftDocs/mixed-reality#240). 

Moving forward, feel free to continue making contributions to the new MRTK docs website [aka.ms/mrtkdocs](https://aka.ms/mrtkdocs) via https://github.com/MicrosoftDocs/mixed-reality
 
 fyi: @keveleigh

**Pull request closed without merging**
