### PR TITLE
Events added to TapToPlace

### PR DESCRIPTION
**Pull request by stevenjt**
OnStartedPlacing and OnStoppedPlacing events added to TapToPlace

PR for #1221

### CODE REVIEW

**Comment by stevenjt** [comment]
I've been looking through the existing event systems and documentation to determine a plan for how best to implement these placement events using an interface. Does the following fit with the current approach to event systems in the toolkit?

1) Create a PlacementManager following the conventions set by the other exiting managers in HoloToolkit/Input/Scripts/Utilities/Managers. Alternatively adding the functionality to the InputManager could be an option, but it seems that is more for events resulting from direct user input so I don't think placement events would be suitable there?
2) Modify TapToPlace to register with the PlacementManager, and then call the manager at appropriate times for events.
3) Create a new interface IPlacementHandler which contains OnPlacingStarted and OnPlacingCompleted signatures.
4) PlacementManager will call any components on the GameObject which the placement events originated from that use the IPlacementHandler interface.

**Comment by StephenHodgson** [comment]
Any update to this?

**Comment by stevenjt** [comment]
I'm not currently working on this and I'm not sure when I will have the time to return to it.

I will open a new PR if I do get back to it in the future and similar functionality has not already been implemented by then.

**Comment by joaocpaiva** [comment]
I also needed this functionality in my app and used events as workaround. 

@StephenHodgson can you elaborate on your proposed solution using event routing? Maybe I will find some time to create a PR that addresses it.

**Pull request closed without merging**
