### PR TITLE
 Reduce MRTK path lengths by 15 characters (#6985)

### PR DESCRIPTION
**Pull request by davidkline-ms**
This change renames MixedRealityToolkit[.*] folders to MRTK[.*] to reduce path lengths by 15 characters. MixedRealityTookit.Generated is _not_ renamed as customers may have custom profiles located there and the desire is to not cause unneeded source management churn.

As part of this change, the paths contained within the test collateral has been updated,

PLEASE NOTE: This change touches nearly every file in the MRTK. The _vast_ majority of which are renames only.

Fixes: #6985

### CODE REVIEW

**Comment by davidkline-ms** [comment]
@Troy-Ferrell, this commit fixed links in the documentation. Are there more references that i missed?

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7409/commits/2a812e8770ea00479fb56be4d6c32a3f620f4edd

**Comment by keveleigh** [comment]
Re: the changes @thalbern is seeing

Proposal: Can we split this into several PRs? First, update the tests to read from the MRTK files helper classes, then update each of these folders one at a time? Would help with the reviewing process and prevent possible mis-merges, like what I think Bernadette's seeing (those errors are coming from a new test that looks like it's merged into the old folder structure instead of the new one).

It also might help if we try to reduce our PR backlog a bit before renaming the folders, since this PR will likely break them all. I know that's a bit of a loftier goal, but I think it'd be best in the long run.

**Comment by Troy-Ferrell** [comment]
> @Troy-Ferrell, this commit fixed links in the documentation. Are there more references that i missed?
> 
> [2a812e8](https://github.com/microsoft/MixedRealityToolkit-Unity/commit/2a812e8770ea00479fb56be4d6c32a3f620f4edd)

@davidkline-ms 
Unfortunately, no there are way more references. Looking at that commit, there were only two changes. Look at README_Solver.md as an example and find references like below. Lots of code references and "hey there is an example scene here"

"MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/"

"https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes"

Searching "MixedRealityToolkit." in VS Code
vscode

@keveleigh breaking up this into multiple PRs is a good idea....I only want to point out that since almost every file is touched, after multiple PRs when the final change is ready for MRTK_development, one will just have to carefully review any stragglers that were recently ingested into MRTK_Dev separately in that time frame

**Comment by davidkline-ms** [comment]
> Proposal: Can we split this into several PRs? First, update the tests to read from the MRTK files helper classes, then update each of these folders one at a time? 

I can do that! Closing

**Pull request closed without merging**
