### PR TITLE
Re-enable Sharing with UNET

### LINKED ISSUE #2276: "Sharing with UNET" example - Anchor isn't shared with Client
## Overview
When testing the Hololens Example "Sharing with UNET"  with two Hololenses the Anchor isn't shared from the Server "Lens" to the Client "Lens".

## Expected Behavior
One Device starts a Session, second one joins the Session, both Devices can "fire" Balls, see the moving remote "Head" and the Debug-Button (Anchor) at synced Positions.

## Actual Behavior
One Device starts a Session, second one joins the Session, both Devices can "fire" Balls, see the moving remote "Head"and the Debug-Button (Anchor) at different  Positions.
When we look into der Debug Output we notice the following Message right after tapping the "Reset Anchor" Text: 

"This script is not intended to be run from the Unity Editor" -  (MixedRealityToolkit-Unity/Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/GenericNetworkTransmitter.cs Line 132)

Further Clicks at "Reset Anchor" Text show that the "recived" Ancher was empty and a download of the new Anchor was requested.

## Steps to reproduce
https://github.com/Microsoft/MixedRealityToolkit-Unity

## Unity Editor Version
2017.4.4.f1

## Mixed Reality Toolkit Release Version
2017.4.0.0

### LINKED ISSUE #2303: Hololens Unet client places anchor at headset position
## Overview

After a hololens starts to host and place corectly an anchor somewhere in the room. When a second hololens connects to the first one with Unet, it succesfully gets the server anchor (with the good id) but the anchor is placed at the headset position when the app connected. Note that all shared holograms and player controllers are well placed relatively to this anchor so all the scene is incorect of only one translation. Debug panel show nothing special except anchor set to true.

## Expected Behavior

The client should place the anchor at the same real position than the server.

## Actual Behavior

The client place the anchor at its headset position one second after connected to the server

## Steps to reproduce

Here a summary of what contains ma scene:
SpatialGameObject <SpatialMappingObserver, SpatialMappingManager>
UIContainer (prefab with UNET UI from MRTK)
NetworkGameObject <NetworkManager,NetworkDiscoveryWithAnchors,GenericNetworkTransmitter,WordlAnchorManager>
SharedCollectionGameObject <SharedCollection,SceneContentAdjuster>
UNetAnchorManager <NetworkIdentity,UNetAnchorManager>

## Unity Editor Version

2018.1.2f1

## Mixed Reality Toolkit Release Version

2017.4.0.0

Thank you very much for your help

### PR DESCRIPTION
**Pull request by keveleigh**
Overview
---
Updates some `#if`s from #2127 to run on all build configurations except the intended IL2CPP && .NET Standard 2.0. This was blocking Sharing with UNET from working.

This also contains some minor changes to the scene to bring it up-to-date with the latest components.

Changes
---
- Fixes #2276, fixes #2303

### CODE REVIEW

**Comment by davidkline-ms** [comment]
Were there any references to files in Examples? I had thought that was part of the reason for moving it....

**Comment by StephenHodgson** [comment]
Did this pass all the build types?

**Comment by keveleigh** [comment]
@StephenHodgson 
>Did this pass all the build types?
>Both IL2CPP and NET?
>Both 4.x and Standard 2.0?

I just rebuilt the Toolkit in all four configurations, and all four built successfully.

**Comment by gzpUnreal** [comment]
Yes, I do like to have this. Thanks a lot.

**Comment by davidkline-ms** [comment]
@isufraz, We will be targeting a new release from master approximately mid-July.

Thanks!

**Comment by gzpUnreal** [comment]
Thank you. 

Best,

Zhenping Guo
 

    On ‎Friday‎, ‎July‎ ‎6‎, ‎2018‎ ‎12‎:‎21‎:‎03‎ ‎AM‎ ‎CST, David Kline <notifications@github.com> wrote:  
 
 
@isufraz, We will be targeting a new release from master approximately mid-July.

Thanks!

**Pull request merged**
