### PR TITLE
Allow extension of MixedRealityInputSystem

### PR DESCRIPTION
**Pull request by provencher**
Overview
---
- MixedRealityInputSystem was not extensible, as methods were not virtual.
- Simply converted all public void methods to be virtual, to make it easier to extend the class without duplicating it.

Changes
---
- Fixes: # .

### CODE REVIEW

**Comment by Railboy** [comment]
@SimonDarksideJ @StephenHodgson Are there objections due to performance concerns? This may be a good opportunity to establish some performance testing standards.

**Comment by provencher** [comment]
I rebased the change on the latest development branch, as an api change caused a code conflict

**Comment by StephenHodgson** [comment]
@provencher why not just make a copy and modify what you need and register your custom implementation with the configuration profile?

That's essentially why we created it, so you wouldn't have to extend what was already there.

**Comment by provencher** [comment]
Copying the script is messy and also prone to breaking when the MixedRealityInputSystem is changed. I'd rather extend the public functions to simply add the behavior I need.

For my purposes, I simply need to catch the inputs as they're fired from the platform, to forward them through my codebase. I don't need to change what the core script is doing beyond that.

**Comment by StephenHodgson** [comment]
Makes sense. Maybe when the code is more stable then.

**Comment by provencher** [comment]
It seems this change was reverted in PR https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3847

I understand that the performance costs were undesirable for the default user, and respect that perspective.

However, what about maintaining an extensible version of the script, alongside the more performant non-extensible version? Folks making changes to the script would have to apply it to both for a PR to be merged, and it would grant the flexibility offered by this change, without causing default users to suffer performance costs.

Moreover, this would ensure that a privately maintained copy wouldn't be left behind by rapid changes.

I think this principle could apply to many of the important classes used by the profiles.

**Comment by StephenHodgson** [comment]
Instead of having another copy, is there anything we can do to update the class to better achieve your goal?

Is there something missing from these methods we should be adding?

**Comment by provencher** [comment]
The missing functionality is the ability to catch inputs as they're received by the base class, in order to forward them to other systems before they're discarded.

Currently event handlers process the inputs, but there is no way to hook into that pipeline without adding an event handler to the stack.

**Comment by StephenHodgson** [comment]
I think you could inherit from the base class and override the `HandleEvent` method. 

That's really where the routing takes place, and that method is already virtual.

**Comment by provencher** [comment]
Looking at that method, it's hard for me to gather context about what's happening at the moment the function is called. How can you tell what input raised the event from within an inherited generic HandleEvent override?

**Comment by StephenHodgson** [comment]
You can validate the event data with the type you're expecting. (each of the input event delegates actually do this each time before actually calling the interface method)

```
var baseInputEventData = ExecuteEvents.ValidateEventData<BaseInputEventData>(eventData);

// and to find the input source that raised it:

baseInputEventData.InputSource
```

Once you have the input source you can pretty much get anything you want out of it.

**Comment by provencher** [comment]
I'm surprised that validation method is considered performant enough by the standards that reverted this PR to be honest.

image

I had no idea every event was casted every time it passed through to ensure safety. 

So the solution for me is to add a switch statement that casts the event to every time possible until it hits the type I'm looking for?

**Comment by provencher** [comment]
On another note, @wiwei, would it be possible to get some performance metrics showing the performance hit of virtualizing the functions, given that you reverted the change?

**Comment by StephenHodgson** [comment]
You're right, it probably doesn't need to be validated all the time. Mainly left it in there for people who tried to do something they shouldn't.

**Comment by davidkline-ms** [comment]
Some context around the decision to revert:

(from @andreiborodin) "There are pieces of code that must execute regardless if extension forgets to call base or not; and in those cases we could allow for empty virtual method that are called.

So, MRTK.DoSomethingImportant() can include a call to an empty virtual method OnDoingSomethingImportant() to enable extension but prevent overriding/replacing DoSomethingImportant code."

We are doing some investigation and will work with @provencher and others to land on a good solution.

**Pull request merged**
