### PR TITLE
Final merge of Stabilization into master

### PR DESCRIPTION
**Pull request by keveleigh**
Some PRs have gone into Stabilization after the release.

We should mark the patch release after this, then delete Stabilization.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
What about fixes that the community wants in like #1799

**Comment by keveleigh** [comment]
Fixes can go into Dev for the next release, exactly like we've been doing it, right?

**Comment by StephenHodgson** [comment]
Exactly. We're going to need something that doesn't have the namespace changes.

Everything after the namespace change is technically vNEXT.

**Comment by keveleigh** [comment]
> Everything after the namespace change is technically vNEXT

That feels wrong to me. The dev branch is already 215 commits ahead of master. What's our plan for those, if not a final (or more than one, since we're talking a several month timeline here) release out of master before we migrate to true vNext?

**Comment by StephenHodgson** [comment]
Dev branch != Master because of the namespace changes. They'll never merge again.

**Comment by davidkline-ms** [comment]
It seems to me that we need a dev branch for master and one for vNext... Should we consider re-parenting dev and creating a new one for master?

**Comment by StephenHodgson** [comment]
Right, we've got stabilization for master.

The current dev branch is not going to be compatible with either the master nor vNEXT, so I'm not sure reparenting is even possible.

**Comment by davidkline-ms** [comment]
We could rename dev and lock it. Then we can create a new dev for master and one for vNext.
Thoughts?

**Comment by StephenHodgson** [comment]
@DDReaper thoughts?

**Comment by davidkline-ms** [comment]
I would also like to protect the vNext branch like we do with master. this would be part of the "create a dev branch for vNext").

**Comment by StephenHodgson** [comment]
I'd recommend going ahead and locking it down.

**Comment by davidkline-ms** [comment]
@StephenHodgson, consider it done :)

**Comment by DDReaper** [comment]
I see no reason to rename Dev at the moment, it is what it is, a "Development working branch" where we are testing new features and experiments.  Dev will never (at this point) be merged back in to master.

From the Shiproom call, we agreed.

1. Master is frozen and will only receive patch fixes through a "Stabilisation" branch.  
2. Each Stabilisation branch after being merged with master will be deleted and then a new Branch based of master will be created for any further patches.
3. Dev_working is a highly experimental branch, only for testing.
4. vNext will eventually be the next Master and is a "Future" branch for the moment.

That is what I thought we agreed and drew up in the last meeting

**Comment by davidkline-ms** [comment]
@DDReaper, that's in line with my recollection as well. It does seem that we need a branch off of vNext since it is now protected.

**Comment by StephenHodgson** [comment]
I suggest vNEXT-Development or something along those lines.

**Comment by keveleigh** [comment]
I have a few questions that I don't believe have been addressed here, and this conversation doesn't align with my understanding of our recent plan.

1. The dev branch is already 215 commits ahead of master. What's our plan for those?
2. If the namespace change effectively disconnected the dev branch from master, yet vNext is starting from scratch, what was the point of doing the namespace refactor in the dev branch?
3. On a similar note: "Master is frozen and will only receive patch fixes". Where do I put new features between now and when vNext ships? Right now, the vNext branch doesn't have anything for me to build off, yet dev/master is locked for any future release.

**Comment by StephenHodgson** [comment]
> The dev branch is already 215 commits ahead of master. What's our plan for those?

Most of those are new features like the two handed and bounding box changes.
It's up to you guys if you want to see this come to the master.

> If the namespace change effectively disconnected the dev branch from master, yet vNext is starting from scratch, what was the point of doing the namespace refactor in the dev branch?

Yeah it kinda did defeat the purpose of the namespace refactor to start from scratch with vNEXT.

> Where do I put new features between now and when vNext ships? Right now, the vNext branch doesn't have anything for me to build off, yet dev/master is locked for any future release.

`Dev_Working_Branch`

**Comment by keveleigh** [comment]
I guess my third question was more "Where do I put new features [that I want to see ship in a Toolkit release]?" It's been said that `Dev_Working_Branch` won't ship anymore and is now experimental and only for testing.

**Comment by StephenHodgson** [comment]
Most of the stuff in Dev_Working_Branch will be migrated over to vNEXT as we go though each feature area and cherry pick what's good, and rewrite what's needed.

**Comment by davidkline-ms** [comment]
vNext-Development branch created off of MRTK-Version-Next. we can now start migrating from Dev_Working_Branch.

**Comment by keveleigh** [comment]
What's the benefit to cherry picking certain things (which can result in unknowingly leaving features or functionality behind) vs starting from the dev branch and rewriting piece-by-piece where needed, leaving the "good" things as-is?

**Comment by davidkline-ms** [comment]
@keveleigh, that's a good question.

**Comment by StephenHodgson** [comment]
The way I was thinking about it was so we can actively go through each feature and check them off as we go along.

**Pull request merged**
