### PR TITLE
Update some asmdefs to Unity 2019 version for UPM packaging

### PR DESCRIPTION
**Pull request by MaxWang-MS**
## Overview
Currently amdefs are checked in at Unity 2018 version. This creates problems for UPM packaging because those packages are consumed in Unity 2019, which will lead to some automated asmdef configurator to try to modify certain content (i.e. ver. 2018 asmefs) of the supposedly immutable the package. To solve the problem, we are now checking in ver. 2019 asmdefs. Those files are backward compatible until Unity 2018.4.13f1, beyond which the user must manually perform a few straight forward steps to make them compatible. Documentations will be added in this PR to show the change. Some automatic configurator are therefore removed.

Note: Users on Unity versions earlier than 2018.4.13f1 must revert the changes made to asmdefs when upgrading to Unity 2019, which will also be mentioned in the docs.

## Changes
- Fixes: #8574.

### CODE REVIEW

**Review by davidkline-ms — APPROVED** [review]

**Comment by davidkline-ms** [comment]
@MaxWang-MS , can you resolve the documentation merge conflict? thx!

**Review by keveleigh — COMMENTED** [review]
Are there any changes needed for the Leap Motion and Oculus asmdefs? I think there are some references their configuration checkers add when the corresponding SDKs are installed.

**Comment by MaxWang-MS** [comment]
> Are there any changes needed for the Leap Motion and Oculus asmdefs? I think there are some references their configuration checkers add when the corresponding SDKs are installed.

As discussed offline asmdefs related to those two devices will be handled separately.

**Pull request merged**
