### PR TITLE
rename Fitbox to ContentStartPositionModal and fix bug (PR)

### PR DESCRIPTION
**Pull request by fogbridgegit**
Overview
---
rename Fitbox to ContentStartPositionModal and fixed bug
improved the test example

Changes
---
- Fixes: # .

### CODE REVIEW

**Comment by fogbridgegit** [comment]
ok i renamed ContentStartPositionModal to ContenStartPosition

**Comment by DDReaper** [comment]
Please close this PR and add the updates to the existing #1623 PR

**Comment by DDReaper** [comment]
Any update on the progress of closing this PR and putting the changes in the original PR @fogbridgegit ?

**Comment by DDReaper** [comment]
Closing this as it is effectively a duplicate of #1623
All the changes are also in that PR.
This is also against the wrong branch.

**Pull request closed without merging**
