### PR TITLE
Fixes for the button iconset inspectors

### PR DESCRIPTION
**Pull request by RogPodge**
## Overview
Fixes the button icon set inpsectors in two ways.

1. no longer throws errors due to cascading EditorFoldoutGroups
image

2. Exceptions no longer thrown when preview textures aren't able to be displayed. Instead, the button config inspector displays appropriate warnings and N/A when the previews can't load
image

## Changes
- Fixes: #9458, #9557

### CODE REVIEW

**Review by keveleigh — APPROVED** [review]

**Review by foteiniSal — COMMENTED** [review]
Amazing! thank you ! it works fine in Unity 2020.3.12f1

**Comment by shahinfir** [comment]
Icon sets still throws errors due to cascading EditorFoldoutGroups in 
MRTK 2.7.2
Unity 2020.3.14f1

**Comment by RogPodge** [comment]
> @RogPodge
> Icon sets still throws errors due to cascading EditorFoldoutGroups in
> MRTK 2.7.2
> Unity 2020.3.14f1

Unfortunately this PR wasn't included in the 2.7.2 release (it barely missed the window).  We'll be sure to get it in for the next one :)

**Pull request merged**
