### PR TITLE
Fixed issue where SetSelection was not triggering an update to the ra…

### PR DESCRIPTION
**Pull request by killerantz**
…dial colleciton.

## Overview
There were changed in Interactable that effects how this script changes which radial button is selected. InteractableToggleColleciton.SetSelection(index) used to call into Interactable's pointer click event, but some of the checks do not allow this call to pass, execute a click and call back to the InteractableToggleCollection to set the new selected index.

This fix just brute forces the visual state change without triggering any onClick events in the interactable, which is I think is preferred.

## Changes
- Fixes: #4331  .

### CODE REVIEW

**Comment by julenka** [comment]
@killerantz, we are trying to ensure that each PR has an issue assigned to it, could you please create or reference and issue for this bug?

**Comment by killerantz** [comment]
Issue #4331, I put it in the Fixes section.

**Comment by keveleigh** [comment]
@killerantz was this meant to be closed without merging?

**Comment by killerantz** [comment]
Sorry, it should be merged. I thought the close option was for the comment not the PR.

**Pull request merged**
