### PR TITLE
Inspector should be created on interface, not concrete class

### PR DESCRIPTION
**Pull request by LocalJoost**
## Overview
Inspectors were created on the concrete class in stead of the interface. In stead of creating it on
[MixedRealityServiceInspector(typeof(MyNewService))]
It should be created on 
[MixedRealityServiceInspector(typeof(**I**MyNewService))]

## Changes
- Fixes: 
ExtensionInspectorTemplate.txt now references #INTERFACE_NAME# in stead of #SERVICE_NAME#

### CODE REVIEW

**Comment by wiwei** [comment]
@LocalJoost, thanks for this PR as well :)

Can you also retarget this one to mrtk_development (i.e. instead of stabilization?). I can't retarget things in the github UI without pulling in all of the stuff from stabilization, which, as of this very instant, isn't what we want to do.

**Comment by LocalJoost** [comment]
Shall I create a new PR with both of these changes in it? May be easier for you. After all, it’s all peanuts changes

Joost van Schaik

Windows Development MVP & Windows Insider MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by davidkline-ms** [comment]
> Shall I create a new PR with both of these changes in it? May be easier for you. After all, it’s all peanuts changes

That would be greatly appreciated. Please note that @andreiborodin has been making packaging changes and they may already be in the development branch. 

Thanks!

**Comment by LocalJoost** [comment]
Created a new PR. Rebasing the old ones gave me all kinds of issues. Want me to withdraw the old ones?

Joost van Schaik

Windows Development MVP & Windows Insider MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Pull request closed without merging**
