### PR TITLE
Add clarification to eye tracking example scenes

### PR DESCRIPTION
**Pull request by sostel**
## Overview
Added some info text to the ET sample scenes that are loaded additively. Some developers were confused by the missing camera and MRTK components.

## Changes
- Addresses issue #4496 - MRTK currently relies on additive scene loading, so setting up each scene as a standalone scene is currently not possible if we want to enable the user to switch between them.

image

### CODE REVIEW

**Comment by wiwei** [comment]
Dannnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnng that's good

**Comment by julenka** [comment]
Can you update the title of the PR?

**Comment by julenka** [comment]
> Can you update the title of the PR?

Oh nevermind, I get how you're doing the naming: Patch and then bug number.

**Comment by sostel** [comment]
> > Can you update the title of the PR?
> 
> Oh nevermind, I get how you're doing the naming: Patch and then bug number.

Yeah, it's confusing. Sorry! But yep, you got it :)

**Comment by julenka** [comment]
@Railboy will your new scene system help with this problem at all?

**Comment by wiwei** [comment]
Changed the title of the PR to reflect what it addresses

**Comment by sostel** [comment]
Thanks for merging this, @Yoyozilla! :)

**Pull request merged**
