### PR TITLE
[Docs] Landing page & docs left navigation improvements

### PR DESCRIPTION
**Pull request by cre8ivepark**
### Landing page
- Updated landing page's **Feature Areas** section. Now each feature links to the corresponding page in the documentation portal.
- Added entry to important features such as **Profiles**, **In-Editor Simulation**, **Multi-Scene Manager(Scene System), and Experimental features**.
- Added clear entry to the **Getting Started** and **Documentation** portal.
### Docs portal left navigation menu
- Reduced unnecessary hierarchy in the Documentation page's left nav pane which makes a lot of important pages hidden in default. Since we have enough vertical space, it would be better to reduce the hierarchy, click count and expose the pages. 
- Removed **About MRTK** menu which only contained **Authors** page. Moved **Authors** menu down to the bottom of the left nav. 
- Added missing nav menus for these pages: **Scene System**, **Profile configuration**, **MRTK Standard Shader**

## Preview link
https://github.com/cre8ivepark/MixedRealityToolkit-Unity/tree/mrtk_development_DocsUpdates

2019-06-17 15_53_35-cre8ivepark_MixedRealityToolkit-Unity at mrtk_development_DocsUpdates

## Changes
- Fixes: #4916 #4814 #4779 Part of #4792

## Branch
This change is based on the **mrtk_development** branch

### CODE REVIEW

**Comment by Railboy** [comment]
This is a huge improvement, especially the icon links. Awesome work!

**Comment by cre8ivepark** [comment]
Cleaned up the navigation hierarchy. For all menus with sub-items, removed the link to the page and created XXX Overview page under it to make the topic always get expanded on click.
2019-06-18 12_44_53-Microsoft Edge

**Pull request merged**
