### PR TITLE
Removed a warning when the radial dot is set to inactive

### PR DESCRIPTION
**Pull request by killerantz**
Overview
When a radial button's selected state is off, the radialDot gameObject is set to inactive. When this happens the widget on the gameObject removes itself from the list of widgets in the Interactive and causes the warning. This is expected behavior, when a gameObject with a widget should not receive updates from Interactive.

Changes
Moved the widget from the RadialDot to another gameObject (Outline) that does not become inactive.
- Fixes: #1857.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Oh, this shouldn't have gone into the master branch.

**Comment by StephenHodgson** [comment]
@killerantz please be sure to target patch branches next time please.

**Comment by killerantz** [comment]
sorry about that, it's been a while.

**Comment by killerantz** [comment]
can you revert or rollback?

**Comment by StephenHodgson** [comment]
Nah, it's fine.

**Pull request merged**
