### PR TITLE
Feature namespace refactor merge to Dev_Working

### PR DESCRIPTION
**Pull request by DDReaper**
Overview
---
Merge of Refactoring work in to Dev_Master

Changes
---
 - EVERYTHING!

### CODE REVIEW

**Comment by NeerajW** [comment]
@DDReaper suggestions on how to code review this? 5000+ files :)

**Comment by DDReaper** [comment]
Lol, we don't @NeerajW 
All the code reviews were done through the building of the Feature Branch.  This is just now moving the work in to Dev_Working.

**Comment by cre8ivepark** [comment]
@NeerajW @DDReaper I have updated the screenshots on the landing page. I found missing materials in the ObjectCollection scene. Just assigned the materials.

Before & After:
mrtk_exampleslanding_beforeandafter

**Comment by StephenHodgson** [comment]
Looks good, but we're going to wait to merge until we've got a release.

**Comment by StephenHodgson** [comment]
@DDReaper I'll open PRs directly against your branch when we merge in the other dev stuff.

**Pull request merged**
