### PR TITLE
MRTK Asset Cleanup

### LINKED ISSUE #1345: Assertion failed: Removing Assets/HoloToolkit/UX/Resources/Models/Cursor/Cursor_move/CursorRing.fbm/templates because the asset does not exist
## Overview
When opening the MRTK MASTER branch for the first time, the following error appears:
```
Assertion failed: Removing 
Assets/HoloToolkit/UX/Resources/Models/Cursor/Cursor_move/CursorRing.fbm/templates because the asset does not exist
```

## Expected Behavior
No errors when opening project.

## Actual Behavior
```
Assertion failed: Removing Assets/HoloToolkit/UX/Resources/Models/Cursor/Cursor_move/CursorRing.fbm/templates because the asset does not exist
```
Is displayed in the console on startup.

## Unity Editor Version
MRTP4

## Mixed Reality Toolkit Release Version
MASTER

### LINKED ISSUE #1404: Update ignore file to exclude UnityPackageManager
## Overview
The file manifest.json file is a nuisance that sneaks into commits constantly.

Since we have no immediate plans for using the Package Manager, should we add UnityPackageManager to our .gitignore?

## Unity Editor Version
2017.2.0p1 MRTP4

### LINKED ISSUE #1405: EditorPrefsUtility's filename does not match the class name
## Overview
EditorPrefsUtility should match it's file name

## Mixed Reality Toolkit Release Version
2c59d07b574cbde904b7ad6bd2e249438597440d

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
- Added ThirdParty to the list of ignored folders so devs can import custom tools
- Updated all .fbx assets import options.
    - Disabled import blend shapes
    - Turned off material imports
    - Turned off animation imports if no animation
    - Re-Exported CursorRing.fbx and removed embedded templates folder
    - Re-Exported hololens_low.fbx and removed embedded dds texture

Changes
---
- Fixes: #1347
- Fixes #1345 
- Fixes #1405 
- Fixes #1404

### CODE REVIEW

**Comment by StephenHodgson** [comment]
>Generally speaking, I'm for Git LFS. Will it make this PR a breaking change?

Good catch, added label.

>Why are there some script folder moves in this PR?

Because the assets do not follow the correct asset organization pattern found in the rest of the project.

- Feature Folder
    - Prefabs
    - Materials
    - Models
    - Scripts
    - Textures

**Comment by NeerajW** [comment]
Can we make this Git LFS migration easier for folks? I have also considered this in the past but did not find anything super useful.

**Comment by NeerajW** [comment]
We are holding off on this PR until we learn more about the side effects of git LFS.
If you would like to separate them out and issue a new PR for asset cleanup, that can be done sooner.

Based on shiproom discussion.

**Comment by StephenHodgson** [comment]
Instead of blocking, I'll just remove the LFS support

**Comment by StephenHodgson** [comment]
Some of the Namespace fixes might break people's apps.

**Comment by StephenHodgson** [comment]
It was just the git lfs stuff that had the breaking changes.  Removed the label

**Pull request merged**
