### PR TITLE
Updated Teleport logic for HoloLens & Floor Offset in WMR

### LINKED ISSUE #1084: Start placement of MixedRealityCameraParent is floating??
Seen this on / off in the project through the various merges / updates.  However, it's currently stuck in the project.

Replication Steps:
* Create afresh clone of the Repo to a new folder (just to ensure nothing is mixed up)
* Start Unity on new folder (testing with 2017.2.0f2 & 2017.2.0f2-MRTK dev
* Open a Scene (InputManagerTests is a good one)
* START MR Portal (we wouldn't want Unity to Crash now would we :D)
* Enable Simulator (just for convenience, a headset produces the same result)
* Hit Play

Expected: (captured from Unity as an approximate)
image

Actual: (captured from MR Portal)
image

As you can see, the start position is elevated A LOT

Result is the same either it is run from Unity or from a Built project in Debug, Master or Release.

### LINKED ISSUE #1249: MixedRealityTeleport does not get disabled on HoloLens
`MixedRealityTeleport` does not get disabled on HoloLens.  Most noticeable when using Xbox Controller.

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixes #1249
Fixes #1084 Added Scene Content Adjuster for determining how much scene objects should be offset

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Haha this is true!  We should def choose a point soon to deprecate all the old API stuff.

Maybe after Unity finally "For _real_" releases full WMR support.

**Comment by StephenHodgson** [comment]
@keveleigh I added some stuff. Probs should have put it in a different PR but I pushed to the wrong branch

**Comment by StephenHodgson** [comment]
@DDReaper you might be interested in this update. Care to review?

**Comment by DDReaper** [comment]
Will check this out this weekend. Today's a bit busy but will look at it tomorrow for sure.

**Pull request merged**
