### PR TITLE
[vNext] Addressed feedback from Simon on naming of some files and demo scene. #2938

### PR DESCRIPTION
**Pull request by killerantz**
Overview

- Updated Demo scene with introduction banner and updated head and body objects to reflect current standards.

- Moved creating new states and themes to Mixed Reality Toolkit/Interactable/State

- Fixed an inspector layout error

- Renamed a bunch of files to include the "Interactable" prefix 

Changes
---
- Feedback: # 2938

### CODE REVIEW

**Comment by cre8ivepark** [comment]
I found that visual effects on HolographicButton are broken, and cannot change theme property. Probably because of the name change:

2018-10-25 15_30_06-mrtk-internal-sydney-dev - microsoft visual studio
2018-10-25 15_30_12-unity 2018 1 9f1 personal 64bit - interactablesgallery unity - mrtk-public-mic

**Comment by killerantz** [comment]
Thanks @cre8ivepark, I got these fixes pushed to a new branch, so I'm going to abandon this PR and create a new one.

**Comment by StephenHodgson** [comment]
Since we abandoned this branch, can we clean it up as well?
`feature/mrtk_interactable_demoUpdates_2938`

**Comment by StephenHodgson** [comment]
@killerantz ?

**Comment by killerantz** [comment]
Yes please!

**Comment by StephenHodgson** [comment]
@davidkline-ms please delete this branch.

**Pull request closed without merging**
