### PR TITLE
Mouse Input Fixes

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
- Fixed issues with Mouse in OpenVR
- Cleaned up a few input related classes with simpler logic.
- Added configurable mouse pointer properties
image
    - Hide mouse cursor on start.
    - Hide mouse after a few seconds if no input is detected from it.
    - Show mouse if any button is pressed / or above a set threshold.
        - When mouse is shown it's position is at gaze position
        - Mouse click to un-hide doesn't raise pointer click.

Changes
---
- Fixes: #2754
- Fixes: #2757
- Fixes: #2330

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Can we have a demo scene showing mouse input over controllers?  if it's not too much trouble.

**Comment by davidkline-ms** [comment]
That pointer settings script has some great looking features that would be nice to demo.

**Comment by StephenHodgson** [comment]
Every scene is a demo scene. We don't have demo scenes for the controllers.

**Comment by StephenHodgson** [comment]
Should we also add demo scenes for motion controllers as well?

**Comment by davidkline-ms** [comment]
> Every scene is a demo scene. We don't have demo scenes for the controllers.

We also don't have the threshold settings that make this a very compelling feature

**Comment by davidkline-ms** [comment]
> Should we also add demo scenes for motion controllers as well?

Maybe, but this mouse script has some great customer focused settings that would be really nice to enable easy experimentation.

**Comment by StephenHodgson** [comment]
Now that I think about it, I need to do more work to this PR by supporting an "always on" setting, in case someone wants that.

**Comment by davidkline-ms** [comment]
Question: Is the intent to have the vertical axes inverted? I was initially puzzled as to why pulling back on the mouse moved the cursor up in the world.

**Comment by StephenHodgson** [comment]
> Question: Is the intent to have the vertical axes inverted? I was initially puzzled as to why pulling back on the mouse moved the cursor up in the world.

Should also probably be customizable as well. I'll add that as well

**Comment by davidkline-ms** [comment]
I'll wait for your update and then test again.

**Comment by StephenHodgson** [comment]
Likely we want to be able to let users invert the mouse at the Controller mapping profile. Gotta think about this one a tick.

**Comment by StephenHodgson** [comment]
> Should the default be forward == up? It feels like it.

Probably. Sounds correct to me.

**Comment by StephenHodgson** [comment]
> I was initially puzzled as to why pulling back on the mouse moved the cursor up in the world.

When pushing the mouse up on the pad, the mouse should rise in front of your view as well. (Just like what you'd expect to see on screen).

The axis inversion might need to be a separate PR as it needs to be changed in the Controller Mapping Profile

**Comment by davidkline-ms** [comment]
> Looks good to me. @davidkline-ms can you also test and approve?

Will do.

**Comment by davidkline-ms** [comment]
I am getting some odd feeling behaviors, though that might be my inexperience with the feature.  The concerns I had with the previous version of this PR have been addressed.

**Comment by Alexees** [comment]
@StephenHodgson Just wanted to use an eventdata's Pointer.TryGetPointerPosition on the mousecursor, but it seems it's returned to something's localspace as it's definitely not world space. Is it the camera I have to convert it from?

**Pull request merged**
