### PR TITLE
More WSA wrapping

### PR DESCRIPTION
**Pull request by StephenHodgson**
Now builds for win standalone. (after Input Update gets merged)

### CODE REVIEW

**Comment by DDReaper** [comment]
Looks good, however, you have edited "StartSessionButton.cs" in both this PR and #1028 
You should exclude changing this file in this PR and leave it in the InputUpdate PR

**Comment by StephenHodgson** [comment]
I based this PR off the other, so those changes will disappear once it's merged.

**Comment by DDReaper** [comment]
Best be sure to merge them in order then :D @StephenHodgson 
I merged them backwards, but PR's should only ever run from the base branch, not from another PR

**Comment by StephenHodgson** [comment]
Agreed, I usually do a rebase each time.

**Comment by DDReaper** [comment]
In which case, this is tested fine (and yes, Builds to standalone with both PR's) and can be merged.
P.S. Dropped you a note on Slack

**Pull request merged**
