### PR TITLE
Input Handler Inspector Fix

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Pulled out Mixed Reality Manager Check and added it to base handler inspector to ensure proper setup if component is added before system is configured in the scene.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@alcooper91 can you confirm this fixes your issue please?

**Comment by alcooper91** [comment]
It does not appear to fix my issue:
image
Rather than showing the error message about there being no keywords, it simply doesn't show anything:
image

This reprod both with the default SpeechProfile and when I modified the DefaultSpeechProfile to add "Hello" and "Goodbye" as phrases

**Comment by alcooper91** [comment]
Same stack as pasted in my initial Issue message.

**Comment by StephenHodgson** [comment]
Oh right, my bad 😅 

Hmm, I wonder what I'm still missing to repro your issue. 🤔

**Comment by StephenHodgson** [comment]
Doesn't fix @alcooper91's bug but it still fixes an issue with adding a handler into the scene with out the Mixed Reality manager being configured.

**Comment by SimonDarksideJ** [comment]
Approved, however we do need a separate PR to address @alcooper91 issue.  Is there an issue number for it with repo steps?

**Comment by StephenHodgson** [comment]
#2834

**Pull request merged**
