### PR TITLE
HoloLens 2 style Check box / Radio / Toggle Switch buttons

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
Currently, MRTK provides traditional style Checkbox / Radio / Toggle Switch buttons. For cohesive user experience, adding HoloLens 2 style controls for Checkbox, Radio, and Toggle Switch that align with HoloLens 2 buttons.
These buttons are prefab variants of existing PressableButtonHoloLens2Toggle.prefab, just having different visual representations. Added Radio button group example with 

## Changes
- Added PressableButtonHoloLens2ToggleSwitchPlated_32x96
- Added PressableButtonHoloLens2CheckBoxPlated_32x96
- Added PressableButtonHoloLens2RadioPlated_32x96
- Added PressableButtonHoloLens2Toggle_32x96 
- Added PressableButtonHoloLens2Toggle_40x40
- Added PressableButtonHoloLens2Toggle_48x48
- Adjusted toggle backplate visual to fix the issue of hiding icon/text on press
  (existing PressableButtonHoloLens2Toggle prefabs)
- Updated PressableButtonExamples scene

New HoloLens 2 style controls vs existing controls:
HL2_ButtonCheckRadio
HL2_ButtonCheckRadio3

Toggle button fix Before & After:

Updated PressableButtonExamples scene
2020-02-25 16_15_49-Unity 2018 4 13f1 Personal -  PREVIEW PACKAGES IN USE  - PressableButtonExample

## Changes
- Fixes: #7393

### CODE REVIEW

**Comment by cre8ivepark** [comment]
Thanks, @thalbern! I'll update the scene to make the color indicator changed on press & work with far interactions.

**Comment by cre8ivepark** [comment]
Fixed far interactions issues & made the color block click indicator change color on click.
HL2Button_RadioFar2
HL2Button_CheckSwitchFar

**Comment by Troy-Ferrell** [comment]
Nice! If this get in soon, putting note here to update #7176

**Comment by cre8ivepark** [comment]
@thalbern Fixed. Thanks!
2020-02-27 13_54_23-Unity 2018 4 13f1 Personal -  PREVIEW PACKAGES IN USE  - PressableButtonExample

**Pull request merged**
