### PR TITLE
Fix for issue #5423

### PR DESCRIPTION
**Pull request by anuraag016**
Fix for issue #5423 [Controllers shown at original place after teleporting in VR.](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5423)

## Overview
This fix addresses the issue #5423 [Controllers shown at original place after teleporting in VR.](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5423)

## Changes
The fix is in the BaseController.cs file.
In the function:
protected virtual bool TryRenderControllerModel(Type controllerType, InputSourceType inputSourceType)

we add MixedRealityPlayspace.AddChild(controllerObject.transform);

This line should actually be moved inside TryAddControllerModelToSceneHierarchy function

so that even if we use the platform controller visualization, they will be correctly added to under MixedRealityPlaySpace game object.

### CODE REVIEW

**Comment by wiwei** [comment]
@keveleigh I think we were just chatting about this last week - was this one of the options you were thinking about?

**Comment by keveleigh** [comment]
Unfortunately, I don't believe just this change fixes it (after #5250). I implemented this locally last week and saw incorrect behavior in mrtk_dev.

I'm thinking through a combination of reverting #5250 and adding this change as part of more clearly defining the expected data from source pose events (world space vs local space).

**Comment by ritijain** [comment]
@keveleigh  - is this some

> Unfortunately, I don't believe just this change fixes it (after #5250). I implemented this locally last week ([keveleigh@ba647fc](https://github.com/keveleigh/HoloToolkit-Unity/commit/ba647fc67c976db744f214ea14ecc9c1a7e25cf5)) and saw incorrect behavior in mrtk_dev.
> 
> I'm thinking through a combination of reverting #5250 and adding this change as part of more clearly defining the expected data from source pose events (world space vs local space).

@keveleigh is this something you have the bandwith to try? What was the undesirable behavior that you observed, so that @anuraag016 can try it out as well?

**Comment by keveleigh** [comment]
@ritijain

>is this something you have the bandwith to try?

I've blocked out some time tomorrow to focus on some MRTK issues, including this one!

>What was the undesirable behavior that you observed

After teleporting, the controllers were in an unexpected location. I had originally fixed that with #5250, which is in mrtk_dev but not RC2.1, but I'm no longer convinced I fixed it correctly, after the issue @anuraag016 reported here. Combining the two fixes breaks things again though

**Comment by keveleigh** [comment]
@wiwei @davidkline-ms
I merged my work into this PR, to account for both this more correct fix and the changes I made in #5250. I decided to take the path of defining both events as world space data, since that's likely more useful for an end developer.

I believe this PR is ready for review now!

**Pull request merged**
