### PR TITLE
Port banner to 2.4.0 branch

### PR DESCRIPTION
**Pull request by MaxWang-MS**

### CODE REVIEW

**Comment by RogPodge** [comment]
@MaxWang-MS this PR seems to include a bunch of changes to .cs files and the pipelines/pr.yaml file from upstream. Can we remove these for the sake of not potentially introducing changes to the 2.4.0 from a functionality standpoint (even if adding inheritdoc changes is benign)

**Comment by MaxWang-MS** [comment]
@RogPodge Your concerns are totally understandable but those changes are required to make this PR pass the CI. There has been some updates to docfx that needs them.

**Review by RogPodge — APPROVED** [review]

**Pull request merged**
