### PR TITLE
Remove Unused Variable

### PR DESCRIPTION
**Pull request by BillyFrcs**
## Overview
Remove unused variable in some file ```PokePointer.cs```, ```ConeCastTrackingTargetTest.cs``` & ```EyeTrackingTargetTest.cs```

## Changes
- Remove unused variable ```private Vector3 endPoint```.
- Remove unused variable ```private GameObject target```.

### CODE REVIEW

**Review by keveleigh — APPROVED** [review]

**Comment by keveleigh** [comment]
Thanks for the clean-up!

**Comment by BillyFrcs** [comment]
> Thanks for the clean-up!

No problem Sir

**Pull request merged**
