### PR TITLE
Fix additional example folder cross-talk

### PR DESCRIPTION
**Pull request by davidkline-ms**
This change moves more assets (textures, materials, models, etc) to allow individual sample projects to be individually imported when using UPM.

This change is on the large side as the prudent approach seemed to be to move in bulk since many of the moved files feel very re-usable in customer projects.

### CODE REVIEW

**Comment by MaxWang-MS** [comment]
Looks like you removed CubeEnvironmentColor.mat and just want to confirm that that is intended.

**Comment by davidkline-ms** [comment]
> Looks like you removed CubeEnvironmentColor.mat and just want to confirm that that is intended.

That would have been a mistake. I will investigate

**Review by keveleigh — APPROVED** [review]
Feels like a lot of files, but you called that out in the PR description.

**Pull request merged**
