### PR TITLE
Unity Editor Update 2017.2.0f3 MRTP

### LINKED ISSUE #1114: 2017.2.0f3 MRTP Released
[Latest 2017.2.0f3 MRTP released](http://beta.unity3d.com/download/edcd66fb22ae/download.html)

Change Log
---
- Fix for XR.InputTracking.disablePositionalTracking
- Fix for exception getting thrown when calling DateTime.Parse in IL2CPP builds
- Fix for exception getting thrown when referencing DateTimeOffset in IL2CPP builds
- Fixes for asserts and broken rendering when using XRSettings.eyeTextureResolutionScale
- Fix for buttons not working with InputManager when only the left controller is on
- Fix for respecting different near/far clip plane values when using multiple cameras in one scene
- Fixed bug which caused Unity to crash on application close.

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixes #1114

### CODE REVIEW

**Comment by keveleigh** [comment]
There's also a link lower down in the readme, under Prerequisites, that just links to the beta page. That should probably be updated too.

**Comment by StephenHodgson** [comment]
I might just move some of the new stuff to the docs and make the main readme match master.

**Comment by StephenHodgson** [comment]
It's not hard to change the editor version. But really this is just easy for people to reference. 

I'm 95% sure we need to be using the MRTP for HMD support and the actual release for HoloLens.

**Comment by StephenHodgson** [comment]
This is the official editor version for WMR
image

**Pull request merged**
