### PR TITLE
add music library capability to examples project

### PR DESCRIPTION
**Pull request by davidkline-ms**
Overview
---
The MicStreamSelector plugin requires the Music Library capability to be able to save recording files.

Changes
---
Enable Music Library by default. Related to #993

### CODE REVIEW

**Comment by davidkline-ms** [comment]
@StephenHodgson, I believe we should

**Comment by StephenHodgson** [comment]
If that's the case, we should add this capability at the same time we prompt people to enable visible meta files.

In the capabilities selection menu, we should also explain that this capability should always remain enabled for the microphone, and as list of required capabilities to the documentation someplace.

**Comment by StephenHodgson** [comment]
Should we also add the signed DLLs for this to the PR?

**Comment by davidkline-ms** [comment]
Since i am not the code signer, i would prefer they be separate pull requests

**Comment by keveleigh** [comment]
I'm not sure we need to prompt every dev to add this capability. We should definitely add it as an option in the Add UWP Capabilities window, and we should also expose the error better to let people know why it's failing and how to fix it.

**Comment by DDReaper** [comment]
I agree with @keveleigh , this should be another option on the editor menu project options.
Probably best to fix that in #1471 and update #1530 @StephenHodgson.

Does this also need to be in the UWP Capabilities Build window as well?

**Pull request merged**
