### PR TITLE
Hand coach graduation feedback PR 

### PR DESCRIPTION
**Pull request by RogPodge**
## Overview
Addressing feedback on the hand coach graduation.

### CODE REVIEW

**Comment by RogPodge** [comment]
The scrolling object collection prefab ended up having a scary looking set of diffs compared to where it was before graduating the hand coach. The reason for this was a lot of renderers needed to get added into a field in the ClippingBox so that they would get masked properly, and as such, Unity did a lot of work behind the scenes. Ultimately the prefab works as intended so it shouldn't be an issue.

**Review by keveleigh — APPROVED** [review]

**Comment by keveleigh** [comment]
Wouldn't mind @cre8ivepark's feedback too, before merging

**Review by cre8ivepark — APPROVED** [review]
Tested and looking great!

**Pull request merged**
