### PR TITLE
Updated MRTK Optimize tool and performance/stability/optimization docs

### PR DESCRIPTION
**Pull request by Troy-Ferrell**
## Overview
There has been consistent confusion & ignorance around the necessity & significance of performance for mixed reality as well as how to properly stabilize holograms. There has also been feedback that developers like the idea of this being automated for them but they want control to select what gets changed or at least be better notified of what may change. Thus, modifying everything when MRTK is added or on some "Apply scene settings" would be problematic for many. 

This change improves functionality and UI for the MRTK optimize window tool to help developers set up their environment for success as well the related documentation.
- Simplify UI to provide all configuration changes up front instead of different tabs
- Made other tabs dedicated tools
- Added success/warning indicators and code checks to instruct user when their project is correctly configured
- Added 16-bit depth format setter
- Added updated documentation links
- Fixed issue where lights could be null
- Fixed issue where mesh filter could be null
- Added filter for MRTK shipped shaders in material discovery tool

Furthermore, for documentation changes,
- Added page for optimize window and new utilities section in table of contents
- added significant amount of content for perfgettingstarted.md to instruct users instead of resourcing out to various links. Emphasizing key configuration settings to get quick perf wins
- a new hologram-stabilization.md page for details on depth buffer sharing, stabilization plane, and world anchor references as well as how to update content to render depth

## Changes
- Fixes: #4884 , #4005 , #3158, #1939, #4962 

OptimizeWindow_Settings

### CODE REVIEW

**Comment by Cameron-Micka** [comment]
Pulled this down and it works great! Nice improvements for the developer community.

**Comment by Troy-Ferrell** [comment]
@wiwei can you merge this when available? Thanks!

**Pull request merged**
