### PR TITLE
Increased the frame wait timer to account for Holographic Remoting latency

### PR DESCRIPTION
**Pull request by RogPodge**
## Overview
Latency when connecting via holographic remoting is not standard, and on the 2.8.0 version of the windows XR plugin, the time it takes to register the Hololens is a bit longer, causing the scene content system to mistakenly place the scene content in a different area. This PR increases the wait time before setting the scene content's position, giving Unity a bit more time to initialize the camera in the proper place

## Changes
- Fixes: #9867

### CODE REVIEW

**Review by davidkline-ms — APPROVED** [review]
should we make this configurable with a default of 15?

**Comment by RogPodge** [comment]
> should we make this configurable with a default of 15?

It's a very editor specific workaround so I wouldn't want to expose it and make it public if possible.

**Comment by RogPodge** [comment]
It might be good to have build in a "transition" when loading in MRTK scene content so we can mask any weirdness with the initialization step in the future (like what hololens and WMR apps do when you first boot them up). I think we can expose this variable when we hit a point where we have a feature like that, but for now it feels a bit obtuse/likely to confuse developers.

**Pull request merged**
