### PR TITLE
MRTK 2017.2.1.2 Patch Release

### PR DESCRIPTION
**Pull request by StephenHodgson**
[See draft release notes](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/untagged-2045d27e3dba254591de)

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@keveleigh just waiting on the updated sharing service binaries for the pre-namespace refactor before we ship this.  Please let me know what you think the time frame will be for that.

**Comment by NeerajW** [comment]
@StephenHodgson do you want to update this from latest Stabilization? Then we can merge?

**Comment by StephenHodgson** [comment]
@NeerajW this PR is the direct stabilization branch, so it'll autoupdate as we merge in PRs against the stabilization branch.

**Comment by NeerajW** [comment]
Just saw it show up :)

**Comment by StephenHodgson** [comment]
Okay guys, pretty sure we're good to go here.

Anything we want to add before release?

**Comment by StephenHodgson** [comment]
Currently doesn't build for 5.6

**Comment by StephenHodgson** [comment]
@DDReaper anything else you think we should add?

**Pull request merged**
