### PR TITLE
[MRTK3] Changing default color space to Linear + material adjustments

### LINKED ISSUE #10774: Linear Color Space Support
## Describe the bug

From the ["Updates on OpenXR for Mixed Reality"](https://www.youtube.com/watch?v=RkWeRmtWyVo&t=1438s) talk during the MR DevDays, it was mentioned that with OpenXR HoloLens supports Linear Color Space. However it seems the MRTK shaders are lacking proper Linear Color Space support.

Switching to Linear results in various colors being off or other rendering artifacts like light bleeding on the UI backplates.

## To reproduce

1. Open your MRTK project and switch to Linear Color Space in the UWP Player settings.
2. Build a scene with the hand mesh visualizer enabled and other UI building blocks.
3. Observe hand mesh coloring being much more darker, as well as light bleeding on UI backplates.

## Expected behavior

Overall visuals is the same or just minor color blending variations.

## Screenshots

Linear Color Space
OpenXR_Linear

Gamma Color Space
WMR_Gamma

## Your setup

- Unity 2020.3.20f1
- MRTK 2.8.2

## Target platform 

- HoloLens 2

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
Updating MRTK3 default project setting to use Linear color space instead of Gamma.
Overall, colors in linear space look desaturated with less contrast. Adjusted major UI-related materials and MRTK Standard materials to make them close to the original colors in Gamma space. Tested on device & editor.

2022-08-29 12_01_58-Project Settings

- Resolves #10774 for MRTK3 (not MRTK2)

### CODE REVIEW

**Comment by Zee2** [comment]
Thanks so much for doing this @cre8ivepark !!

**Comment by cre8ivepark** [comment]
Not sure why it says I need to check in the meta file for ProjectSettings.asset file. Only modified m_ActiveColorSpace to 1.

Checking file: /home/runner/work/MixedRealityToolkit-Unity/MixedRealityToolkit-Unity/UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset
**WARNING: Meta file missing for /home/runner/work/MixedRealityToolkit-Unity/MixedRealityToolkit-Unity/UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset. Please be sure to check it in alongside this file.**

**Comment by MaxWang-MS** [comment]
Hi @cre8ivepark, this the PR ready for review now?

**Comment by cre8ivepark** [comment]
> Hi @cre8ivepark, this the PR ready for review now?

Yes, it is ready.

**Review by MaxWang-MS — APPROVED** [review]

**Comment by Zee2** [comment]
Something is up with this @cre8ivepark . All the Canvas materials are totally off... at least on my machine

image

What is going on here?

**Pull request merged**
