### PR TITLE
Remove update repaint method in build window

### PR DESCRIPTION
**Pull request by Troy-Ferrell**
## Overview
With build window visible and project running, developers notice massive performance drop. Even without play mode, this window is repainting itself more than necessary due to update() method.

This change just removes the excessive repaint

## Changes
- Fixes: #5003 

## Verification
Opened window with game mode and noticed perf drop in half. Now fixed
Close & open window fine
Select buttons to switch tabs 
Build worked

### CODE REVIEW

**Comment by wiwei** [comment]
I was initially concerned about what would happen if we removed this, but from testing a few of the common scenarios, it looks like this is fine - I thought that this was causing some bug where Open APPX Packages Location wasn't un-greying out after building the appx, but it turns out, it's just an existing bug.

**Comment by Troy-Ferrell** [comment]
Same sentiment Will, I think it was just left over and isn't needed for proper unity editor window behavior

**Pull request merged**
