### PR TITLE
Remove empty GazeController and replace with ActionBasedController

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

General cleanup of this empty class.

### CODE REVIEW

**Review by RogPodge — APPROVED** [review]

**Comment by camnewnham** [comment]
Is there an alternative way we can differentiate between controller types in script? Previously the GazeController would let us "select" the eye tracking controller (or so I thought..)

In our app we iterate controllers and perform different actions based on the type, i.e:

```C#
    return new XRBaseController[] { controllerLookup.LeftHandController, controllerLookup.RightHandController }
            .Select<XRBaseController, XR.Schema.IController>(controller =>
            {
                if (!controller.enabled || controller.currentControllerState.inputTrackingState == InputTrackingState.None)
                {
                    return null;
                }
                switch (controller)
                {
                    case ArticulatedHandController handController:
                        // Do something here
                    case GazeController gazeController:
                        // Do something here
                    default:
                        Debug.LogWarning("Unimplemented controller type: " + controller.GetType());
                        return null;
                }
            })
```

**Comment by Zee2** [comment]
@camnewnham Great question! I was about to give a super quick answer of "just check the type of the input device!" but realized that's actually not quite going to work with our current setup.

The problem is that right now we're using a _**separate**_ simulated eye gaze device that's `internal` and doesn't inherit from the normal eye gaze device, so you wouldn't be able to check against that (oops). If you were able to, you could do this:

```
using UnityEngine.XR.OpenXR.Features.Interactions;
using Microsoft.MixedReality.Toolkit.Input.Simulation;

if (controller is ActionBasedController actionBasedController)
{
    switch (actionBasedController.positionAction.action?.activeControl?.device)
    {
        case EyeGazeInteraction.EyeGazeDevice eyeDevice:
             // Controller is bound to an OpenXR-type eye gaze input device.
        case SimulatedEyeGazeDevice simulatedEyeDevie:
             // Controller is bound to a device of type AnotherInputDeviceType
        // etc
    }
}
```

If our eye gaze device inherited from the `EyeGazeInteraction.EyeGazeDevice` (which it should) then you would do:

```
if (controller is ActionBasedController actionBasedController)
{
    switch (actionBasedController.positionAction.action?.activeControl?.device)
    {
        case EyeGazeInteraction.EyeGazeDevice eyeDevice:
             // Controller is bound to an eye device
        // etc
    }
}
```
However, because that's not an option, you can always query the usages of the device:

```
if (controller is ActionBasedController actionBasedController)
{
    if (actionBasedController.positionAction.action?.activeControl?.usages.Contains(new InternedString("gaze")) ?? false)
    {
         // Controller is bound to a device with the gaze usage.
         // Replace `new InternedString("gaze")` with a CommonUsage to check for other kinds of input devices (hands, etc)
    }
}
```

A less-resilient way to check would be:

`if (controller.GetComponentsInChildren<IGazeInteractor>(true).Count != 0) { // controller is gaze!  }`

However, that assumes your gaze controller does actually have an interactor on it, which isn't necessarily true.

When we fix our simulated eye gaze device to inherit from the standard OpenXR eye device, this won't be a problem and you can do the second approach by just checking the device type.

**Comment by Zee2** [comment]
@camnewnham, an even easier approach while we sort this out: we have a helper script called `ControllerLookup` that simply holds a reference to the gaze controller and hand controllers. You can use that while we get this sorted out!

```
// Cache this in startup/awake/etc somewhere.
ControllerLookup lookup = PlayspaceUtilities.ReferenceTransform.GetComponentsInChildren<ControllerLookup>();

var gazeController = lookup.GazeController; // Easy lookup!
```

**Comment by Zee2** [comment]
@camnewnham , #11040 allows you to check for the simulated device. However, we still recommend using `ControllerLookup`.

**Comment by camnewnham** [comment]
> @camnewnham, an even easier approach while we sort this out: we have a helper script called `ControllerLookup` that simply holds a reference to the gaze controller and hand controllers. You can use that while we get this sorted out!
> 
> ```
> // Cache this in startup/awake/etc somewhere.
> ControllerLookup lookup = PlayspaceUtilities.ReferenceTransform.GetComponentsInChildren<ControllerLookup>();
> 
> var gazeController = lookup.GazeController; // Easy lookup!
> ```

Ah, perfect! I was already using `controllerLookup.LeftHandController` but hadn't checked if the Gaze controller appeared there. Still learning the MRTK3 patterns :)

Thankyou!

**Pull request merged**
