### PR TITLE
First step in updating to a new minimum Unity version 

### PR DESCRIPTION
**Pull request by davidkline-ms**
This change updates to Unity 2020.3.2f1, checks for 2020.3 on project load, removes the 2018.4 .net backend AR Foundation workaround and updates the package manifest.

Checking this in to a feature branch while we make the final call on the minimum Unity version for MRTK v3.

### CODE REVIEW

**Comment by davidkline-ms** [comment]
Looks like we need a Unity 2020.3 build on our CI systems

**Review by RogPodge — APPROVED** [review]
Seems fine to me for a feature branch.

Are we going to make 2020 the new minimum supported version?

**Comment by davidkline-ms** [comment]
> Are we going to make 2020 the new minimum supported version?

We are. Per #9597.

**Comment by davidkline-ms** [comment]
I will clean this PR up (merge latest and confirm that it builds correctly in 2020.3) and will merge into the feature branch this week

**Comment by RogPodge** [comment]
@davidkline-ms is this PR still relevant?

**Comment by davidkline-ms** [comment]
This is done. The v3 codebase has yet to be brought to github.

**Pull request closed without merging**
