### PR TITLE
Add ability for some ManipulationHandler to ignore pointer events from gameobjects using InteractiveColliderContext

### LINKED ISSUE #4393: BoundingBox script doesn't work  when ManipulationHandler component is also added to the same gameobject
## Describe the bug

I attempted leveraging the Bounding Box + ManipulationHandler capabilities. Turns out BoundingBox doesn’t work reliably when ManipulationHandler is also active in the same hierarchy. 

## To reproduce

1. Create an object in the MRTK enabled scene
2. Add the ManipulationHandler script to the gameobject.
3. Add the BoundingBox script to the gameobject. (script order is important)
4. Hit play in unity editor
5. try to use the bounding box handles. - Nothing happens.

## Expected behavior
Bounding Box works as expected and allows rotation and scale operations based on handles.

## Screenshots

image

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.10f1]
- MRTK Version [e.g. v2.0 - RC1-Refresh]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- UnityEditor

## Additional context
I tracked down the reason to the pointer event that BoundingBox receives has been marked “used” by manipulation handler sometimes.

### LINKED ISSUE #4546: BoundingBox needs to print error if maniphandler is above BoundingBox
## Overview
This bug is a follow up issue #4393. That bug was closed by design and the requirement is devs always put the bounding box component before manipulation handler on a game object if they are on the same object.

To prevent people from accidentally putting manipulation handler above bounding box, we should have some validation to check that manipulation handler component comes after bounding box on a game object.

### PR DESCRIPTION
**Pull request by julenka**
This is an alternative approach for PR #5072 to fix #4393 (follow-up bugfix is #4546)

## Looking for feedback
I'm looking for feedback regarding the approach in this PR compares to PR #5072. Would love to hear if folks see issues with this approach. Also suggestions about naming the component.

## Overview
The root cause of #4393 is that when maniphandler is above boundingbox, maniphandler will swallow all pointer events originating from scale, rotate affordances before bounding box has a chance to handle it. This causes the scale, rotate affordances to be impossible to grab. The fix is to put bounding box before manip handler. This allows bounding box to handle the affordances first.

PR #5072 solves this by throwing error if bounding box is ever coming after manip handler.

An alternate approach is to somehow tell ManipulationHandler to ignore events from certain gameobjects. I considered using tags or layers but decided against it because those approaches did not feel extensible (layers only have 31 values so potentially customers could run out if we took one for layer "Ignore Manipulationhandler", and only one tag allowed per gameobject).

An alternative to tags or layers is to add a component I called `ManipulationHandlerContext` component that can provide configurable info to a manipulationhandler whenever that gameobject is grabbed.  On PointerDOwn, ManipulationHandler then checks if the object the pointer event came from has a ManipHandlerContext and ignores the event source if IgnoredByManipulationHandler == true. This allows us to have descendents that raise pointer events, but which can be ignored by manipulation handler (because they could be used by some other components).

BoundingBox then adds these context components to its affordances, and sets IgnoredByManipulationHandler = true. This then prevents manipulationhandler from stealing the events that come from the bounding box affordances.

## Verification
- Verified that this allows bounding box handles to be grabbed regardless of whether bounding box is above / below manipulationhandler

### CODE REVIEW

**Comment by julenka** [comment]
Note: if I was to go with this approach I need to add docs in ManipulationHandler explaining ManipulationHandlerContext.

**Comment by julenka** [comment]
Okay, I updated to use a more general "InteractiveColliderContext" component. Going to mark this as ready for review then and close the other PR, in favor of this one.

**Comment by luis-valverde-ms** [comment]
What if instead we add a component to the rig root game object created by the bounding box that catches those events and dispatches them to the bounding box? I'd rather that to the context component approach because the latter forces event listeners (e..g manipulation handler) to check for the context while the former is completely transparent.

**Comment by julenka** [comment]
> What if instead we add a component to the rig root game object created by the bounding box that catches those events and dispatches them to the bounding box? I'd rather that to the context component approach because the latter forces event listeners (e..g manipulation handler) to check for the context while the former is completely transparent.

That could work, let me try it out.

**Comment by julenka** [comment]
> > What if instead we add a component to the rig root game object created by the bounding box that catches those events and dispatches them to the bounding box? I'd rather that to the context component approach because the latter forces event listeners (e..g manipulation handler) to check for the context while the former is completely transparent.
> 
> That could work, let me try it out and see.

Seems to be working! I like that solution a lot better, third times a charm :-) Will send that out shortly and closing this PR.

**Pull request closed without merging**
