### PR TITLE
Bounding box of SkinnedMeshRenderer support added

### PR DESCRIPTION
**Pull request by lvonasek**
## Overview
Bounding box does not support SkinnedMeshRenderer. That makes manipulation with models using SkinneMeshRenderer very hard. This PR resolves that issue.

## Changes
Added support of bounding box for SkinnedMeshRenderer

### CODE REVIEW

**Comment by RogPodge** [comment]
Thanks for the PR @lvonasek! Could you also update this code in [BoundsControl](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs)? The BoundingBox has been deprecated in favor of BoundsControl for awhile now.

**Comment by lvonasek** [comment]
> Thanks for the PR @lvonasek! Could you also update this code in [BoundsControl](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs)? The BoundingBox has been deprecated in favor of BoundsControl for awhile now.

Code updated as requested.

**Pull request merged**
