### PR TITLE
Add script to run playmode tests from powershell

### PR DESCRIPTION
**Pull request by julenka**
## Overview
Sometimes tests that pass in the Unity editor fail when run from console (in headless, batch mode). Finding the command to run this is possible, but not necessarily easy. Provide a script that runs the playmode tests locally, parses results, and provides a simple output (number passed, failed tests, and list failed tests).

## Changes
- Fixes: #5353
- Fixes: #5317 
- Add docs for how to run the test
- Change title of tests page to hopefully make the page easier to find from search engine.

### CODE REVIEW

**Comment by wiwei** [comment]
Yasss

**Comment by julenka** [comment]
> I wonder if there would be an easy way to get the exact same script runnable here as the script we run on the pipeline, so we don't potentially have the same / similar code in two places.

@MenelvagorMilsom is this script acceptable to run on CI? Not sure...it does stuff like open up a new window...It does print some basic test results which is nice but CI already does this.

**Comment by julenka** [comment]
> Weird that the script is showing up as binary in the PR (clicking through show the script just fine). LGTM though!

@keveleigh argh I saved the file as utf-16 for some reason. Ignored it yesterday because I was tired. Fixed it now, saved at utf-8.

**Comment by MenelvagorMilsom** [comment]
> @MenelvagorMilsom is this script acceptable to run on CI? Not sure...it does stuff like open up a new window...It does print some basic test results which is nice but CI already does this.

We're already doing something similar [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/pipelines/templates/tests.yml). On CI we write our results to the console continuously so that we can observe progress. Also we may be able to run this script on CI easier if we could specify a unity install folder and let the script find the .exe.

Otherwise these scripts are very similar, we should be able make a few changes and use this on CI.

**Pull request merged**
