### PR TITLE
Fix incorrectly set up gridobjectcollection assets

### PR DESCRIPTION
**Pull request by julenka**
## Overview
After #6550, many of our scenes and prefabs had gridobjectcollection assets which had row/column configurations that caused the gridobjectcollection upgrade detection to print a warning. This change updates the prefabs / scenes so that no other scenes raise the gridobjectcollection upgrade warnings.

## Changes
- Fixes: #6580 
- Change the warning to a log message when gridobjectcollection detection possible upgrade from 2.1 to 2.2
- Add one more edge case for detecting grid object collection asset upgrade.
- Change default distance for plane layout from 1m to 0m, since most assets actually wanted to be laid out 0m from parent

## Verification
I opened all MRTK scenes in editor and verified no warnings were printed.
> This optional section is a place where you can detail the specific type of verification 
> you want from reviewers. For example, if you want reviewers to checkout the PR locally
> and validate the functionality of specific scenarios, provide instructions
> on the specific scenarios and what you want verified.
>
> If there are specific areas of concern or question feel free to highlight them here so
> that reviewers can watch out for those issues.
>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by CDiaz-MS** [comment]
@julenka 
Currently checking the scenes but I found that pressing the Previous Anchor button does not set the Anchor.

GridObjectCollectionNegativeIndex

**Comment by CDiaz-MS** [comment]
Checked all the scenes and verified no warning messages were printed.

**Comment by CDiaz-MS** [comment]
Tested and it works for me.

**Comment by keveleigh** [comment]
Looks like some merge conflicts 😕

**Comment by julenka** [comment]
we also discovered some of the parameters in the HandMenuExamples scene do not match best practices, @cre8ivepark  will update those params as well

**Comment by cre8ivepark** [comment]
@davidkline-ms @keveleigh I am resolving the merge conflict now.

**Pull request merged**
