### PR TITLE
ET demo texture size is too big

### PR DESCRIPTION
**Pull request by sostel**
## Overview
- Addresses issue #4582
- Decreased file size of textures and replaced Photoshop (*.psd) files with *.png for the Eye Tracking navigation demo. 
- The texture for zoom is still relatively big, but if that is reduced further the zoom doesn't make much sense anymore.

### CODE REVIEW

**Comment by wiwei** [comment]
I changed the title of this PR to reflect what it's addressing - I think that with this we're still bloating the repo (because we have historical copies of things) so there's still work here that needs to be done in order to scrub the older files away... I think

**Comment by sostel** [comment]
> I changed the title of this PR to reflect what it's addressing - I think that with this we're still bloating the repo (because we have historical copies of things) so there's still work here that needs to be done in order to scrub the older files away... I think

How can we scrub the older files away? Not familiar with this. Do you know anybody who's familiar with that?

**Comment by keveleigh** [comment]
I think we should take this as-is. This will help decrease the size of our release packages. I'm not sure there's a way to scrub older files without rewriting history, which we shouldn't do in a shared repo like this one.

**Pull request merged**
