### PR TITLE
ProgressIndicatorExamples Demo Update

### PR DESCRIPTION
**Pull request by Railboy**
## Overview
This overhauls the ProgressIndicatorExamples scene to include more useful examples. It also includes some minor fixes to progress indicator prefabs.

## Changes
- Fixes: #9970

### CODE REVIEW

**Comment by RogPodge** [comment]
Small request to increase the text font size to make it a bit more readable in demo. Changing the profile to hololens so it uses a black background instead of the default skybox would also be helpful:
image

The CI is also emitting a lot of warnings about unassigned variables, would be good to fix those up
image

**Comment by RogPodge** [comment]
@Railboy I'm also not quite sure what's going on with this scene: 
image

I also can't tell where the ProgressIndicatorDemo scripts are being used, so even though they look right I can't really verify

**Comment by cre8ivepark** [comment]
This is a great example of using Progress Indicator with actual scene loading. I think it would be helpful to include information text in the scene something like "This example requires ProgressIndicatorExamplesAdditiveLoad.unity scene in the Build Settings". 
2021-06-14 14_08_25-Unity 2018 4 35f1 -  PREVIEW PACKAGES IN USE  - ProgressIndicatorExamples unity

**Comment by RogPodge** [comment]
Adding onto Yoon's comment, I was under the impression that the example was simply to show the spinning indicator, not seeing any actual content loaded onto the earth model. I agree that clarifications on that front in both the additive scene and in the main examples scene itself would be very helpful (maybe we can rename the AdditiveLoad scene to something else or put an indicator somewhere, I feel like loading entire scenes into other scenes is a bit different from the usual developer workflow.)

**Review by RogPodge — APPROVED** [review]
Code looks good barring CI changes. Figured out that the new scripts were used within the scene's button scripts.

**Comment by RogPodge** [comment]
small ping on updating the CI issues @Railboy

**Pull request merged**
