### PR TITLE
Delete README_Pointers.md

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

This page isn't referenced anymore and only exists as a pointer to the new pointers docs.

### CODE REVIEW

**Comment by Troy-Ferrell** [comment]
@keveleigh check https://github.com/MicrosoftDocs/mixed-reality as well and make sure there are no references

**Comment by keveleigh** [comment]
@Troy-Ferrell Good call! Opened https://github.com/MicrosoftDocs/mixed-reality/pull/1940 to update the link there.

**Comment by keveleigh** [comment]
https://github.com/MicrosoftDocs/mixed-reality/pull/1940 has been merged, so I'm merging this in

**Pull request merged**
