### PR TITLE
Asset Organization

### PR DESCRIPTION
**Pull request by StephenHodgson**
See #986

Organizes the branch to better reflect the master branch folder organization.

### CODE REVIEW

**Comment by jessemcculloch** [comment]
Any suggestions on how to test this?

**Comment by StephenHodgson** [comment]
@jessemcculloch not really much to test per se, but the structure should match the master branch.  Best way to do that is do a side by side folder comparison.

**Comment by jessemcculloch** [comment]
Do we have any way to make sure that the reorg does not break any prefabs? Material & script locations, etc?

**Comment by StephenHodgson** [comment]
Shouldn't be a problem as long as the guids don't change.

**Pull request closed without merging**
