### PR TITLE
Add planning process document

### PR DESCRIPTION
**Pull request by davidkline-ms**
This change adds a document describing the MRTK planning process.

### CODE REVIEW

**Comment by wiwei** [comment]
I was thinking about where we might put this, and the more I think about it, I'm curious if having planning process be part of the docs is kinda odd - it kinda feels like the docs should reflect how as a consumer folks should be consuming things, whereas maybe our wiki here is what should be driving contributors.

Otherwise, I'm kinda curious - would you imagine we'd also put iteration plans on the same general location on the docs? Would it make sense to keep the iteration plans and generally planning/how we run the project somewhat close together (so that you can go from overall meta plan to specific plans).

I think that it might be good to get some alignment on this, as it will affect where we choose to put other artifacts in the future.

**Comment by davidkline-ms** [comment]
> I was thinking about where we might put this, and the more I think about it, I'm curious if having planning process be part of the docs is kinda odd 

Good point. I am happy to post this in the repository's wiki. Sound reasonable?

**Comment by wiwei** [comment]
Cool, closing this one out in favor of the wiki

**Pull request closed without merging**
