### PR TITLE
Signed MixedRealityToolkit binary updates

### PR DESCRIPTION
**Pull request by keveleigh**
Overview
---
This is a new drop from https://github.com/Microsoft/MixedRealityToolkit, adding versioning info (starting at 1.0.0.1 for this drop) to all the DLLs and EXEs, as well as digitally signing the binaries with the official Microsoft certificate for authenticity.

The updated Sharing binaries will come from #1666.

In the future, drops will happen as necessary from the native repo, instead of all at once like this.

Changes
---
- Unblocks: #1435 
- Supercedes: #1562 
- Fixes: #493 
- Probably others...

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@DDReaper I think he just wants to verify they work

**Comment by keveleigh** [comment]
> when we already have them planned for the NameSpace Refactor?

I only have the sharing binaries planned to be updated in the namespace refactor branch. The rest can go directly into the dev branch, since there weren't any namespaces to be updated there.

**Comment by StephenHodgson** [comment]
Will not including the ARM version of the Motion Controller prevent us from building for that platform target?

**Comment by keveleigh** [comment]
The motion controller DLL is only used in the editor, while built apps call the platform API directly, so we don't need to ship any UWP versions of them.

**Pull request merged**
