### PR TITLE
Improve configuration checking by MRTK

### PR DESCRIPTION
**Pull request by Troy-Ferrell**
## Overview
This change improves notifying the user of non-recommended settings currently configured in the developer's unity project. In particular the focus is on Single Pass Instanced rendering which has been shown to have tremendous performance increases for XR projects and should be pushed as the default configuration.
https://blogs.unity3d.com/2017/11/21/how-to-maximize-ar-and-vr-performance-with-advanced-stereo-rendering/

- Added listener to MixedRealityEditorSettings to check for when play mode is entered. When this happens, the system will check if certain configurations have not been set and alert user via warnings (see screenshot). This warning & check logic is only in editor

- Added preference for user to decide whether to run configuration check or not (see screenshot)

- Updated the settings prompt to also check for single pass instanced to be default rendering path if user accepts. I did not add enable depth buffer sharing because this should be default for new unity projects. Furthermore, enabling depth buffer sharing can have problematic outcomes on Hololens if data is not written to depth compared to single pass instancing (which only affects custom shaders potentially). 

- Fixed MixedRealityEditorSettings to use correct ignore prompt preferences key. Item was duplicated and broken between the preferences window and if the user clicked "ignore" button the prompt. The keys were not matching. I have updated the preference window (MixedRealityPreferences.cs) to use "_MixedRealityToolkit_Editor_IgnoreSettingsPrompts" with the underscore since it is more likely users have hit the ignore button via the prompt then gone into preferences project settings window. 

- Also moved MixedRealityPreferences to utilities/editor package so it can be utilized across project and thus had to make class public

image

image

## Changes
- Fixes: #4941 , #2860
Related: #1939 

## Verification
Enter play mode with various settings off and notice warnings logged
Turn off preference in project settings, note warnings are not filed on re-run of above

### CODE REVIEW

**Comment by jbienzms** [comment]
I guess the only issue I have with this approach is that currently there are so many warnings in MRTK projects I see developers turning warnings off and only focusing on errors. I almost feel like not having shared depth buffer turned on should be an error instead of a warning, but I do understand there are some situations where this is actually desired. I just wish that these warnings could be surfaced in a more visual way. For example, I wish they could be surfaced similar to your performance analysis tool rather than just warnings in the console window.

**Comment by jbienzms** [comment]
Looks like we still need a check to warn if the audio spatializer isn't set to Microsoft HRTF?

**Comment by jbienzms** [comment]
Looks like we still need a check to warn if the audio spatializer isn't set to Microsoft HRTF?

**Comment by Troy-Ferrell** [comment]
@jbienzms , yes I struggled with deciding how best to surface these suggestions. It's kind of like the spatial mapping system default state. Some wanted it on by default while others hated it being on by default. Errors will be much more prominent but then a developer who wants to ignore this will have to go to the preferences and check "not run" effectively. I tried adding the bold rich text to make the warnings stand out. I also considered a prompt dialog...but again some developers will likely get extremely pissed. 

Depth buffer sharing is slightly lower than single pass instanced rendering. The problem with depth LSR is it requires the developer to submit a valid depth buffer which means work and understanding on their side. Whereas SPI only affects you if you have custom shaders which is more rare, and if you are writing shaders yourself, you likely know about SPI. 

I actually missed the HRTF spatializer setting. That may be harder. I need to check if I can set the scriptable object like I do lighting settings. Is there issues if people have the Oculus spatializer set basically?

**Comment by jbienzms** [comment]
> @jbienzms , yes I struggled with deciding how best to surface these suggestions.

Yeah, this is a challenging one. Especially since some are recommended but optional. That's what I miss about the old HTK "Configure my project" wizard.

> I actually missed the HRTF spatializer setting. That may be harder. I need to check if I can set the scriptable object like I do lighting settings. Is there issues if people have the Oculus spatializer set basically?
> 
> **EDIT:**
> Added log warning check for MS HRTF audio spatializer only when build target platform is UWP since MRTK developers may be building for non-Microsoft platforms

I think this is a good approach. Technically we will pretty much always want to use Microsoft HRTF on HoloLens and ideally use it on WMR immersive. But if they're targeting another platform, or even if they're targeting Vive or Rift on PC they could be using a different spatializer. So ideally I would only warn when targeting HoloLens, but I don't think we can know that in Unity. So probably just warning for UWP is best for now.

**Comment by Troy-Ferrell** [comment]
Updated PR to point to prerelease/2.0.0_stabilization

**Pull request merged**
