### PR TITLE
Disabled the MRTK build window when the build target != UWP

### PR DESCRIPTION
**Pull request by StephenHodgson**
Left some convenience buttons in the window.

### CODE REVIEW

**Comment by DDReaper** [comment]
Will need this replicating in Dev

**Comment by keveleigh** [comment]
@DDReaper We'll do a merge back from master into the dev branch once the stabilization branch is merged, which will bring back these bug fixes.

**Comment by StephenHodgson** [comment]
@keveleigh I'm not sure it's that simple.  Esp after the namespace refactor.

**Comment by DDReaper** [comment]
Yeah @keveleigh Due to the NS refactor, these changes need manually redoing against Dev_Working (where applicable).  in my experience, merging back from the old way caused too many issues.

**Comment by HBJKZLH** [comment]
Untiy [Universal Windows Platform] Platform does not support.

The Socket code is written and the Thread code is written and the FileStream code is written, you know what?



I used the network communication section to find that this part of the code could not be transferred to the [Universal Windows Platform].

After I tested Unity 2017.2.0f3 (64-bit) version,Unity 2017.3.1f1 (64-bit) version,Unity 2017.2.1f1 (64-bit) version.



They don't support it.



Do you have any feedback on untiy?









When I wrote socket and IO and Thread related code in the program, untiy packaging times was wrong,
The socket.Connect function is not supported.
The socket.Receive function is not supported, and the 
socket.Send function is not supported.
The filestream.close function is not supported,
New Thread(recv) is not supported,
Does not support Thread. IsBackground,
Does not support Thread. To Start,




But if I just write in the code.

The Socket client = null;

Thread the Thread = null;

FileStream filedata = null;



This way, the Universal Windows Platform is passed.

I think it should be the flaw in the Platform library of untiy [Universal Windows Platform].


Please help me to feedback this question,








------------------ 原始邮件 ------------------
发件人: "Stephen Hodgson"<notifications@github.com>;
发送时间: 2018年3月1日(星期四) 中午12:03
收件人: "Microsoft/MixedRealityToolkit-Unity"<MixedRealityToolkit-Unity@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [Microsoft/MixedRealityToolkit-Unity] Disabled the MRTK buildwindow when the build target != UWP (#1747)




@keveleigh I'm not sure it's that simple.  Esp after the namespace refactor.

**Pull request merged**
