### PR TITLE
[MRTK3] Port Build Window to MRTK3

### PR DESCRIPTION
**Pull request by pajama**
## Overview
BuildDeployWindow is in it's own package and assembly. Included everything needed to make it compile. Probably could still use a pass at namespacing and folder structure, but at least I verified that this now works with MRTK3, so it's a start.

## Changes
- Fixes: #10947

### CODE REVIEW

**Comment by Zee2** [comment]
image

Please avoid checking in IDE files!

**Comment by keveleigh** [comment]
Hey @pajama! I've been working on a similar port locally (slowly, but surely haha...).
Do you mind if I come in and adapt some of the changes I've made to your PR here? Or would you rather me provide feedback and allow you to continue this work?

**Comment by pajama** [comment]
Hey @keveleigh! Please by all means hack at this PR! I can try to help test some more soon once my workload clears up a bit.

**Comment by pajama** [comment]
@microsoft-github-policy-service agree [company="default"]

**Comment by pajama** [comment]
@microsoft-github-policy-service agree

**Comment by AMollis** [comment]
We appreciate your contribution and thank you for the pull request.

Microsoft Mixed Reality Toolkit version 2 (MRTK2) is currently in limited support. This means that Microsoft is only fixing high priority issues. Unfortunately, this pull request does not meet the necessary priority and will be closed. If you strongly feel that this change deserves more attention, please open a new pull request and explain why it is important.

Microsoft recommends that all new HoloLens 2 Unity applications use MRTK3 instead of MRTK2.

Please note that MRTK3 was released in August 2023. It features an all-new architecture for developing rich mixed reality experiences and has a minimum requirement of Unity 2021.3 LTS. For more information about MRTK3, please visit [https://www.mixedrealitytoolkit.org](https://www.mixedrealitytoolkit.org).

Thank you for your continued support of the Mixed Reality Toolkit!

**Pull request closed without merging**
