### PR TITLE
GpuTiming -> GpuStats, now with VRAM usage added and no build warnings

### PR DESCRIPTION
**Pull request by botrif**
This corresponds to the MixedRealityToolkit changes for this plugin https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3319

The GpuTimingCamera.NewGpuFrameTime event was added because the best time to read the previous full frame timing is in OnPreCull(), which is not available to MonoBehaviours in general but only ones attached to a camera, which this script is

### CODE REVIEW

**Comment by StephenHodgson** [comment]
Please update your branch with latest development changes. We only accept Pull Requests on the development branch. 

Thanks.

**Comment by StephenHodgson** [comment]
Sorry, not sure why it closed the issue when I changed the branch target. Please reopen when it's updated.

**Comment by botrif** [comment]
htk_development?

**Comment by botrif** [comment]
I'm going to create a new PR instead

**Comment by StephenHodgson** [comment]
Most likely mrtk_development unless your code was targeting the old HoloToolkit

**Comment by botrif** [comment]
OK I think David Kline from MixedRealityToolkit will submit these changes instead. I’m not even sure what “old HoloToolkit” means.

**Pull request closed without merging**
