### PR TITLE
Update XR SDK spatial mapping to support additional platforms (OpenXR)

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

Using the [Mixed Reality OpenXR package](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-supported-features) 0.9.0-preview.1, spatial mapping is available!

## Changes
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9491

### CODE REVIEW

**Review by MaxWang-MS — APPROVED** [review]

**Review by davidkline-ms — APPROVED** [review]

**Comment by laultman** [comment]
In response to email from Kurtis "Yes, spatial awareness with OpenXR was not supported in the MRTK 2.6.1 release. This work was tracked by #9491 and added to the 2.7.0 release by #9567. It's present in the 2.7.0 preview, which you can download via the feature tool if you enable previews in the settings."
As I noted in my discussion in the current version of the Feature Tools the 2.7.x features are NOT available even with the preview enabled.

**Comment by laultman** [comment]
I enabled them from the beginning as it was detailed in the documentation. They were never present at any time.

**Pull request merged**
