### PR TITLE
Initial check-in of example scene 2

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
Overview
---
Second example scene, aiming to provide a more real world implementation
Aims to demonstrate more advanced interactions through vNext operation such as:

* Grabbing
* Resizing
* Chained interactions
* tbc

image

Aim is to ensure it is a professional looking scene that is engaging as well as educational

Changes
---
- Added room scene
- Added content from the Build Insiders event
- Resized down textures to minimize the physical size of the scene
- Updated all content to use the Standard shader

TODO
---
- [ ] Styling on Scene - help please
- [ ] Lighting / shader effects in scene, including audio effects
- Tutorial script / audio (pushed to Beta)
- [ ] Tutorial / example documentation, walking through creation and use of the scene
- [ ] Input config

Replaces PR #2511 with a branch against main development

### CODE REVIEW

**Comment by davidkline-ms** [comment]
> including audio effects
@SimonDarksideJ, what type of audio effects are you looking for?

> Tutorial script / audio
As mentioned in #2514, let's not block alpha on a voice-over. We can draft / record the script in beta.

**Comment by beaufolsom** [comment]
Hey @SimonDarksideJ @davidkline-ms,

I'm an artist on The Developer Experience team working with @radicalad @cre8ivepark -- I'm going to fork Simons repo and make a new base scene to work from -- look for a PR in the near future in Simon's repo.

**Comment by davidkline-ms** [comment]
> I'm going to fork Simons repo and make a new base scene to work from -- look for a PR in the near future in Simon's repo.

Woo Hoo!

I would also love your feedback / contributions to the example scene 1 branch :)

**Comment by SimonDarksideJ** [comment]
Both example scenes are branches off the main repo, so they should be ready to grab.

Go wild, but just don't use 4k textures 🤣

**Comment by StephenHodgson** [comment]
Yes, please branch the main repo.

**Comment by davidkline-ms** [comment]
closing so @SimonDarksideJ can untangle the original scene 2 and the new scene 3 into separate branches.

**Pull request closed without merging**
