### PR TITLE
Added option to only have slider sounds play during manipulation

### PR DESCRIPTION
**Pull request by RogPodge**
## Overview
Added option to only play slider sounds during manipulation. When enabled, a flag is flipped on when the slider is being manipulated, which allows the sounds to play. This ensures that the sound only plays during manipulation, and not when the value is modified via scripts.

## Changes
- Fixes: #10065

### CODE REVIEW

**Review by keveleigh — APPROVED** [review]

**Comment by Zee2** [comment]
Is it possible to write tests for this?

**Review by Zee2 — APPROVED** [review]

**Comment by RogPodge** [comment]
> Is it possible to write tests for this?

Seems a tad cumbersome since the specific sounds that are played are all private.

**Pull request merged**
