### PR TITLE
Upgrade example scene & prefab button icons

### PR DESCRIPTION
**Pull request by Railboy**
## Overview
Updates button icons in example scenes and prefabs.

## Changes
- Fixes: #7810

### CODE REVIEW

**Comment by davidkline-ms** [comment]
#7906 (replacement PR for #7886) as been merged. Taking this out of draft status.

**Comment by davidkline-ms** [comment]
@RogPodge, can you resolve merge conflicts? Please note merges can sometimes be tricky in prefabs. It might be easier to re-apply your changes after accepting the upstream changes.

**Comment by Railboy** [comment]
@davidkline-ms I've handled the merge conflicts.

I would like @cre8ivepark to review since they involved the examples hub scene and ToggleFeaturesPanel, both of which he has made recent changes to.

**Comment by cre8ivepark** [comment]
Found one icon on the hand menu (close button) had an incorrect icon displayed. (pin instead of x)
Updated and testing now.

**Comment by cre8ivepark** [comment]
Tested on the device using Examples Hub and it looks good!

**Comment by davidkline-ms** [comment]
@RogPodge / @cre8ivepark, looks like one more merge conflict snuck in.

**Comment by cre8ivepark** [comment]
It seems like the prefab SlateUGUIHoloLens2Buttons.prefab was modified & relocated by this PR:
#7923
I'll merge and update it.

**Pull request merged**
