### PR TITLE
Ported Solvers to vNEXT

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
- Brings over solvers from master branch.

TODO:
---
- [ ] Examples and Tests

### CODE REVIEW

**Comment by davidkline-ms** [comment]
Do we need these for Alpha? Or were they just super convenient to port? :)

**Comment by StephenHodgson** [comment]
They're private. Shouldn't be used outside of their respective classes.

**Comment by Ecnassianer** [comment]
In regard to your TODO, don't forget that june18_dev's solver example map is much improved over the one in master branch!

**Comment by SimonDarksideJ** [comment]
@cre8ivepark can you approve this PR if you are ok with the Solvers update?  Else this is going to cause delays with @davidkline-ms & @keveleigh absence

**Comment by StephenHodgson** [comment]
Holding off until solver update in master.

**Comment by davidkline-ms** [comment]
Let's get this in and we can track the changes that need to come from master via #2465.

**Pull request merged**
