### PR TITLE
Android Shader Support

### PR DESCRIPTION
**Pull request by Cameron-Micka**
## Overview
A handful of users have been using the MRTK on Android platforms which use OpenGL ES renderers. This pull request attempts to address a few issues which have been found by the community.

Changes include: 

- Removing the Shader Model 5 requirement which was only the "earlydepthstencil" feature. Documentation hints that early depth stencil automatically gets enabled when the shader compiler detects it is feasible. 
- Fixing a handful of shader compilation warnings in OpenGL ES. (Note, some warnings only appear the first time a shader is compiled.)
- Fallback shaders now default to MRTK ones. 

## Changes
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/2517, https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6003, and (partially) https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5875

## Verification
I've tested on HoloLens, HoloLens 2, Oculus Quest, and Windows PC. If you have any other platforms to test on that would be much appreciated. Especially unusual OpenGL ES variants found on mobile phones.

>
> As a reviewer, it is possible to check out this change locally by using the following
> commands (substituting {PR_ID} with the ID of this pull request):
>
> git fetch origin pull/{PR_ID}/head:name_of_local_branch
>
> git checkout name_of_local_branch

### CODE REVIEW

**Comment by keveleigh** [comment]
When first opening in Unity for Android, I see

image

not sure if this is fine?

**Comment by Cameron-Micka** [comment]
> When first opening in Unity for Android, I see
> 
> image
> 
> not sure if this is fine? (Also the same message for `Hidden/Instanced-Colored`, but I don't think that's one of ours)

Nice find! Which OpenGL ES version are you using? I’m guessing the version you have specified doesn’t support geometry shaders and instancing. I’ll make the MRTK/Standard the fall back. Even though it won’t look anything like the hand triangles at least we won’t get magenta on Android.

**Comment by keveleigh** [comment]
I'm in 2018.4.11, and I don't _think_ I've changed any defaults (but I could be wrong!)

image

**Comment by Cameron-Micka** [comment]
Interesting, thanks! I’ll give that a try on Monday. That looks like what I have.

**Comment by Cameron-Micka** [comment]
Weird! The console never showed me those warnings (tried in 2018.4.11 too). But, I filtered all the shaders within the MRTK and was able to see those warnings in the inspector and pushed up the changes.

**Review by keveleigh — APPROVED** [review]

**Pull request merged**
