### PR TITLE
[vNext] Feature/mrtk interactable demo2938 and inspector updates

### PR DESCRIPTION
**Pull request by killerantz**
Overview
- Updated Demo scene with introduction banner and updated head and body objects to reflect current standards.
- Moved creating new states and themes to Mixed Reality Toolkit/Interactable/State
- Fixed an inspector layout error
- Renamed a bunch of files to include the "Interactable" prefix
- Fixed issue caused by renamed files.
- Cleaned up inspector base files and moved some features to a static class instead of a base class.

Changes
- Feedback: # 2938

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Is this yet ready for review @killerantz ?

**Comment by cre8ivepark** [comment]
@killerantz Tested with HoloLens and works great. All Receiver events are working well. Confirmed HolographicButton prefab is also fixed. Thanks!

**Comment by killerantz** [comment]
@SimonDarksideJ  Yes, it's ready for what's there. I checked off some of the items from your feedback (#2938), other items are still in progress. Thanks.

**Comment by StephenHodgson** [comment]
Can we delete this branch (`feature/mrtk_interactable_demo2938AndInspectorUpdates`) now that it's in?

**Comment by davidkline-ms** [comment]
done

**Pull request merged**
