### PR TITLE
Removed duplicate bounding box asset 

### PR DESCRIPTION
**Pull request by StephenHodgson**
Changes
---
- Fixes: #1593

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@Railboy

**Comment by Railboy** [comment]
This change breaks the Bounding Box prefab. I recommend that we rename the UX mesh asset instead, since it will likely be modified further as we incorporate more bounding box functionality.

**Comment by StephenHodgson** [comment]
How does it break the prefab?  I double checked and all the mesh references are linked to the asset in the UX/Models folder

**Comment by StephenHodgson** [comment]
Also, this duplicated asset is causing issues with duplicated meta files.

**Comment by Railboy** [comment]
We've got several unmerged bounding box prefabs that aren't using the UX meshes yet. But on reflection I guess we have to break them sooner or later.

**Comment by NeerajW** [comment]
@Railboy could we help approve or comment on this?

**Pull request merged**
