### PR TITLE
Add ability to suppress OnClick after OnHold for PressableButtons

### PR DESCRIPTION
**Pull request by FlorianJa**
## Overview & Changes
- Fixes: #10285

### CODE REVIEW

**Comment by davidkline-ms** [comment]
@zee, here is one for you mr. button :)

**Comment by MaxWang-MS** [comment]
Thanks for your contribution @FlorianJa! It looks like based on the current modifications the suppression mechanism only works when the `InteractableOnHoldReceiver` component is added and the added suppress click flag set before the `PhysicalPressEventRouter` gets initialized. As we allow runtime addition and removal of receivers, could you make it work even when the receiver is added/removed or the flag is changed in runtime?

**Comment by FlorianJa** [comment]
Yeah, thats true. Changes during runtime are not applied here. I had a look at the code and as far as I can see, without changing the `Interactable` script I need to "pull" the receiver in the Update method in `PhysicalPressEventRouter`. I think is is not desirable, right? Another way would be to add two new events to the `Interactable` script informing other components that receivers were added or removed. This would require changes in 

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/2683255e63e756437a42168de482e783472af8d9/Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs#L804-L822

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/2683255e63e756437a42168de482e783472af8d9/Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs#L1056-L1064

What do you think?

Btw: I could not find a method to remove receivers during runtime. The only solution which I see is getting the whole `List<InteractableEvent> InteractableEvents`, remove one or more receivers and then set the `InteractableEvents` again. Did i miss something?

**Comment by MaxWang-MS** [comment]
Thanks for your detailed response @FlorianJa! So yes, I believe pulling in update loop is not desirable here. I think you are also right in that we need to notify `PhysicalPressEventRouter` when there's a change to InteractableEvents, but I am not sure what would be the best approach. You mentioned using UnityEvents, but I am debating myself whether we can just call into a newly created function in `InteractableEvents`, for example `UpdateInteractableEventList(List<InteractableEvent> events)`. We could guard the call with a GetComponent check, and the cost should be reasonable as we are likely not adding new events frequently. This approach could be better than using a new `ReceiverUnityEvent` as it doesn't trigger multiple event calls when `SetupEvents()` is called (we are passing a list to `PhysicalPressEventRouter`) and the mechanism will be hidden from developers so that the already complex inspector of `Interactable` does not get worse.

By the way, I think it might be a good idea to let SuppressClick be set on `PhysicalPressEventRouter` instead of `InteractableOnHoldReceiver`s as technically we could have more than one `InteractableOnHoldReceiver`.

And yes, I don't think there is a remove receiver function.

**Comment by RogPodge** [comment]
@FlorianJa Do you think you'll be able to retarget this branch to 2.8.0 and pull in the latest code from there as well? I think we might be ok with getting this PR in, even if it doesn't support scenarios where this component is added after the `PhysicalPressEventRouter` is already initialized. What we'll need though is:

1. Documentation describing this limitation
2. Ideally a unit test showing the desired behavior when everything is properly configured before intialization

Thanks for your contributions!!!

**Pull request closed without merging**
