### PR TITLE
Add support for Leap UnityModules 4.9.1

### PR DESCRIPTION
**Pull request by Craig-J**
## Overview
Add support for 4.9.1 UnityModules - release notes available [here](https://github.com/leapmotion/UnityModules/releases/tag/UM-4.9.1).

## Verification
Run through [Using Leap](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrtk-unity/supported-devices/leap-motion-mrtk?view=mrtkunity-2021-05) and try out the example scenes in Head and Desk mode. 4.9.1 can be downloaded from the release page above or from the [Ultraleap Developer Site](https://developer.leapmotion.com/unity).

Pull request for the docs repo to come shortly.

### CODE REVIEW

**Comment by Craig-J** [comment]
> @keveleigh @Craig-J I'm just sitting together with UltraLeap in the MS MTC in Munich :) I think in general enabling every single minor version of LeapMotion is exhausting. It seems since version 4.7.1 the versioning mess is gone and the asmdef is also not needed anymore. I suggest we either use a regex for the version check like 4.* or just automatically allow all new versions. I will reach out to the UltraLeap dev team to make them aware of this issue.

I'm part of the dev team at Ultraleap which is responsible for UnityModules. I don't think it's a lot of effort to support new versions especially now that we're back on track keeping the version.txt up to date.

We will likely want to revisit the configuration checker in the next major versions of both our plugin (5.x - as there is likely to be breaking changes requiring new or modified logic) and MRTK (3.x - the major version bump is an opportunity to remove any deprecated logic no longer required for UnityModules versions that the MRTK team no longer want to support).

**Comment by ltwlf** [comment]
@Craig-J thanks for the clarification. And sorry, I didn't see that you're from ultraleap :) We were prototyping an ultrahaptic integration for MRTK/HoloLens 2.

**Comment by CDiaz-MS** [comment]
> We will likely want to revisit the configuration checker in the next major versions of both our plugin (5.x - as there is likely to be breaking changes requiring new or modified logic) and MRTK (3.x - the major version bump is an opportunity to remove any deprecated logic no longer required for UnityModules versions that the MRTK team no longer want to support).

@Craig-J Yes we will, MRTK v3 will likely utilize the LeapMotion OpenXR plugin (https://developer.leapmotion.com/openxr) and remove the logic required for the v2 configuration checker.

**Review by CDiaz-MS — APPROVED** [review]
Tested on Unity 2019.4 with Gemini 5.2.  Looks good to me.

**Pull request merged**
