### PR TITLE
Gesture Profile Fixes

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Added gesture type filter so it's impossible to register the same gesture twice.

Changes
---
- Fixes: #2912

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@krishnan-unni can you confirm this fixes the bug you found?

**Comment by krishnan-unni** [comment]
@StephenHodgson is this merged to mrtk_development?

**Comment by StephenHodgson** [comment]
You'll need to pull my branch and check.

You can view the changes by clicking on the right most tab at the top of this page.

**Comment by krishnan-unni** [comment]
@StephenHodgson I picked your fork from https://github.com/StephenHodgson/MixedRealityToolkit-Unity and tested it. Doesn't looks like it is fixed. I am still able to add Multiple actions to the same Gesture type though the profile.
capture

**Comment by StephenHodgson** [comment]
Did you pull the specific branch with this fix?

What were your steps so I can reproduce this?

**Comment by krishnan-unni** [comment]
Yup. My bad. I pulled the Dev branch. Missed the tag of the gesture fixes. I'll pull that and let you know. To test you need to create a config profile, input system profile action profile and gesture profile. Assign them all to config profile and try to create more gestures in gesture profile and assign same actions again. If the fix is working it shouldn't allow 1 gesture type to be assigned more than once

**Comment by StephenHodgson** [comment]
>  shouldn't allow 1 gesture type to be assigned more than once

Sounds good to me!

**Comment by krishnan-unni** [comment]
Yup, confirmed. Its working.  A trivia -  The new gestures have no default description appearing anymore. Not a deal breaker. Just an observation.
capture

**Comment by krishnan-unni** [comment]
@StephenHodgson  Is the Spatial mapping\understanding related features complete? Couldn't find the code related to them.

**Comment by keveleigh** [comment]
@krishnan-unni

The spatial mapping components are currently in review at https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2917, but the spatial understanding components haven't made their way over yet.

**Comment by StephenHodgson** [comment]
Please keep on topic.

If you have any questions like that please ping us in the mixed reality channel on slack or open a new issue with the question.

**Comment by krishnan-unni** [comment]
@StephenHodgson sure. Sorry, and thank you :)

**Pull request merged**
