### PR TITLE
UNET package for HoloLens Collaboration compatible with Holotoolkit 2…

### PR DESCRIPTION
**Pull request by virendrasuryavanshi**
2017.4.3.0

Overview
---
This PR is a follow up of the PR #3465 .
@davidkline-ms

### CODE REVIEW

**Comment by davidkline-ms** [comment]
Thank you @virendrasuryavanshi!

**Comment by davidkline-ms** [comment]
We will look at this as soon as possible.

**Comment by chrisfromwork** [comment]
@virendrasuryavanshi is there a commit history/source branch associated with these changes that may provide more insight into what scripts you had to change in the HTK/Sharing code base in order to get UNet working correctly? It seems like this binary can provide a lot of worth to new projects, but it may be a bit difficult to migrate existing HTK projects to use these changes without this information.

**Comment by virendrasuryavanshi** [comment]
@chrisfromwork Actually I was working on one of my project when I faced issues with UNET package with latest HoloToolkit and I had to remove all errors and modify the scripts to make it work for me and then thought of sharing it with everyone so they can save their time from doing this modifications and solving the errors but sorry as I was not doing that by maintaining every change through version control So I don't have complete record of what changes I did and what scripts I modified.

**Comment by davidkline-ms** [comment]
@virendrasuryavanshi, would you be ok with us unpacking your unitypackage and submitting the relevant changes? we would essentially import the latest HTK, import your package and the diff with a known baseline.

thanks!

**Comment by virendrasuryavanshi** [comment]
@davidkline-ms Sure, No issues with that. I hope my work can be helpful. But If you don't mind please Just give me an update after you try it.

**Comment by davidkline-ms** [comment]
We surely will! Thanks for the contribution!

**Comment by virendrasuryavanshi** [comment]
Any Updates? Sorry to be annoying, Just eager to know was it helpful?

**Comment by wiwei** [comment]
Just posting back here, on our side unfortunately we haven't had the cycles to do the due diligence and push these changes through in the right way. We're investing heavily in a new round of work to go along with HoloLens 2 and investment isn't happening in the previous HTK right now. I'll be closing this out as we don't have the time to do the right coverage on this change at this time.

**Pull request closed without merging**
