### PR TITLE
Update LostTrackingService for Unity 2020 and XRSDK/WMR

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

Updates the LostTrackingService to no longer call into removed legacy XR APIs (`WorldManager`) on Unity 2020.
Also adds support for the replacement APIs in ARSubsystems' XRSessionSubsystem. This required a new reference to that assembly, and I reused the existing `ARFOUNDATION_PRESENT` define, since have ARFoundation implies ARSubsystems.

## Changes

- Part of #8269

### CODE REVIEW

**Comment by keveleigh** [comment]
Adding `DO NOT MERGE` while I investigate using ARSessionSubsystem instead, which would help make this more cross-compatible.

**Comment by keveleigh** [comment]
Temporarily closing this out while I rethink the approach

**Comment by davidkline-ms** [comment]
:shipit:

**Pull request merged**
