### PR TITLE
Xbox Controller Updates

### PR DESCRIPTION
**Pull request by StephenHodgson**
- Addresses some feedback from @keveleigh.
- Adds a `None` enum to the `XboxControllerMappingTypes` that will break all existing settings.
    - Sorry, `None` should have been there from the beginning!
- Added a `XboxControllerHanderBase` for easily creating your own implementations.
    - Handy helper functions for getting buttons based on enum to change/update inputs on the fly.
- Added optional parameters to `XboxControllerSource` when overriding events on the `StandaloneInputModule`

### CODE REVIEW

**Comment by DDReaper** [comment]
Was looking at how to bring this forward to the Develop2017.2 branch, however these classes have been removed there :S

**Comment by keveleigh** [comment]
@DDReaper These classes never existed there. These are new, added to master in #936. The Dev branch has an implementation of Gamepad input, mostly in [GamepadInput.cs](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Unity_2017.2.0/Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs), which added "gesture" support via the gamepad, but not discrete button mappings.

**Comment by DDReaper** [comment]
Ok, I'll check that out, as I'm getting no input from the Wireless Original Xbox One controller currently @keveleigh (Just tested your PR)
Controller works fine in MRPortal.

**Comment by StephenHodgson** [comment]
@DDReaper, did you implement the InputManager.asset?

**Comment by DDReaper** [comment]
Ok, figured out the problem. As noted in #964 , the base dev branch is broken for Immersive headsets.
Headmovement and gaze functions, but the MR camera is floating and Xbox controllers don't work.  Fixed by pulling in @keveleigh s fixes

**Comment by StephenHodgson** [comment]
@DDReaper this PR has nothing to do with the dev branch.

**Pull request merged**
