### PR TITLE
updated nuget docs for version 2.1.0 on github io

### PR DESCRIPTION
**Pull request by thalbern**
docfx update for minor doc changes of nuget docs in version 2.1.0

### CODE REVIEW

**Comment by keveleigh** [comment]
This was auto generated by the pipelines, but to the wrong folder. Any ideas why?

https://github.com/microsoft/MixedRealityToolkit-Unity/tree/gh-pages/version/leases/2.1.0/Documentation/MRTKNuGetPackage.html

**Comment by thalbern** [comment]
> This was auto generated by the pipelines, but to the wrong folder (`leases` vs `releases`). Any ideas why? Would be great to just have it rebuild release docs when they're submitted!
> 
> https://github.com/microsoft/MixedRealityToolkit-Unity/tree/gh-pages/version/leases/2.1.0/Documentation/MRTKNuGetPackage.html

- this just looks like a typo in the build script - @MenelvagorMilsom can you check this?
- or could have been a manual deploy fail

@keveleigh this shouldn't be related to this change - i just did this manually for the tiny patch i did on the nuget docs
afaik we're doing manual deploys from release branches atm bc there's no need for regular deploys - @davidkline-ms  please correct me if i'm wrong!

**Comment by thalbern** [comment]
> > This was auto generated by the pipelines, but to the wrong folder (`leases` vs `releases`). Any ideas why? Would be great to just have it rebuild release docs when they're submitted!
> > https://github.com/microsoft/MixedRealityToolkit-Unity/tree/gh-pages/version/leases/2.1.0/Documentation/MRTKNuGetPackage.html
> 
> * this just looks like a typo in the build script - @MenelvagorMilsom
>               
>               Niall Milsom
>               FTE can you check this?
> * or could have been a manual deploy fail
> 
> @keveleigh Kurtis Eveleigh FTE this shouldn't be related to this change - i just did this manually for the tiny patch i did on the nuget docs
> afaik we're doing manual deploys from release branches atm bc there's no need for regular deploys - @davidkline-ms David Kline (ANALOG) FTE please correct me if i'm wrong!

oh wait! sry didn't see that this was generated out of my commit into that branch - defo @MenelvagorMilsom  should have a look at that!

**Comment by keveleigh** [comment]
@thalbern The release branches have the docs pipeline turned on, but they seem to be resolving the branch name incorrectly. I copied it over the first time (https://github.com/microsoft/MixedRealityToolkit-Unity/commit/cef8d3356184bb2d03774959990abd403ae4b3b1), and it looks like it happened again after your PR was merged: https://github.com/microsoft/MixedRealityToolkit-Unity/commit/0e471354f4c4c66f011e159eed6c43b37e25ad81

**Comment by MenelvagorMilsom** [comment]
image

Turns out that `TrimStart` removes all characters from the start of a string up until the first character not in the trim string.

I swapped this for a `Replace` and everything seems to have committed into the right place now:

https://github.com/microsoft/MixedRealityToolkit-Unity/commits/gh-pages/version/releases/2.1.0

We should probably remove the "leases" folder and its contents

**Pull request closed without merging**
