### PR TITLE
Experience Settings profile can now be set to None

### PR DESCRIPTION
**Pull request by RogPodge**
## Overview
Some quirks with how the Unity Assets are loaded vs when the inspector code runs causes issues in Unity 2020 with MRTK profiles. This PR fixes two points.

1. Experience settings profiles can now be set to None by default. This fixes issues with new profiles not having their experience settings loaded correctly by default upon creation. Additional checks and warnings are raised in the case of the Experience Settings profile being set to None

2. Cloning a profile no longer forces focus back to the MixedRealityToolkit object. Previously, the inspector of the profile would update to reflect the new, editable status of the profile, but as of Unity 2020, the profile will appear to still be a "default" profile and have it's fields disabled. By changing the selection focus, we circumvent this issue

## Changes
- Fixes: #9979

### CODE REVIEW

**Comment by RogPodge** [comment]
Added a fix thanks to @MaxWang-MS to retain the old behavior of not changing the selection focus upon cloning the profile

**Review by davidkline-ms — APPROVED** [review]

**Comment by davidkline-ms** [comment]
Let's bring this up with the team for a 2.7.1 release.

**Comment by keveleigh** [comment]
> Let's bring this up with the team for a 2.7.1 release.

I'd have a couple other proposals to include as well

**Pull request merged**
