### PR TITLE
Prevents build failure

### PR DESCRIPTION
**Pull request by Naphier**
## Overview
Prevents build failure when buildInfo.Configuration or buildInfo.BuildPlatform are empty or whitespace. Addresses #5434
Simply adds a couple of null/whitespace checks on the above variables and sets them to safe defaults so that the build can proceed. Warning is displayed in console so dev can debug if necessary.

## Changes
- Fixes: #5434

### CODE REVIEW

**Comment by wiwei** [comment]
Thanks for sending this PR!

@Naphier, can you take a look at my comments in the issue before this goes in:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5434

I think that these changes seem fine, I just want to make sure they're still needed after the couple of bug fixes that have gone into mrtk_development

**Comment by Naphier** [comment]
I'm not completely certain they're needed. Weird thing is that somewhere, while testing, EditorBuildPrefs starting having the right platform. So it's a bit hard to diagnose / reproduce. Hence just a check with warnings. 
Maybe it's better if I just fail the build if either of those are null/whitespace?
Main problem is that MSBuild outputs something like `invalid build option 'master|'` which is far from helpful in figuring out what went wrong.
What do you think?

**Comment by wiwei** [comment]
Ah, it looks like we're chatting in both the issue and the PR - let's keep the discussion in one place (in the issue, because that's where the most information is) - we can resolve stuff there and then circle back here after!

**Comment by wiwei** [comment]
Closing this down while discussion is happening here - I wanted to reiterate that the change itself looks fine, I just want to make sure that it's still needed with the latest in mrtk_development

**Pull request closed without merging**
