### PR TITLE
fix 10216: prefab needs to be available to 2+ samples

### PR DESCRIPTION
**Pull request by davidkline-ms**
## Overview
This change moves the FingerChaser prefab from Demos - Utilities to the Common folder in the Examples package to make it available to the Demos - Input sample as well.

## Changes
- Fixes: #10216

### CODE REVIEW

**Comment by keveleigh** [comment]
@davidkline-ms is this going into 2.7.3?

**Comment by davidkline-ms** [comment]
> @davidkline-ms is this going into 2.7.3? And if so, can it target the release branch?

Thanks for the catch! I missed that step...

**Review by keveleigh — APPROVED** [review]

**Pull request merged**
