### PR TITLE
Fix 5625 - fix observer volume

### PR DESCRIPTION
**Pull request by davidkline-ms**
- Document that the observer origin is in world space.
- Update the observer volume update to properly transform the coordinate space.

@fast-slow-still, can you please validate this change (review the code and test your scenario)?

Fixes: #5625

### CODE REVIEW

**Comment by davidkline-ms** [comment]
@fast-slow-still,

There is a test failure that appears to be related to this change. It feels like the transform is causing the meshes to not be placed correctly... I will add you as a collaborator to my fork. please feel free to push any changes.

**Comment by fast-slow-still** [comment]
It looks like the test failure was a red herring. After running the failing test both in isolation and in the full suite several times locally without error, I re-ran the tests on CI and all three passed. That was before any code changes.

I did push a few minor tweaks. Mostly I clarified the distinction between camera space and the camera's parent's space, and took advantage of the camera's parent being known to be the MixedRealityPlayspace.

I also added the rotation of the ObserverVolume's orientation from world to Playspace.

These are all pretty minor, so if you want to rollback my push, I'm fine with that. My situation was already fixed by your changes.

I do want to stress that this only affects the region of the world in which spatial meshes are generated, but does not affect the positioning of meshes.

**Comment by davidkline-ms** [comment]
Thanks @fast-slow-still! I love your changes.

**Pull request merged**
