### PR TITLE
Creation of the first example scene

### PR DESCRIPTION
**Pull request by SimonDarksideJ**
Overview
---
Basic first example scene, aiming to mimic the WMR startup experience and Start-up view
Aims to demonstrate the primitive basics of vNext operation such as:

* Look
* Pointers
* Basic interaction (still missing interaction scripts)
* Teleporting

> This scene should use **NO additional scripts** where possible. It's aim is to demonstrate the "out of the box" experience the SDK provides.  New profiles (input actions / controller config) are ok, to show the full extent of what is needed to build a project.

image

Aim is to ensure it is a professional looking scene that is engaging as well as educational

Changes
---
- Added scene start
- Added some additional scene assets from HTK
- Also ported the Bounding Box assets as they will be needed later

TODO
---
- [ ] Styling on Scene - help please
- [ ] Lighting / shader effects in interactables - glow on focus
- [ ] Interact sound on click, effect on click
- [x]  Background audio from scene and scene objects required, similar to WMR experience
- Tutorial script / audio (pushed to Beta)
- [ ] Tutorial / example documentation, walking through creation and use of the scene (example panel?)
- [ ] Input config / profiles
- [ ] Input interactions to Activate / Grab and Drop objects in the scene.
- [x] Visualize floor and play area (inscribed within boundary)

Replaces PR #2511 with a branch against main development

### CODE REVIEW

**Comment by davidkline-ms** [comment]
@SimonDarksideJ, other than updating to the latest dev code, what is required for alpha? We spoke internally and believe that the voice-over audio can wait for beta. I have background audio and an update to the sfx files that I will add.

**Comment by SimonDarksideJ** [comment]
Well @davidkline-ms practically all of the TODO, we can skip over some of the non-essential / post production items.
However, currently it is just a static scene, until we have Pointers, interactions merged, it doesn't DO much.

Will need someone to pick this up while I'm off on holiday, hence why I pushed the two example scenes to the main repo so I don't block work.

The Aims of the first example are listed in the overview above.

I tried to find time to start on the Tutorial documentation but lost out, I will have my PC with me while i'm away, so (internet pending) I'll try and write up something when i can.

**Comment by davidkline-ms** [comment]
@SimonDarksideJ,
Kurtis and I will pick them up. Thanks for getting them started!

**Comment by SimonDarksideJ** [comment]
Made a start at the tutorial documentation for the example
https://github.com/SimonDarksideJ/MixedRealityToolkit-Unity/blob/mrtk_development_example_Scene_1/Assets/MixedRealityToolkit-Examples/SDK/Example01-BasicIntroduction/README.md

**Comment by SimonDarksideJ** [comment]
This was supposed to be in alpha, what happened @DavidKline-ms? I thought you and kurtis picked this up.

**Comment by davidkline-ms** [comment]
> This was supposed to be in alpha, what happened

We focused on the demo scenes and getting controllers / boundaries / etc to automatically appear everywhere.

**Comment by davidkline-ms** [comment]
Closing while the team works on plans for example scenes.

**Pull request closed without merging**
