### PR TITLE
Remove warnings in Unity 2019

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview
MixedRealityToolkitFacadeHandler and ServiceFacadeInspector:
image

Platform Utility:
image
image

MixedRealityEditorSettings:
image

Note: This doesn't remove all issues with 2019.3, as that version adds a requirement for the `Unity.ugui` package to be added to all our asmdefs (#4545). Unfortunately, that fix is backwards compatible with previous versions of Unity 2019 but causes errors in Unity 2018.

## Fixes
Fixes: #4831

### CODE REVIEW

**Comment by SimonDarksideJ** [comment]
Suggest you also look to resolving #4931 as part of this PR.  Simply add a reference to "Unity UI" to Foundation and SDK (possibly Examples) asmdefs

**Comment by keveleigh** [comment]
@SimonDarksideJ Unfortunately, adding that reference is backwards compatible with previous versions of Unity 2019 but causes errors in Unity 2018.

**Pull request merged**
