### PR TITLE
Revert #8005 (restore #7986 "Automates the process of updating MRTK version metadata")

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

This change reverts #8005, which itself reverted #7986 due to a resulting CI failure. As far as I can tell, the CI failure happened due to misaligned indentation in a yml file, which this PR additionally fixes up. Please see the above linked PRs for more information about this change.

### CODE REVIEW

**Comment by davidkline-ms** [comment]
By removing the AssemblyInfo.cs files, doesnt that preclude a local build having the version information in the assemblies?

**Comment by keveleigh** [comment]
>By removing the AssemblyInfo.cs files, doesnt that preclude a local build having the version information in the assemblies?

I think @wiwei answered that (or a similar question) at https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7986#discussion_r431905741

**Comment by wiwei** [comment]
Thanks @keveleigh !

**Pull request merged**
