### PR TITLE
Fix rigged hands in remoting

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

This PR updates the rigged hands logic to not display when a transparent display is used, like over remoting. We'd been getting reports of rigged hands not aligning well with the physical hands and causing confusion.

This also fixes some potential null refs when the rigged hand material isn't set.
This also simplifies one of the controller visualization profiles that wasn't using "both" handedness for certain entries.
This also includes some like formatting and style updates for simplification.

### CODE REVIEW

**Comment by RogPodge** [comment]
Noticed we're still carrying around an "ObsoleteXRSDKProfile". Is this something we think we can just remove? Otherwise I'm not sure we should be changing any properties on that profile.

**Comment by MaxWang-MS** [comment]
I am not fan of removing profiles in a patch release though.

**Comment by keveleigh** [comment]
> I am not fan of removing profiles in a patch release though.

Agreed. It could be a big breaking change if people currently have it assigned unless we introduce a migration path.

> Otherwise I'm not sure we should be changing any properties on that profile.

I'm fine reverting the changes here. Mostly, one of the paths was referencing an also-marked-obsolete hand joint prefab and there were duplicate entries, but if we think that's risky I'm happy to revert!

**Comment by RogPodge** [comment]
No super strong opinions, I'll leave it to your judgement. I just wanted to raise the possibility of extra breaking changes.

**Review by RogPodge — APPROVED** [review]

**Review by MaxWang-MS — APPROVED** [review]

**Pull request merged**
