### PR TITLE
Fixes Interaction Sources not properly being registered at startup in some cases

### PR DESCRIPTION
**Pull request by StephenHodgson**
Added delayed initialization in `OnEnable` to wait until `Start` in case the `InputManager` instance isn't ready.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@keveleigh is this closer to what you were talking about?

**Comment by keveleigh** [comment]
Much closer! It still ties `InitializeSources()` to the state of `InputManager` though. If `InputManager`'s `Awake` gets called before this scipt, this will still result in other scripts potentially getting a `SourceDetected` before their `Awake` has been called. Setting `delayInitialization` to true initially and changing it to `false` in `Start` (while leaving everything else the same) would fix that.

**Comment by keveleigh** [comment]
Also, my comment on the other PR about

> It's also possible doing this at the beginning of an app might have the `InputManager` fire two `SourceDetected` events. 

is wrong. The Toolkit's `InputManager` keeps its own reference of detected sources and takes that into account!

**Comment by StephenHodgson** [comment]
@LocalJoost I'd also like your input if you don't mind. Just want to confirm this also fixes the issue you're running into.

**Comment by LocalJoost** [comment]
Just came back home. It's evening here. Tomorrow I will have a look. Like I said I have wasted quite some time already because on this issue.

Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by LocalJoost** [comment]
Tried in my app, seems to work for me as well. @keveleigh Sorry for the somewhat annoyed reaction, I get that when a bug took so much time. I also was wondering 'who the hell is this guy anyway' - well, someone from Microsoft, not just Joe Random Contributor ;)

**Pull request merged**
