### PR TITLE
Fix for #8733: Limit migration tool to Assets folder tree

### PR DESCRIPTION
**Pull request by davidkline-ms**
#8733 identified a bug in the migration tool in which it is searching for assets in immutable folders. With the MRTK being provided as UPM packages, this causes a failure to load scene error when the scene system scenes (ex: DefaultLightingScene) are encountered.

This change limits the migration tool to only work on files in the Assets folder tree.

It does _not_ fix the inability to load the scenes (that change is forthcoming in a new PR_)

**_This change should be considered for a 2.5.1 UPM release as it prevents customers from using the Migration Tool._**

Fixes: #8733

### CODE REVIEW

**Comment by davidkline-ms** [comment]
Please do not merge until we determine in which branch a future UPM update will reside.

**Review by keveleigh — APPROVED** [review]

**Pull request merged**
