### PR TITLE
[Asset] Adding MRTK Logo GLTF file

### PR DESCRIPTION
**Pull request by cre8ivepark**
## Overview
Adding MRTK Logo GLTF file which can be used for the app launcher icon(aka Live cube).

## Screenshots
2019-07-19 23_31_20-Unity 2018 4 2f1 Personal - Glb-Loading-Demo unity - MRTK-GitHub - PC, Mac   Lin

MRTK_GLTF1

## How to create 3D launcher
https://docs.microsoft.com/en-us/windows/mixed-reality/implementing-3d-app-launchers

### Summary
1. Add .glb file to the Asset folder in VS, set the 'Content' as 'True'
2. Edit appx manifest file, replace two areas with below:

```
XML Namespace area:
<Package xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:uap2="http://schemas.microsoft.com/appx/manifest/uap/windows10/2" xmlns:uap5="http://schemas.microsoft.com/appx/manifest/uap/windows10/5" xmlns:uap6="http://schemas.microsoft.com/appx/manifest/uap/windows10/6" xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" IgnorableNamespaces="uap uap2 uap5 uap6 mp">

Default Tile area:
        <uap:DefaultTile ShortName="MixedRealityToolkit" Wide310x150Logo="Assets\Wide310x150Logo.png" Square310x310Logo="Assets\LargeTile.png" Square71x71Logo="Assets\SmallTile.png">
          <uap5:MixedRealityModel Path="Assets\MRTK_Logo.glb">
          <uap6:SpatialBoundingBox  Center="0.5,0.5,0.5" Extents="0.5,0.5,0.5" />
          </uap5:MixedRealityModel>
        </uap:DefaultTile>
```

### CODE REVIEW

**Comment by wiwei** [comment]
lgtm, though question around how this is gonna get used in the future - do you plan on updating any docs to explain this, or create some other example that shows how this is going to be used? Otherwise there is a risk that this could just become a dangling (albiet, cool) asset.

**Comment by keveleigh** [comment]
@wiwei we could probably add something to our build tooling (similar to what you did with the gaze capability) to set this in the appx manifest at build time. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/1231

**Comment by cre8ivepark** [comment]
The official docs (https://docs.microsoft.com/en-us/windows/mixed-reality/implementing-3d-app-launchers) should be enough to explain 'how to use' the 3D launcher but definitely, it would be helpful to have docs in MRTK. It also makes me think of creating docs that explains available common assets in MRTK - Fonts, Textures, 3D models, etc... I'll think about the structure.

**Pull request merged**
